{
	"alias": "FEDORA-2019-20bc611b61",
	"bugs": [
		{
			"bug_id": 1700825,
			"feedback": [
				{
					"bug_id": 1700825,
					"comment": {
						"id": 952441,
						"karma": 1,
						"karma_critpath": 1,
						"text": "works as expected",
						"timestamp": "2019-05-29 08:23:46",
						"update_id": 140192,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5ed589dd93c3ff16e0ea2fc0f186dc1f2de667f3d60c0e168cb18fbaf3455286?s=24&d=retro",
							"email": "lnie@redhat.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								}
							],
							"id": 307,
							"name": "lnie",
							"openid": "lnie.id.fedoraproject.org"
						},
						"user_id": 307
					},
					"comment_id": 952441
				}
			],
			"security": true,
			"title": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service. [fedora-all]",
			"bugzilla": {
				"bug_id": "1700825",
				"creation_ts": "2019-04-17 12:48:12 +0000",
				"short_desc": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service. [fedora-all]",
				"delta_ts": "2019-06-13 01:38:06 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1700824",
						"alias": "CVE-2019-11236",
						"creation_ts": "2019-04-17 12:48:04 +0000",
						"short_desc": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
						"delta_ts": "2021-12-14 18:47:58 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1697188",
							"1697189",
							"1697190",
							"1697191",
							"1697192",
							"1697193",
							"1700825",
							"1703360",
							"1703361",
							"1703363",
							"1703458",
							"1706762",
							"1707088",
							"1724439",
							"1775363",
							"1775364",
							"1775365",
							"1778100",
							"1778101",
							"1778103",
							"1778107",
							"1778108",
							"1778109",
							"1778113",
							"1778114",
							"1778115",
							"1778116",
							"1778117",
							"1805086",
							"1805087",
							"1805088",
							"1805089",
							"1822420",
							"1822421"
						],
						"blocked": [
							{
								"bug_id": "1700840",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2020:2081",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12647293",
								"comment_count": "0",
								"who": {
									"text": "mrehak",
									"name": "Marian Rehak"
								},
								"bug_when": "2019-04-17 12:48:04 +0000",
								"thetext": "The current implementation of python-urllib3 does not encode the ‘\\r\\n’ sequence in the query string, which allowed the attacker to manipulate a HTTP header with the ‘\\r\\n’ sequence in it, so the attacker could insert arbitrary content to the new line of the HTTP header.\n\nExternal References:\nhttps://bugs.python.org/issue36276"
							},
							{
								"isprivate": "0",
								"commentid": "12647296",
								"comment_count": "1",
								"who": {
									"text": "mrehak",
									"name": "Marian Rehak"
								},
								"bug_when": "2019-04-17 12:48:17 +0000",
								"thetext": "Created python-urllib3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1700825]"
							},
							{
								"isprivate": "0",
								"commentid": "12650233",
								"comment_count": "2",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2019-04-18 11:02:43 +0000",
								"thetext": "Additional references:\n\nhttps://github.com/urllib3/urllib3/issues/1553\nhttps://github.com/urllib3/urllib3/commit/0aa3e24fcd75f1bb59ab159e9f8adb44055b2271"
							},
							{
								"isprivate": "0",
								"commentid": "12670858",
								"comment_count": "8",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2019-04-26 14:02:44 +0000",
								"thetext": "This issue is reproducible on Red Hat Gluster Storage 3, successfully injected the HTTP header. If an attacker manages to place a CRLF then he could exploit this vulnerability."
							},
							{
								"isprivate": "0",
								"commentid": "12706796",
								"comment_count": "13",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2019-05-06 19:12:41 +0000",
								"thetext": "All supported versions of Red Hat OpenStack Platform are affected by this flaw."
							},
							{
								"isprivate": "0",
								"commentid": "12706798",
								"comment_count": "14",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2019-05-06 19:12:54 +0000",
								"thetext": "Created python-urllib3 tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1707088]"
							},
							{
								"isprivate": "0",
								"commentid": "13032828",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-08-06 12:34:20 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2019:2272 https://access.redhat.com/errata/RHSA-2019:2272"
							},
							{
								"isprivate": "0",
								"commentid": "13036494",
								"comment_count": "19",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2019-08-06 19:20:56 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2019-11236"
							},
							{
								"isprivate": "0",
								"commentid": "13329358",
								"comment_count": "20",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-11-05 20:38:10 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:3335 https://access.redhat.com/errata/RHSA-2019:3335"
							},
							{
								"isprivate": "0",
								"commentid": "13330466",
								"comment_count": "21",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-11-05 21:16:11 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:3590 https://access.redhat.com/errata/RHSA-2019:3590"
							},
							{
								"isprivate": "0",
								"commentid": "13385697",
								"comment_count": "22",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-11-21 15:42:57 +0000",
								"thetext": "Upstream patch for 1.24 versions:\nhttps://github.com/urllib3/urllib3/commit/efddd7e7bad26188c3b692d1090cba768afa9162"
							},
							{
								"isprivate": "0",
								"commentid": "13386427",
								"comment_count": "23",
								"who": {
									"text": "thoger",
									"name": "Tomas Hoger"
								},
								"bug_when": "2019-11-21 19:31:42 +0000",
								"thetext": "There are actually 2 related patches for 1.24:\n\nhttps://github.com/urllib3/urllib3/commit/9b76785331243689a9d52cef3db05ef7462cb02d\nhttps://github.com/urllib3/urllib3/commit/efddd7e7bad26188c3b692d1090cba768afa9162\n\nThe second one is the one linked from comment 22 above, and it needs to be applied on top of the first one.  Both patches mention CVE-2019-9740 in the commit message, which is the CVE for similar problem in urllib/urllib2 that is part of Python standard library."
							},
							{
								"isprivate": "0",
								"commentid": "13386441",
								"comment_count": "24",
								"who": {
									"text": "thoger",
									"name": "Tomas Hoger"
								},
								"bug_when": "2019-11-21 19:38:11 +0000",
								"thetext": "Created python-pip tracking bugs for this issue:\n\nAffects: epel-6 [bug 1775364]\nAffects: fedora-all [bug 1775363]\n\n\nCreated python-pip-epel tracking bugs for this issue:\n\nAffects: epel-7 [bug 1775365]"
							},
							{
								"isprivate": "0",
								"commentid": "13413010",
								"comment_count": "25",
								"who": {
									"text": "thoger",
									"name": "Tomas Hoger"
								},
								"bug_when": "2019-11-29 10:24:18 +0000",
								"thetext": "Created python-virtualenv tracking bugs for this issue:\n\nAffects: epel-6 [bug 1778101]\nAffects: fedora-30 [bug 1778100]\n\n\nCreated python3-virtualenv tracking bugs for this issue:\n\nAffects: epel-7 [bug 1778103]"
							},
							{
								"isprivate": "0",
								"commentid": "13711385",
								"comment_count": "28",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-03-17 16:18:26 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0850 https://access.redhat.com/errata/RHSA-2020:0850"
							},
							{
								"isprivate": "0",
								"commentid": "13711389",
								"comment_count": "29",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-03-17 16:18:48 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0851 https://access.redhat.com/errata/RHSA-2020:0851"
							},
							{
								"isprivate": "0",
								"commentid": "13849945",
								"comment_count": "31",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-28 15:29:24 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1605 https://access.redhat.com/errata/RHSA-2020:1605"
							},
							{
								"isprivate": "0",
								"commentid": "13851289",
								"comment_count": "32",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-28 16:08:45 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1916 https://access.redhat.com/errata/RHSA-2020:1916"
							},
							{
								"isprivate": "0",
								"commentid": "13907633",
								"comment_count": "33",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-05-12 18:37:49 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2068 https://access.redhat.com/errata/RHSA-2020:2068"
							},
							{
								"isprivate": "0",
								"commentid": "13907642",
								"comment_count": "34",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-05-12 18:38:05 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2081 https://access.redhat.com/errata/RHSA-2020:2081"
							},
							{
								"isprivate": "0",
								"commentid": "14618909",
								"comment_count": "37",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2020-12-19 20:40:15 +0000",
								"thetext": "Statement:\n\nThis issue affects the version of python-urllib3 shipped with Red Hat Gluster Storage 3, as it is vulnerable to CRLF injection.\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected critical and important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12647294",
						"comment_count": "0",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2019-04-17 12:48:12 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "12647295",
						"comment_count": "1",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2019-04-17 12:48:14 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1700824,1700825\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "12780875",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-05-28 17:50:51 +0000",
						"thetext": "FEDORA-2019-fbda9f1e49 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-fbda9f1e49"
					},
					{
						"isprivate": "0",
						"commentid": "12786372",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-05-29 01:36:05 +0000",
						"thetext": "python-urllib3-1.24.3-1.fc30 has been pushed to the Fedora 30 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-20bc611b61"
					},
					{
						"isprivate": "0",
						"commentid": "12786490",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-05-29 02:27:02 +0000",
						"thetext": "python-urllib3-1.24.3-1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-fbda9f1e49"
					},
					{
						"isprivate": "0",
						"commentid": "12836662",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-06-12 14:47:15 +0000",
						"thetext": "python-urllib3-1.24.3-1.fc30 has been pushed to the Fedora 30 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12838565",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-06-13 01:38:06 +0000",
						"thetext": "python-urllib3-1.24.3-1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-urllib3-1.24.3-1.fc30",
			"release_id": 28,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-urllib3",
						"version": "1.24.3",
						"release": "1.fc30",
						"arch": "noarch"
					},
					{
						"name": "python2-urllib3",
						"version": "1.24.3",
						"release": "1.fc30",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-urllib3",
						"version": "1.24.3",
						"release": "1.fc30",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 952106,
			"text": "This update has been submitted for testing by jcline. ",
			"timestamp": "2019-05-28 17:50:48",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 952107,
			"text": "This update test gating status has been changed to 'waiting'.",
			"timestamp": "2019-05-28 17:50:49",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 952109,
			"text": "This update test gating status has been changed to 'ignored'.",
			"timestamp": "2019-05-28 17:50:52",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 952286,
			"text": "This update has been pushed to testing.",
			"timestamp": "2019-05-29 01:36:20",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1700825,
						"security": true,
						"title": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service. [fedora-all]"
					},
					"bug_id": 1700825,
					"comment_id": 952441
				}
			],
			"id": 952441,
			"karma": 1,
			"karma_critpath": 1,
			"text": "works as expected",
			"timestamp": "2019-05-29 08:23:46",
			"update_id": 140192,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/5ed589dd93c3ff16e0ea2fc0f186dc1f2de667f3d60c0e168cb18fbaf3455286?s=24&d=retro",
				"email": "lnie@redhat.com",
				"groups": [
					{
						"name": "qa"
					},
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 307,
				"name": "lnie",
				"openid": "lnie.id.fedoraproject.org"
			},
			"user_id": 307
		},
		{
			"id": 958719,
			"text": "This update has reached 14 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2019-06-12 06:00:07",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 958921,
			"text": "This update has been submitted for stable by jcline. ",
			"timestamp": "2019-06-12 13:43:45",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 958934,
			"text": "This update has been pushed to stable.",
			"timestamp": "2019-06-12 14:48:17",
			"update_id": 140192,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"date_pushed": "2019-06-12 14:47:01",
	"date_stable": "2019-06-12 14:47:01",
	"date_submitted": "2019-05-28 17:50:48",
	"date_testing": "2019-05-29 01:35:15",
	"karma": 1,
	"meets_testing_requirements": true,
	"notes": "Update to v1.24.3",
	"pushed": true,
	"release": {
		"branch": "f30",
		"candidate_tag": "f30-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f30",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 30",
		"mail_template": "fedora_errata_template",
		"name": "F30",
		"override_tag": "f30-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f30-signing-pending",
		"pending_stable_tag": "f30-updates-pending",
		"pending_testing_tag": "f30-updates-testing-pending",
		"stable_tag": "f30-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f30-updates-testing",
		"version": "30"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_karma": 2,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-urllib3-1.24.3-1.fc30",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2019-20bc611b61",
	"unstable_karma": -3,
	"updateid": "FEDORA-2019-20bc611b61",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/ea181a99533a98f797cc7164c217bf67096698ea9565cf60ea0c5dd420a8ce44?s=24&d=retro",
		"email": "jeremy@jcline.org",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "communishift"
			},
			{
				"name": "erlang"
			},
			{
				"name": "erlang-maint-sig"
			}
		],
		"id": 2383,
		"name": "jcline",
		"openid": "jcline.id.fedoraproject.org"
	},
	"version_hash": "eb00b32a68f1400685568403737407e534b338d9"
}
