{
	"alias": "FEDORA-2021-a8ddc1ce70",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1915427,
			"security": true,
			"title": "CVE-2020-35654 python-pillow: decoding crafted YCbCr files could result in heap-based buffer overflow [fedora-33]",
			"bugzilla": {
				"bug_id": "1915427",
				"creation_ts": "2021-01-12 16:07:49 +0000",
				"short_desc": "CVE-2020-35654 python-pillow: decoding crafted YCbCr files could result in heap-based buffer overflow [fedora-33]",
				"delta_ts": "2021-01-21 01:45:24 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1915424",
						"alias": "CVE-2020-35654",
						"creation_ts": "2021-01-12 16:06:02 +0000",
						"short_desc": "CVE-2020-35654 python-pillow: decoding crafted YCbCr files could result in heap-based buffer overflow",
						"delta_ts": "2022-05-17 10:26:06 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Reopened, Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1915425",
							"1915427",
							"1915429"
						],
						"blocked": [
							{
								"bug_id": "1915433",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2021:3917",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14666265",
								"comment_count": "0",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:06:02 +0000",
								"thetext": "In Pillow before 8.1.0, TiffDecode has a heap-based buffer overflow when decoding crafted YCbCr files because of certain interpretation conflicts with LibTIFF in RGBA mode.\n\nExternal References: \n\nhttps://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html#security"
							},
							{
								"isprivate": "0",
								"commentid": "14666270",
								"comment_count": "1",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:06:20 +0000",
								"thetext": "Created python-pillow tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1915425]"
							},
							{
								"isprivate": "0",
								"commentid": "14666278",
								"comment_count": "2",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:07:59 +0000",
								"thetext": "Created python-pillow tracking bugs for this issue:\n\nAffects: fedora-33 [bug 1915427]"
							},
							{
								"isprivate": "0",
								"commentid": "14669914",
								"comment_count": "4",
								"who": {
									"text": "pviktori",
									"name": "Petr Viktorin (pviktori)"
								},
								"bug_when": "2021-01-13 13:30:00 +0000",
								"thetext": "If Pillow can be removed from the Printing stack dependencies, it should be removed from RHEL9.\n\nAnyway, the fixed Pillow 8.1.0 is in Rawhide and ELN. The next build should pick it up."
							},
							{
								"isprivate": "0",
								"commentid": "14669921",
								"comment_count": "5",
								"who": {
									"text": "pviktori",
									"name": "Petr Viktorin (pviktori)"
								},
								"bug_when": "2021-01-13 13:30:54 +0000",
								"thetext": "Sorry, wrong bug. This one should stay open."
							},
							{
								"isprivate": "0",
								"commentid": "14671927",
								"comment_count": "6",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-01-13 23:42:19 +0000",
								"thetext": "Statement:\n\npython-pillow as shipped with Red Hat Enterprise Linux 7 and 8 are not affected by this flaw as the flaw was introduced in a newer version than shipped."
							},
							{
								"isprivate": "0",
								"commentid": "14679713",
								"comment_count": "7",
								"who": {
									"text": "manisandro",
									"name": "Sandro Mani"
								},
								"bug_when": "2021-01-15 18:31:20 +0000",
								"thetext": "Upstream patch: https://github.com/python-pillow/Pillow/commit/eb8c1206d6b170d4e798a00db7432e023853da5c"
							},
							{
								"isprivate": "0",
								"commentid": "14723941",
								"comment_count": "8",
								"who": {
									"text": "mcooper",
									"name": "Mark Cooper"
								},
								"bug_when": "2021-01-29 02:03:12 +0000",
								"thetext": "The following Quay containers contain python-pillow 7.2.0 and hence are affected by the CVE (checked upstream 7.2.0 contains the same vulnerable code):\n - quay-registry-container\n - quay-builder-qemu-rhcos-container"
							},
							{
								"isprivate": "0",
								"commentid": "14796101",
								"comment_count": "10",
								"who": {
									"text": "lbalhar",
									"name": "Lum√≠r Balhar"
								},
								"bug_when": "2021-02-18 08:23:09 +0000",
								"thetext": "I can confirm that the pillow in RHEL 8 is not vulnerable:\n\n# python3 image_load.py crash-2020-10-test.tif \n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 16908288 bytes but only got 0. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 67895296 bytes but only got 0. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1572864 bytes but only got 0. Skipping tag 42\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 116647 bytes but only got 4867. Skipping tag 42738\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 3468830728 bytes but only got 4851. Skipping tag 279\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2198732800 bytes but only got 0. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 67239937 bytes but only got 4125. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 33947764 bytes but only got 0. Skipping tag 139\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 17170432 bytes but only got 0. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 80478208 bytes but only got 0. Skipping tag 1\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 787460 bytes but only got 4882. Skipping tag 20\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 1075 bytes but only got 0. Skipping tag 256\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 120586240 bytes but only got 0. Skipping tag 194\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 65536 bytes but only got 0. Skipping tag 3\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 198656 bytes but only got 0. Skipping tag 279\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 206848 bytes but only got 0. Skipping tag 64512\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 130968 bytes but only got 4882. Skipping tag 256\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 77848 bytes but only got 4689. Skipping tag 64270\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 262156 bytes but only got 0. Skipping tag 257\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 33624064 bytes but only got 0. Skipping tag 49152\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 67178752 bytes but only got 4627. Skipping tag 50688\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 33632768 bytes but only got 0. Skipping tag 56320\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 134386688 bytes but only got 4115. Skipping tag 2048\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 33912832 bytes but only got 0. Skipping tag 7168\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 151966208 bytes but only got 4627. Skipping tag 10240\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 119032832 bytes but only got 3859. Skipping tag 256\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 46535680 bytes but only got 0. Skipping tag 256\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 35651584 bytes but only got 0. Skipping tag 42\n  \" Skipping tag %s\" % (size, len(data), tag))\n/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 524288 bytes but only got 0. Skipping tag 0\n  \" Skipping tag %s\" % (size, len(data), tag))\n_TIFFVSetField: tempfile.tif: Null count for \"Tag 769\" (type 1, writecount -3, passcount 1).\n_TIFFVSetField: tempfile.tif: Null count for \"Tag 42754\" (type 1, writecount -3, passcount 1).\n_TIFFVSetField: tempfile.tif: Null count for \"Tag 769\" (type 1, writecount -3, passcount 1).\n_TIFFVSetField: tempfile.tif: Null count for \"Tag 42754\" (type 1, writecount -3, passcount 1).\nZIPDecode: Decoding error at scanline 0, incorrect header check.\nZIPDecode: Decoding error at scanline 0, invalid stored block lengths.\nZIPDecode: Decoding error at scanline 0, incorrect data check.\nZIPDecode: Decoding error at scanline 0, invalid stored block lengths.\nZIPDecode: Decoding error at scanline 0, invalid distance too far back.\nZIPDecode: Decoding error at scanline 0, invalid distance code.\nZIPDecode: ZLib error: .\nTraceback (most recent call last):\n  File \"image_load.py\", line 6, in <module>\n    im.load()\n  File \"/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py\", line 1053, in load\n    return self._load_libtiff()\n  File \"/usr/lib64/python3.6/site-packages/PIL/TiffImagePlugin.py\", line 1145, in _load_libtiff\n    raise IOError(err)\nOSError: -2"
							},
							{
								"isprivate": "0",
								"commentid": "15598648",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-10-19 12:10:30 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Quay 3\n\nVia RHSA-2021:3917 https://access.redhat.com/errata/RHSA-2021:3917"
							},
							{
								"isprivate": "0",
								"commentid": "15599183",
								"comment_count": "15",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2021-10-19 14:08:33 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-35654"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14666276",
						"comment_count": "0",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:07:49 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-33.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message."
					},
					{
						"isprivate": "0",
						"commentid": "14666277",
						"comment_count": "1",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:07:51 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1915424,1915427\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14679914",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-15 20:08:41 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been submitted as an update to Fedora 33. https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70"
					},
					{
						"isprivate": "0",
						"commentid": "14680712",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-16 02:18:17 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-a8ddc1ce70`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14696992",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-21 01:45:24 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1915428,
			"security": true,
			"title": "CVE-2020-35653 python-pillow: decoding a crafted PCX file could result in buffer over-read [fedora-33]",
			"bugzilla": {
				"bug_id": "1915428",
				"creation_ts": "2021-01-12 16:08:07 +0000",
				"short_desc": "CVE-2020-35653 python-pillow: decoding a crafted PCX file could result in buffer over-read [fedora-33]",
				"delta_ts": "2021-01-21 01:45:28 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "low",
				"blocked": [
					{
						"bug_id": "1915420",
						"alias": "CVE-2020-35653",
						"creation_ts": "2021-01-12 16:03:05 +0000",
						"short_desc": "CVE-2020-35653 python-pillow: Buffer over-read in PCX image reader",
						"delta_ts": "2022-05-17 10:26:02 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"1915421",
							"1915422",
							"1915428",
							"1916008"
						],
						"blocked": [
							{
								"bug_id": "1915433",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2021:4149",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14666253",
								"comment_count": "0",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:03:05 +0000",
								"thetext": "In Pillow before 8.1.0, PcxDecode has a buffer over-read when decoding a crafted PCX file because the user-supplied stride value is trusted for buffer calculations.\n\nExternal References: \n\nhttps://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html#security"
							},
							{
								"isprivate": "0",
								"commentid": "14666258",
								"comment_count": "1",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:03:29 +0000",
								"thetext": "Created python-pillow tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1915421]"
							},
							{
								"isprivate": "0",
								"commentid": "14666282",
								"comment_count": "3",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:08:16 +0000",
								"thetext": "Created python-pillow tracking bugs for this issue:\n\nAffects: fedora-33 [bug 1915428]"
							},
							{
								"isprivate": "0",
								"commentid": "14671728",
								"comment_count": "4",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-01-13 21:50:38 +0000",
								"thetext": "Upstream patch: https://github.com/python-pillow/Pillow/commit/2f409261eb1228e166868f8f0b5da5cda52e55bf .\n\nNote that this patch says that it is for CVE-2020-35655 but the issue correponds to the upstream advisory and MITRE CVE for CVE-2020-35653[1][2].\n\n1. https://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html#security\n2. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-35653"
							},
							{
								"isprivate": "0",
								"commentid": "14671872",
								"comment_count": "6",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-01-13 23:16:17 +0000",
								"thetext": "Flaw summary:\n\nIn src/PIL/PcxImagePlugin.py PcxImageFile's _open() method accepted a `stride` length via `stride = i16(s, 66)` where `s` points to user-controlled input data from a PCX file. This meant that an attacker who is able to provide a crafted file with an invalid stride length could cause an out-of-bounds read that could potentially lead to an impact to application availability, or less likely, an impact to data confidentiality depending on how pillow is used in the application."
							},
							{
								"isprivate": "0",
								"commentid": "14723906",
								"comment_count": "8",
								"who": {
									"text": "mcooper",
									"name": "Mark Cooper"
								},
								"bug_when": "2021-01-29 01:52:06 +0000",
								"thetext": "The following Quay containers contain python-pillow 7.2.0 and hence are affected by the CVE (checked upstream 7.2.0 contains the same vulnerable code):\n - quay-registry-container\n - quay-builder-qemu-rhcos-container"
							},
							{
								"isprivate": "0",
								"commentid": "15598647",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-10-19 12:10:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Quay 3\n\nVia RHSA-2021:3917 https://access.redhat.com/errata/RHSA-2021:3917"
							},
							{
								"isprivate": "0",
								"commentid": "15599182",
								"comment_count": "12",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2021-10-19 14:08:28 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-35653"
							},
							{
								"isprivate": "0",
								"commentid": "15666999",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-11-09 17:24:14 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4149 https://access.redhat.com/errata/RHSA-2021:4149"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14666279",
						"comment_count": "0",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:08:07 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-33.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message."
					},
					{
						"isprivate": "0",
						"commentid": "14666280",
						"comment_count": "1",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:08:09 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1915420,1915428\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14679915",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-15 20:08:43 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been submitted as an update to Fedora 33. https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70"
					},
					{
						"isprivate": "0",
						"commentid": "14680713",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-16 02:18:19 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-a8ddc1ce70`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14696993",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-21 01:45:28 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1915434,
			"security": true,
			"title": "CVE-2020-35655 python-pillow: decoding crafted SGI RLE image files could result in buffer over-read [fedora-33]",
			"bugzilla": {
				"bug_id": "1915434",
				"creation_ts": "2021-01-12 16:11:53 +0000",
				"short_desc": "CVE-2020-35655 python-pillow: decoding crafted SGI RLE image files could result in buffer over-read [fedora-33]",
				"delta_ts": "2021-01-21 01:45:32 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "low",
				"blocked": [
					{
						"bug_id": "1915432",
						"alias": "CVE-2020-35655",
						"creation_ts": "2021-01-12 16:09:55 +0000",
						"short_desc": "CVE-2020-35655 python-pillow: Buffer over-read in SGI RLE image reader",
						"delta_ts": "2022-05-17 10:26:12 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"1915434",
							"1915435",
							"1915436",
							"1916023"
						],
						"blocked": [
							{
								"bug_id": "1915433",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2021:4149",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14666303",
								"comment_count": "0",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:09:55 +0000",
								"thetext": "In Pillow before 8.1.0, SGIRleDecode has a 4-byte buffer over-read when decoding crafted SGI RLE image files because offsets and length tables are mishandled.\n\nExternal References: \n\nhttps://pillow.readthedocs.io/en/stable/releasenotes/8.1.0.html#security"
							},
							{
								"isprivate": "0",
								"commentid": "14666323",
								"comment_count": "1",
								"who": {
									"text": "mkaplan",
									"name": "Michael Kaplan"
								},
								"bug_when": "2021-01-12 16:12:08 +0000",
								"thetext": "Created python-pillow tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1915435]\nAffects: fedora-33 [bug 1915434]"
							},
							{
								"isprivate": "0",
								"commentid": "14671948",
								"comment_count": "3",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-01-13 23:53:06 +0000",
								"thetext": "Upstream commit: https://github.com/python-pillow/Pillow/commit/120eea2e4547a7d1826afdf01563035844f0b7d5"
							},
							{
								"isprivate": "0",
								"commentid": "14671990",
								"comment_count": "5",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-01-14 00:20:34 +0000",
								"thetext": "Flaw summary:\n\nIn `ImagingSgiRleDecode()` of `src/libImaging/SgiRleDecode.c`, it's possible for a call to `malloc()` to request 4 bytes less than necessary, which can lead to a heap buffer overflow -> out-of-bounds read subsequently. The upstream patch moves length checks above the call to `malloc()` and exits `ImagingSgiRleDecode()` with an error code to avoid passing an improper length to `malloc()`.\n\nAn attacker who is able to submit a crafted SGI RLE file to an application using python-pillow to decode it, could trigger an out-of-bounds read."
							},
							{
								"isprivate": "0",
								"commentid": "14723947",
								"comment_count": "6",
								"who": {
									"text": "mcooper",
									"name": "Mark Cooper"
								},
								"bug_when": "2021-01-29 02:07:07 +0000",
								"thetext": "The following Quay containers contain python-pillow 7.2.0 and hence are affected by the CVE (checked upstream 7.2.0 contains the same vulnerable code):\n - quay-registry-container\n - quay-builder-qemu-rhcos-container"
							},
							{
								"isprivate": "0",
								"commentid": "15667000",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-11-09 17:24:19 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4149 https://access.redhat.com/errata/RHSA-2021:4149"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14666317",
						"comment_count": "0",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:11:53 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-33.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message."
					},
					{
						"isprivate": "0",
						"commentid": "14666318",
						"comment_count": "1",
						"who": {
							"text": "mkaplan",
							"name": "Michael Kaplan"
						},
						"bug_when": "2021-01-12 16:11:56 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1915432,1915434\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14679916",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-15 20:08:46 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been submitted as an update to Fedora 33. https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70"
					},
					{
						"isprivate": "0",
						"commentid": "14680714",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-16 02:18:21 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-a8ddc1ce70`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14696994",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-21 01:45:32 +0000",
						"thetext": "FEDORA-2021-a8ddc1ce70 has been pushed to the Fedora 33 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "mingw-python-pillow-7.2.0-3.fc33",
			"release_id": 40,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "mingw64-python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "noarch"
					},
					{
						"name": "mingw64-python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "noarch"
					},
					{
						"name": "mingw32-python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "noarch"
					},
					{
						"name": "mingw32-python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "mingw-python-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "src"
					}
				]
			}
		},
		{
			"epoch": 0,
			"nvr": "python-pillow-7.2.0-3.fc33",
			"release_id": 40,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					},
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "i686"
					}
				],
				"noarch": [
					{
						"name": "python3-pillow-doc",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "noarch"
					}
				],
				"ppc64le": [
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					},
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3-pillow-devel",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python3-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python3-pillow-tk",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python3-pillow-tk-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python-pillow-debuginfo",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python3-pillow-qt",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python-pillow-debugsource",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					},
					{
						"name": "python3-pillow",
						"version": "7.2.0",
						"release": "3.fc33",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1820539,
			"text": "This update has been submitted for testing by smani. ",
			"timestamp": "2021-01-15 20:08:38",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1820540,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-01-15 20:08:39",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1820541,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2021-01-15 20:08:39",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1820631,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-01-15 21:03:44",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1821276,
			"text": "This update has been pushed to testing.",
			"timestamp": "2021-01-16 02:18:27",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1824160,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2021-01-18 10:16:27",
			"update_id": 272457,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/054959f4db5d1ad8f22cae1ba73e26ebfd3edd6690c21cc7ee00608f294ff22a?s=24&d=retro",
				"email": "cserpentis@gmail.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 739,
				"name": "cserpentis",
				"openid": "cserpentis.id.fedoraproject.org"
			},
			"user_id": 739
		},
		{
			"id": 1826733,
			"karma": 1,
			"text": "Works",
			"timestamp": "2021-01-19 19:30:26",
			"update_id": 272457,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/cd6029d8d81108a2a69c38a2373d2a185c0e86224b8ee4971cd77bb6cdad7a20?s=24&d=retro",
				"email": "walter.pete@yandex.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 491,
				"name": "pwalter",
				"openid": "pwalter.id.fedoraproject.org"
			},
			"user_id": 491
		},
		{
			"id": 1826739,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2021-01-19 19:30:44",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1827887,
			"karma": 1,
			"text": "Works fine",
			"timestamp": "2021-01-20 13:35:50",
			"update_id": 272457,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/f80c96a3994c2479fc4815a146079bf93ade230fe3f3993213d2b8222cafc73d?s=24&d=retro",
				"email": "fzatlouk@redhat.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "qa-tools-sig"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "qa-admin"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "sysadmin-qa"
					},
					{
						"name": "sysadmin"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "advocates"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					}
				],
				"id": 2240,
				"name": "frantisekz",
				"openid": "frantisekz.id.fedoraproject.org"
			},
			"user_id": 2240
		},
		{
			"id": 1827888,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2021-01-20 13:35:50",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1828180,
			"karma": 1,
			"text": "no regressions noted",
			"timestamp": "2021-01-20 22:00:16",
			"update_id": 272457,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/d826994e83ce867281f73d85986dd475938841874b75a83a82cdb184f6af8749?s=24&d=retro",
				"email": "rosset.filipe@gmail.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "l10n"
					},
					{
						"name": "cvsl10n"
					},
					{
						"name": "fedora-br"
					}
				],
				"id": 124,
				"name": "filiperosset",
				"openid": "filiperosset.id.fedoraproject.org"
			},
			"user_id": 124
		},
		{
			"id": 1828495,
			"text": "This update has been pushed to stable.",
			"timestamp": "2021-01-21 01:46:43",
			"update_id": 272457,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2021-01-21 01:44:43",
	"date_stable": "2021-01-21 01:44:43",
	"date_submitted": "2021-01-15 20:08:38",
	"date_testing": "2021-01-16 02:17:33",
	"karma": 4,
	"meets_testing_requirements": true,
	"notes": "Backport fixes for CVE-2020-35653, CVE-2020-35654, CVE-2020-35655.",
	"pushed": true,
	"release": {
		"branch": "f33",
		"candidate_tag": "f33-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f33",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 33",
		"mail_template": "fedora_errata_template",
		"name": "F33",
		"override_tag": "f33-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f33-signing-pending",
		"pending_stable_tag": "f33-updates-pending",
		"pending_testing_tag": "f33-updates-testing-pending",
		"stable_tag": "f33-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f33-updates-testing",
		"version": "33"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "mingw-python-pillow-7.2.0-3.fc33 python-pillow-7.2.0-3.fc33",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2021-a8ddc1ce70",
	"unstable_karma": -3,
	"updateid": "FEDORA-2021-a8ddc1ce70",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/45d3b000186539c7dfca915d2fa0176ec9db448e552c9cf548251f4922e664bd?s=24&d=retro",
		"email": "manisandro@gmail.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 117,
		"name": "smani",
		"openid": "smani.id.fedoraproject.org"
	},
	"version_hash": "949c4509a02eb100674b4e53bac2648809d81f21"
}
