{
	"alias": "FEDORA-2015-13824",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1242715,
			"security": true,
			"title": "CVE-2015-5143 python-django: Django: possible DoS by filling session store [fedora-all]",
			"bugzilla": {
				"bug_id": "1242715",
				"creation_ts": "2015-07-14 03:09:04 +0000",
				"short_desc": "CVE-2015-5143 python-django: Django: possible DoS by filling session store [fedora-all]",
				"delta_ts": "2015-11-19 10:01:09 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1239010",
						"alias": "CVE-2015-5143",
						"creation_ts": "2015-07-03 09:05:10 +0000",
						"short_desc": "CVE-2015-5143 Django: possible DoS by filling session store",
						"delta_ts": "2023-05-12 09:56:30 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1242350",
							"1242714",
							"1242715",
							"1242716",
							"1242717",
							"1243189",
							"1243190",
							"1243191"
						],
						"blocked": [
							{
								"bug_id": "1239014",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2015:1686",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8404421",
								"comment_count": "0",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-03 09:05:10 +0000",
								"thetext": "The following flaw was found in Django:\n\nIn previous versions of Django, the session backends created a new empty record in the session storage anytime ``request.session`` was accessed and there was a session key provided in the request cookies that didn't already have a session record. This could allow an attacker to easily create many new session records simply by sending repeated requests with unknown session keys, potentially filling up the session store or causing other users' session records to be evicted.\n\nThe built-in session backends now create a session record only if the session is actually modified; empty session records are not created. Thus this potential DoS is now only possible if the site chooses to expose a session-modifying view to anonymous users.\n\nAs each built-in session backend was fixed separately (rather than a fix in the core sessions framework), maintainers of third-party session backends should check whether the same vulnerability is present in their backend and correct it if so.\n\nAcknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8414725",
								"comment_count": "1",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:18 +0000",
								"thetext": "Created attachment 1049122\nsession-1.4.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414726",
								"comment_count": "2",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:21 +0000",
								"thetext": "Created attachment 1049123\nsession-1.7.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414727",
								"comment_count": "3",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:24 +0000",
								"thetext": "Created attachment 1049124\nsession-1.8.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414728",
								"comment_count": "4",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:27 +0000",
								"thetext": "Created attachment 1049125\nsession-master.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8422540",
								"comment_count": "5",
								"who": {
									"text": "kseifried",
									"name": "Kurt Seifried"
								},
								"bug_when": "2015-07-09 04:38:12 +0000",
								"thetext": "This is now public: https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "8435558",
								"comment_count": "7",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:09:32 +0000",
								"thetext": "\nCreated Django14 tracking bugs for this issue:\n\nAffects: epel-6 [bug 1242717]"
							},
							{
								"isprivate": "0",
								"commentid": "8435559",
								"comment_count": "8",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:09:36 +0000",
								"thetext": "\nCreated python-django tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1242714]\nAffects: fedora-all [bug 1242715]\nAffects: epel-7 [bug 1242716]"
							},
							{
								"isprivate": "0",
								"commentid": "8472815",
								"comment_count": "10",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-07-23 08:54:34 +0000",
								"thetext": "python-django-1.8.3-1.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "8511484",
								"comment_count": "11",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-08-05 05:31:30 +0000",
								"thetext": "python-django-1.6.11-2.el7 has been pushed to the Fedora EPEL 7 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "8570571",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-08-24 20:16:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 6 for RHEL 7\n\nVia RHSA-2015:1678 https://rhn.redhat.com/errata/RHSA-2015-1678.html"
							},
							{
								"isprivate": "0",
								"commentid": "8571471",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-08-25 05:43:44 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 5 for RHEL 6\n  OpenStack 5 for RHEL 7\n\nVia RHSA-2015:1686 https://rhn.redhat.com/errata/RHSA-2015-1686.html"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8435550",
						"comment_count": "0",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:09:04 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8435553",
						"comment_count": "1",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:09:12 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1239010,1242715\n\n# Description of your update\nnotes=Security fix for CVE-2015-5143\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1239010,1242715"
					},
					{
						"isprivate": "0",
						"commentid": "8436112",
						"comment_count": "2",
						"who": {
							"text": "mrunge",
							"name": "Matthias Runge"
						},
						"bug_when": "2015-07-14 07:25:42 +0000",
						"thetext": "https://admin.fedoraproject.org/updates/FEDORA-2015-11403/python-django-1.8.3-1.fc22"
					},
					{
						"isprivate": "0",
						"commentid": "8559311",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:30:58 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1242715"
					},
					{
						"isprivate": "0",
						"commentid": "8560563",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:23 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774097",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:47:51 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776609",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:19 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794924",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:25 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797005",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:46 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838385",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:25 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1242720,
			"security": true,
			"title": "CVE-2015-5144 python-django: Django: possible header injection due to validators accepting newlines in input [fedora-all]",
			"bugzilla": {
				"bug_id": "1242720",
				"creation_ts": "2015-07-14 03:17:55 +0000",
				"short_desc": "CVE-2015-5144 python-django: Django: possible header injection due to validators accepting newlines in input [fedora-all]",
				"delta_ts": "2015-11-19 10:00:55 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1239011",
						"alias": "CVE-2015-5144",
						"creation_ts": "2015-07-03 09:10:36 +0000",
						"short_desc": "CVE-2015-5144 Django: possible header injection due to validators accepting newlines in input",
						"delta_ts": "2023-05-12 10:17:21 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1242350",
							"1242719",
							"1242720",
							"1242721",
							"1242722"
						],
						"blocked": [
							{
								"bug_id": "1239014",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8404438",
								"comment_count": "0",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-03 09:10:36 +0000",
								"thetext": "The following flaw was found in Django:\n\nSome of Django's built-in validators ('django.core.validators.EmailValidator', most seriously) didn't prohibit newline characters (due to the usage of '$' instead of '\\Z' in the regular expressions). If an application uses values with newlines in HTTP response or email headers, it can allow an attacker to perform header injection attacks. Django itself isn't vulnerable because 'django.http.HttpResponse' and the mail sending utilities in 'django.core.mail' prohibit newlines in HTTP and SMTP headers, respectively.\n\nWhile the validators have been fixed in Django, when creating HTTP responses or email messages in other ways, ensure that those methods prohibit newlines as well. Any already-existing data in your application should be checked whether it contains unexpected newlines.\n\n'django.core.validators.validate_ipv4_address()', 'django.core.validators.validate_slug()', and 'django.core.validators.URLValidator' are also affected, however, as of Django 1.6 the 'GenericIPAddresseField', 'IPAddressField', 'SlugField', and 'URLField' form fields which use these validators all strip the input, so the possibility of newlines entering your data only exists if you are using these validators outside of the form fields\n\nAcknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8414730",
								"comment_count": "1",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:44 +0000",
								"thetext": "Created attachment 1049127\nnewlines-1.4.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414731",
								"comment_count": "2",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:46 +0000",
								"thetext": "Created attachment 1049128\nnewlines-1.7.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414732",
								"comment_count": "3",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:49 +0000",
								"thetext": "Created attachment 1049129\nnewlines-1.8.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414733",
								"comment_count": "4",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:52 +0000",
								"thetext": "Created attachment 1049130\nnewlines-master.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8422541",
								"comment_count": "5",
								"who": {
									"text": "kseifried",
									"name": "Kurt Seifried"
								},
								"bug_when": "2015-07-09 04:38:16 +0000",
								"thetext": "This is now public: https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "8435578",
								"comment_count": "7",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:18:25 +0000",
								"thetext": "\nCreated Django14 tracking bugs for this issue:\n\nAffects: epel-6 [bug 1242722]"
							},
							{
								"isprivate": "0",
								"commentid": "8435579",
								"comment_count": "8",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:18:29 +0000",
								"thetext": "\nCreated python-django tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1242719]\nAffects: fedora-all [bug 1242720]\nAffects: epel-7 [bug 1242721]"
							},
							{
								"isprivate": "0",
								"commentid": "8440127",
								"comment_count": "9",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-15 00:59:46 +0000",
								"thetext": "Statement:\n\nThis issue affects the version of python-django as included with Red Hat Enterprise Linux OpenStack Platform 5 and 6 however there is no known security impact in a supported use-case at this time.\n\nA future update may address this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8472813",
								"comment_count": "10",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-07-23 08:54:30 +0000",
								"thetext": "python-django-1.8.3-1.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8435569",
						"comment_count": "0",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:17:55 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8435570",
						"comment_count": "1",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:18:03 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1239011,1242720\n\n# Description of your update\nnotes=Security fix for CVE-2015-5144\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1239011,1242720"
					},
					{
						"isprivate": "0",
						"commentid": "8436778",
						"comment_count": "2",
						"who": {
							"text": "mrunge",
							"name": "Matthias Runge"
						},
						"bug_when": "2015-07-14 10:04:07 +0000",
						"thetext": "Already submitted https://admin.fedoraproject.org/updates/FEDORA-2015-11403/python-django-1.8.3-1.fc22"
					},
					{
						"isprivate": "0",
						"commentid": "8559310",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:30:56 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1242720"
					},
					{
						"isprivate": "0",
						"commentid": "8560562",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:21 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774095",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:47:44 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776608",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:16 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794923",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:18 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797004",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:43 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838384",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:21 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1242721,
			"security": true,
			"title": "CVE-2015-5144 python-django: Django: possible header injection due to validators accepting newlines in input [epel-7]",
			"bugzilla": {
				"bug_id": "1242721",
				"creation_ts": "2015-07-14 03:18:06 +0000",
				"short_desc": "CVE-2015-5144 python-django: Django: possible header injection due to validators accepting newlines in input [epel-7]",
				"delta_ts": "2015-11-19 10:00:41 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1239011",
						"alias": "CVE-2015-5144",
						"creation_ts": "2015-07-03 09:10:36 +0000",
						"short_desc": "CVE-2015-5144 Django: possible header injection due to validators accepting newlines in input",
						"delta_ts": "2023-05-12 10:17:21 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1242350",
							"1242719",
							"1242720",
							"1242721",
							"1242722"
						],
						"blocked": [
							{
								"bug_id": "1239014",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8404438",
								"comment_count": "0",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-03 09:10:36 +0000",
								"thetext": "The following flaw was found in Django:\n\nSome of Django's built-in validators ('django.core.validators.EmailValidator', most seriously) didn't prohibit newline characters (due to the usage of '$' instead of '\\Z' in the regular expressions). If an application uses values with newlines in HTTP response or email headers, it can allow an attacker to perform header injection attacks. Django itself isn't vulnerable because 'django.http.HttpResponse' and the mail sending utilities in 'django.core.mail' prohibit newlines in HTTP and SMTP headers, respectively.\n\nWhile the validators have been fixed in Django, when creating HTTP responses or email messages in other ways, ensure that those methods prohibit newlines as well. Any already-existing data in your application should be checked whether it contains unexpected newlines.\n\n'django.core.validators.validate_ipv4_address()', 'django.core.validators.validate_slug()', and 'django.core.validators.URLValidator' are also affected, however, as of Django 1.6 the 'GenericIPAddresseField', 'IPAddressField', 'SlugField', and 'URLField' form fields which use these validators all strip the input, so the possibility of newlines entering your data only exists if you are using these validators outside of the form fields\n\nAcknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8414730",
								"comment_count": "1",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:44 +0000",
								"thetext": "Created attachment 1049127\nnewlines-1.4.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414731",
								"comment_count": "2",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:46 +0000",
								"thetext": "Created attachment 1049128\nnewlines-1.7.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414732",
								"comment_count": "3",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:49 +0000",
								"thetext": "Created attachment 1049129\nnewlines-1.8.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8414733",
								"comment_count": "4",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-07-07 07:56:52 +0000",
								"thetext": "Created attachment 1049130\nnewlines-master.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8422541",
								"comment_count": "5",
								"who": {
									"text": "kseifried",
									"name": "Kurt Seifried"
								},
								"bug_when": "2015-07-09 04:38:16 +0000",
								"thetext": "This is now public: https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "8435578",
								"comment_count": "7",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:18:25 +0000",
								"thetext": "\nCreated Django14 tracking bugs for this issue:\n\nAffects: epel-6 [bug 1242722]"
							},
							{
								"isprivate": "0",
								"commentid": "8435579",
								"comment_count": "8",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-14 03:18:29 +0000",
								"thetext": "\nCreated python-django tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1242719]\nAffects: fedora-all [bug 1242720]\nAffects: epel-7 [bug 1242721]"
							},
							{
								"isprivate": "0",
								"commentid": "8440127",
								"comment_count": "9",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-07-15 00:59:46 +0000",
								"thetext": "Statement:\n\nThis issue affects the version of python-django as included with Red Hat Enterprise Linux OpenStack Platform 5 and 6 however there is no known security impact in a supported use-case at this time.\n\nA future update may address this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8472813",
								"comment_count": "10",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-07-23 08:54:30 +0000",
								"thetext": "python-django-1.8.3-1.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8435571",
						"comment_count": "0",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:18:06 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora EPEL.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nepel-7 tracking bug for python-django: see blocks bug list for full details of the security issue(s).\n\nThis bug is never intended to be made public, please put any public notes\nin the blocked bugs.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8435575",
						"comment_count": "1",
						"who": {
							"text": "gmollett",
							"name": "Garth Mollett"
						},
						"bug_when": "2015-07-14 03:18:14 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1239011,1242721\n\n# Description of your update\nnotes=Security fix for CVE-2015-5144\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1239011,1242721"
					},
					{
						"isprivate": "0",
						"commentid": "8436775",
						"comment_count": "2",
						"who": {
							"text": "mrunge",
							"name": "Matthias Runge"
						},
						"bug_when": "2015-07-14 10:03:33 +0000",
						"thetext": "Already submitted https://admin.fedoraproject.org/updates/FEDORA-2015-11403/python-django-1.8.3-1.fc22"
					},
					{
						"isprivate": "0",
						"commentid": "8559309",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:30:54 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1242721"
					},
					{
						"isprivate": "0",
						"commentid": "8560560",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:20 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774094",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:47:35 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776607",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:12 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794922",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:11 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797003",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:40 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838382",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:17 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1253076,
			"title": "Do not install bash completion for python executables",
			"bugzilla": {
				"bug_id": "1253076",
				"creation_ts": "2015-08-12 22:03:56 +0000",
				"short_desc": "Do not install bash completion for python executables",
				"delta_ts": "2015-11-19 10:01:46 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8537468",
						"comment_count": "0",
						"who": {
							"text": "ville.skytta",
							"name": "Ville Skyttä"
						},
						"bug_when": "2015-08-12 22:03:56 +0000",
						"thetext": "Loading the django completion causes django specific completions for\ngeneric python executables to be loaded as well. They're not as\ndesirable as the ones shipped with bash-completion, but them being\nloaded prevents the bash-completion ones from loading.\n\n'git am'able fix attached, let me know if you'd like me to push and\nbuild this for devel."
					},
					{
						"isprivate": "0",
						"commentid": "8537469",
						"comment_count": "1",
						"who": {
							"text": "ville.skytta",
							"name": "Ville Skyttä"
						},
						"bug_when": "2015-08-12 22:03:59 +0000",
						"thetext": "Created attachment 1062283\nDo not install bash completion for python executables"
					},
					{
						"isprivate": "0",
						"commentid": "8539659",
						"comment_count": "2",
						"who": {
							"text": "mrunge",
							"name": "Matthias Runge"
						},
						"bug_when": "2015-08-13 13:34:32 +0000",
						"thetext": "Thank you!\n\nI have the feeling of a 1.8.4 coming in the next few days. Will pull this in then. If you want this fixed earlier, please just go ahead and push it directly."
					},
					{
						"isprivate": "0",
						"commentid": "8542020",
						"comment_count": "3",
						"who": {
							"text": "ville.skytta",
							"name": "Ville Skyttä"
						},
						"bug_when": "2015-08-14 07:19:28 +0000",
						"thetext": "Nah, it's not that urgent. But it's possible that my patch won't apply as is to later versions than 1.8.3, I've submitted some bash completion cleanups upstream which have been merged but I don't know if they're merged also in the 1.8 line. Anyway the essence of the fix is to remove everything from _python_django_completion() onwards from extras/django_bash_completion (this is still required after my upstream cleanups)."
					},
					{
						"isprivate": "0",
						"commentid": "8559314",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:31:03 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1253076"
					},
					{
						"isprivate": "0",
						"commentid": "8560567",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:28 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774101",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:48:14 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776614",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:31 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794929",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:48 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797008",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:57 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838390",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:34 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1254911,
			"security": true,
			"title": "CVE-2015-5963 python-django: Denial-of-service possibility in logout() view by filling session store [fedora-all]",
			"bugzilla": {
				"bug_id": "1254911",
				"creation_ts": "2015-08-19 08:51:19 +0000",
				"short_desc": "CVE-2015-5963 python-django: Denial-of-service possibility in logout() view by filling session store [fedora-all]",
				"delta_ts": "2015-11-19 10:01:35 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1252890",
						"alias": "CVE-2015-5963",
						"creation_ts": "2015-08-12 13:02:37 +0000",
						"short_desc": "CVE-2015-5963 python-django: Denial-of-service possibility in logout() view by filling session store",
						"delta_ts": "2023-05-12 21:09:47 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1254911",
							"1254912",
							"1254913",
							"1254914",
							"1254915",
							"1260506",
							"1260508"
						],
						"blocked": [
							{
								"bug_id": "1252892",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2015:1894",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8535052",
								"comment_count": "0",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:02:37 +0000",
								"thetext": "Following issue was reported in Django:\n\nPreviously, a session could be created when anonymously accessing the\n``django.contrib.auth.views.logout`` view (provided it wasn't decorated\nwith ``django.contrib.auth.decorators.login_required`` as done in the\nadmin). This could allow an attacker to easily create many new session\nrecords by sending repeated requests, potentially filling up the session\nstore or causing other users' session records to be evicted."
							},
							{
								"isprivate": "0",
								"commentid": "8535094",
								"comment_count": "1",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:09:56 +0000",
								"thetext": "Created attachment 1061941\nsession-store-1.4.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8535095",
								"comment_count": "2",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:10:00 +0000",
								"thetext": "Created attachment 1061942\nsession-store-1.7.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8535096",
								"comment_count": "3",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:10:03 +0000",
								"thetext": "Created attachment 1061943\nsession-store-1.8.x.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8535097",
								"comment_count": "4",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:10:06 +0000",
								"thetext": "Created attachment 1061944\nsession-store-master.diff"
							},
							{
								"isprivate": "0",
								"commentid": "8535106",
								"comment_count": "5",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:11:23 +0000",
								"thetext": "Acknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue."
							},
							{
								"isprivate": "0",
								"commentid": "8554893",
								"comment_count": "6",
								"who": {
									"text": "amaris",
									"name": "Adam Mariš"
								},
								"bug_when": "2015-08-19 08:45:37 +0000",
								"thetext": "Public via:\nhttps://www.djangoproject.com/weblog/2015/aug/18/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "8610284",
								"comment_count": "9",
								"who": {
									"text": "gmollett",
									"name": "Garth Mollett"
								},
								"bug_when": "2015-09-07 06:27:29 +0000",
								"thetext": "\nCreated python-django tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1260506]"
							},
							{
								"isprivate": "0",
								"commentid": "8623702",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-09-10 11:44:25 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 5 for RHEL 6\n\nVia RHSA-2015:1766 https://rhn.redhat.com/errata/RHSA-2015-1766.html"
							},
							{
								"isprivate": "0",
								"commentid": "8623873",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-09-10 12:06:03 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 5 for RHEL 7\n\nVia RHSA-2015:1767 https://rhn.redhat.com/errata/RHSA-2015-1767.html"
							},
							{
								"isprivate": "0",
								"commentid": "8702714",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-10-08 12:21:17 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 7 For RHEL 7\n\nVia RHSA-2015:1876 https://access.redhat.com/errata/RHSA-2015:1876"
							},
							{
								"isprivate": "0",
								"commentid": "8723979",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-10-15 12:34:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 6 for RHEL 7\n\nVia RHSA-2015:1894 https://rhn.redhat.com/errata/RHSA-2015-1894.html"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8554916",
						"comment_count": "0",
						"who": {
							"text": "amaris",
							"name": "Adam Mariš"
						},
						"bug_when": "2015-08-19 08:51:19 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8554917",
						"comment_count": "1",
						"who": {
							"text": "amaris",
							"name": "Adam Mariš"
						},
						"bug_when": "2015-08-19 08:51:27 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1252890,1254911\n\n# Description of your update\nnotes=Security fix for CVE-2015-5963\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1252890,1254911"
					},
					{
						"isprivate": "0",
						"commentid": "8559313",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:31:01 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1254911"
					},
					{
						"isprivate": "0",
						"commentid": "8560566",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:26 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774100",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:48:06 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776612",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:27 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794927",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:40 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797007",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:53 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838389",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:31 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1254921,
			"security": true,
			"title": "CVE-2015-5964 python-django: Denial-of-service possibility in logout() view by filling session store [fedora-all]",
			"bugzilla": {
				"bug_id": "1254921",
				"creation_ts": "2015-08-19 08:54:00 +0000",
				"short_desc": "CVE-2015-5964 python-django: Denial-of-service possibility in logout() view by filling session store [fedora-all]",
				"delta_ts": "2015-11-19 10:01:22 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1252891",
						"alias": "CVE-2015-5964",
						"creation_ts": "2015-08-12 13:06:00 +0000",
						"short_desc": "CVE-2015-5964 python-django: Denial-of-service possibility in logout() view by filling session store",
						"delta_ts": "2023-05-12 14:07:52 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1254912",
							"1254913",
							"1254914",
							"1254921",
							"1257809",
							"1257810"
						],
						"blocked": [
							{
								"bug_id": "1252892",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2015:1894",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8535075",
								"comment_count": "0",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:06:00 +0000",
								"thetext": "Following issue was reported in Django:\n\nIn CVE-2015-5963, the ``django.contrib.sessions.middleware.SessionMiddleware`` has been modified to no longer create empty session records.\nAdditionally, on the 1.4 and 1.7 series only, the ``contrib.sessions.backends.base.SessionBase.flush()`` and ``cache_db.SessionStore.flush()`` methods have been modified to avoid creating a new empty session. \nThis modification of 1.4 and 1.7 series got CVE-2015-5964.\n\nPreviously, a session could be created when anonymously accessing the ``django.contrib.auth.views.logout`` view (provided it wasn't decorated with ``django.contrib.auth.decorators.login_required`` as done in the admin). This could allow an attacker to easily create many new session records by sending repeated requests, potentially filling up the session store or causing other users' session records to be evicted."
							},
							{
								"isprivate": "0",
								"commentid": "8535107",
								"comment_count": "1",
								"who": {
									"text": "vkaigoro",
									"name": "Vasyl Kaigorodov"
								},
								"bug_when": "2015-08-12 13:11:29 +0000",
								"thetext": "Acknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue. Upstream acknowledges Lin Hua Cheng as the original reporter."
							},
							{
								"isprivate": "0",
								"commentid": "8554896",
								"comment_count": "2",
								"who": {
									"text": "amaris",
									"name": "Adam Mariš"
								},
								"bug_when": "2015-08-19 08:46:49 +0000",
								"thetext": "Public via:\nhttps://www.djangoproject.com/weblog/2015/aug/18/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "8554937",
								"comment_count": "3",
								"who": {
									"text": "amaris",
									"name": "Adam Mariš"
								},
								"bug_when": "2015-08-19 08:54:07 +0000",
								"thetext": "\nCreated python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1254921]"
							},
							{
								"isprivate": "0",
								"commentid": "8623703",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-09-10 11:44:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 5 for RHEL 6\n\nVia RHSA-2015:1766 https://rhn.redhat.com/errata/RHSA-2015-1766.html"
							},
							{
								"isprivate": "0",
								"commentid": "8623875",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-09-10 12:06:06 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 5 for RHEL 7\n\nVia RHSA-2015:1767 https://rhn.redhat.com/errata/RHSA-2015-1767.html"
							},
							{
								"isprivate": "0",
								"commentid": "8723980",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2015-10-15 12:35:01 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  OpenStack 6 for RHEL 7\n\nVia RHSA-2015:1894 https://rhn.redhat.com/errata/RHSA-2015-1894.html"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8554935",
						"comment_count": "0",
						"who": {
							"text": "amaris",
							"name": "Adam Mariš"
						},
						"bug_when": "2015-08-19 08:54:00 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8554936",
						"comment_count": "1",
						"who": {
							"text": "amaris",
							"name": "Adam Mariš"
						},
						"bug_when": "2015-08-19 08:54:05 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1252891,1254921\n\n# Description of your update\nnotes=Security fix for CVE-2015-5964\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1252891,1254921"
					},
					{
						"isprivate": "0",
						"commentid": "8559312",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 12:31:00 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been submitted as an update to Fedora 23. https://bugzilla.redhat.com/show_bug.cgi?id=1254921"
					},
					{
						"isprivate": "0",
						"commentid": "8560565",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-08-20 19:21:24 +0000",
						"thetext": "python-django-1.8.4-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\\nIf you want to test the update, you can install it with \\n su -c 'yum --enablerepo=updates-testing update python-django'. You can provide feedback for this update here: https://bodhi.fedoraproject.org/F23/FEDORA-2015-13824"
					},
					{
						"isprivate": "0",
						"commentid": "8774099",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-02 09:47:59 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8776610",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-03 00:24:23 +0000",
						"thetext": "python-django-1.8.5-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450"
					},
					{
						"isprivate": "0",
						"commentid": "8794926",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-05 13:46:33 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been submitted as an update to Fedora 23. https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8797006",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-06 02:34:50 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 testing repository. If problems still persist, please make note of it in this bug report.\nIf you want to test the update, you can install it with\n$ su -c 'dnf --enablerepo=updates-testing update python-django'\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2015-1dd5bc998f"
					},
					{
						"isprivate": "0",
						"commentid": "8838387",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-11-19 10:00:28 +0000",
						"thetext": "python-django-1.8.6-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"nvr": "python-django-1.8.4-1.fc23",
			"release_id": 11,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-django",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "noarch"
					},
					{
						"name": "python-django",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "noarch"
					},
					{
						"name": "python-django-doc",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "noarch"
					},
					{
						"name": "python3-django-doc",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "noarch"
					},
					{
						"name": "python-django-bash-completion",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-django",
						"version": "1.8.4",
						"release": "1.fc23",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 313099,
			"text": "This update has been submitted for testing by mrunge. ",
			"timestamp": "2015-08-20 12:31:06",
			"update_id": 37071,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 313191,
			"text": "This update has been pushed to testing",
			"timestamp": "2015-08-20 19:22:19",
			"update_id": 37071,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 328707,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2015-09-25 07:14:04",
			"update_id": 37071,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/8bede7eae5a18bbb10b7da207b0d75614581b913621b9737da28fe43fedfad7c?s=24&d=retro",
				"email": "akurtako@redhat.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "eclipse-sig"
					}
				],
				"id": 214,
				"name": "akurtakov",
				"openid": "akurtakov.id.fedoraproject.org"
			},
			"user_id": 214
		},
		{
			"id": 335357,
			"text": "This update has reached 49 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2015-10-08 20:58:36",
			"update_id": 37071,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 339303,
			"karma": 1,
			"text": "WFM",
			"timestamp": "2015-10-15 23:01:06",
			"update_id": 37071,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/cd8c7a6c7915ec305684dc7062ae860ea8d43040037d3bea3d20e03d2621566a?s=24&d=retro",
				"email": "williamjmorenor@gmail.com",
				"groups": [
					{
						"name": "packager"
					}
				],
				"id": 216,
				"name": "williamjmorenor",
				"openid": "williamjmorenor.id.fedoraproject.org"
			},
			"user_id": 216
		},
		{
			"id": 346576,
			"text": "This update has been obsoleted by [python-django-1.8.5-1.fc23](https://bodhi.fedoraproject.org/updates/FEDORA-2015-66d4519450).",
			"timestamp": "2015-11-02 09:47:32",
			"update_id": 37071,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2015-08-20 19:22:19",
	"date_submitted": "2015-08-20 12:31:06",
	"date_testing": "2015-08-20 19:22:19",
	"karma": 2,
	"meets_testing_requirements": true,
	"notes": "\n\npython-django-1.8.4-1.fc23\n\n- Do not install bash completion for python executables\n  (Ville Skyttä, rhbz#1253076)\n- CVE-2015-5963 Denial-of-service possibility in logout() view by filling\n  session store (rhbz#1254911)\n- CVE-2015-5964 Denial-of-service possibility in logout() view by filling\n  session store (rhbz#1252891)\n",
	"release": {
		"branch": "f23",
		"candidate_tag": "f23-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f23",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 23",
		"mail_template": "fedora_errata_template",
		"name": "F23",
		"override_tag": "f23-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f23-signing-pending",
		"pending_stable_tag": "f23-updates-pending",
		"pending_testing_tag": "f23-updates-testing-pending",
		"stable_tag": "f23-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f23-updates-testing",
		"version": "23"
	},
	"require_bugs": true,
	"require_testcases": true,
	"requirements": "",
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "obsolete",
	"suggest": "unspecified",
	"title": "python-django-1.8.4-1.fc23",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2015-13824",
	"unstable_karma": -3,
	"updateid": "FEDORA-2015-13824",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/c626775cb5584b1a49ea4a5cabb248e54e49c09185ebbf4fbce72265255956f0?s=24&d=retro",
		"email": "mrunge@redhat.com",
		"groups": [
			{
				"name": "proventesters"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "centosproject-email-aliases"
			},
			{
				"name": "gitovirt"
			},
			{
				"name": "sig-cloud"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "gitnodejs-packaging"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "sig-extras"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "sig-opstools"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sig-messaging"
			},
			{
				"name": "openstack-sig"
			}
		],
		"id": 189,
		"name": "mrunge",
		"openid": "mrunge.id.fedoraproject.org"
	},
	"version_hash": "771e781bbd1069b3c1a70e9208cc5e0780a2be4f"
}
