{
	"alias": "FEDORA-2024-6140989aaf",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2307370,
			"parent": true,
			"security": true,
			"title": "CVE-2024-8088 python: cpython: From NVD collector",
			"bugzilla": {
				"bug_id": "2307370",
				"alias": "CVE-2024-8088",
				"creation_ts": "2024-08-22 19:20:34 +0000",
				"short_desc": "CVE-2024-8088 python: cpython: From NVD collector",
				"delta_ts": "2024-08-27 15:52:09 +0000",
				"bug_status": "NEW",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2307457",
					"2307459",
					"2307462",
					"2307465",
					"2307458",
					"2307460",
					"2307461",
					"2307463",
					"2307464",
					"2307466"
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18159903",
						"comment_count": "0",
						"who": {
							"text": "bzimport",
							"name": "OSIDB Bzimport"
						},
						"bug_when": "2024-08-22 19:20:34 +0000",
						"thetext": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.ZipFile\" like \"namelist()\", \"iterdir()\", \"extractall()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected."
					}
				]
			}
		},
		{
			"bug_id": 2307466,
			"security": true,
			"title": "CVE-2024-8088 python3.9: From NVD collector [fedora-all]",
			"bugzilla": {
				"bug_id": "2307466",
				"creation_ts": "2024-08-22 23:00:03 +0000",
				"short_desc": "CVE-2024-8088 python3.9: From NVD collector [fedora-all]",
				"delta_ts": "2024-08-28 11:01:33 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2307370",
						"alias": "CVE-2024-8088",
						"creation_ts": "2024-08-22 19:20:34 +0000",
						"short_desc": "CVE-2024-8088 python: cpython: From NVD collector",
						"delta_ts": "2024-08-27 15:52:09 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2307457",
							"2307459",
							"2307462",
							"2307465",
							"2307458",
							"2307460",
							"2307461",
							"2307463",
							"2307464",
							"2307466"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18159903",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2024-08-22 19:20:34 +0000",
								"thetext": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.ZipFile\" like \"namelist()\", \"iterdir()\", \"extractall()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18160115",
						"comment_count": "0",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2024-08-22 23:00:03 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2307370\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18165046",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 10:51:39 +0000",
						"thetext": "FEDORA-2024-0cf8baac55 (python3.9-3.9.19-6.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-0cf8baac55"
					},
					{
						"isprivate": "0",
						"commentid": "18165052",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 10:56:01 +0000",
						"thetext": "FEDORA-2024-0cf8baac55 (python3.9-3.9.19-6.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18165054",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:27 +0000",
						"thetext": "FEDORA-2024-dc7f1d57e4 (python3.9-3.9.19-6.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-dc7f1d57e4"
					},
					{
						"isprivate": "0",
						"commentid": "18165055",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:30 +0000",
						"thetext": "FEDORA-2024-6140989aaf (python3.9-3.9.19-6.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-6140989aaf"
					},
					{
						"isprivate": "0",
						"commentid": "18165056",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:33 +0000",
						"thetext": "FEDORA-2024-9a940ffe4c (python3.9-3.9.19-6.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-9a940ffe4c"
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.9-3.9.19-6.fc41",
			"release_id": 80,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3695596,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2024-08-28 11:01:24",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3695597,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-08-28 11:01:24",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_submitted": "2024-08-28 11:01:24",
	"notes": "Security fix for CVE-2024-8088",
	"release": {
		"branch": "f41",
		"candidate_tag": "f41-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f41",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 41",
		"mail_template": "fedora_errata_template",
		"name": "F41",
		"override_tag": "f41-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f41-signing-pending",
		"pending_stable_tag": "f41-updates-pending",
		"pending_testing_tag": "f41-updates-testing-pending",
		"stable_tag": "f41",
		"state": "frozen",
		"testing_repository": "updates-testing",
		"testing_tag": "f41-updates-testing",
		"version": "41"
	},
	"request": "testing",
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 3,
	"stable_karma": 1,
	"status": "pending",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.9-3.9.19-6.fc41",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2024-6140989aaf",
	"unstable_karma": -1,
	"updateid": "FEDORA-2024-6140989aaf",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "d187b6dcc98f203d61d807020e58911c6cc46141"
}
