{
	"alias": "FEDORA-EPEL-2013-11879",
	"bugs": [
		{
			"bug_id": 916690,
			"parent": true,
			"security": true,
			"title": "CVE-2013-4251 scipy: weave /tmp and current directory issues",
			"bugzilla": {
				"bug_id": "916690",
				"alias": "CVE-2013-4251",
				"creation_ts": "2013-02-28 16:45:42 +0000",
				"short_desc": "CVE-2013-4251 scipy: weave /tmp and current directory issues",
				"delta_ts": "2023-05-13 00:32:18 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"997579",
					"1018351",
					"1018353"
				],
				"blocked": [
					{
						"bug_id": "916691",
						"error": "NotPermitted"
					},
					{
						"bug_id": "1007017",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "5558280",
						"comment_count": "0",
						"who": {
							"text": "fweimer",
							"name": "Florian Weimer"
						},
						"bug_when": "2013-02-28 16:45:42 +0000",
						"thetext": "I think it would be a good idea to remove the fallback to the current directory in the weave code (which happens if ~/.python26_compiled is not a writable directory).  This looks unsafe when the current directory is not trusted."
					},
					{
						"isprivate": "0",
						"commentid": "5561019",
						"comment_count": "2",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-03-01 12:19:45 +0000",
						"thetext": "I'm sorry, but I'm a bit puzzled by this one. You are talking about build_dir, right? Current routine sets it to current dir:\n\n    build_dir = configure_build_dir(module_dir)\n\nwhich is a bug IMO, because argument 'build_dir' is completely ignored -- I'm gonna report it to upstream. But back to the routine that is trying to set build_dir if it's not specified:\n\n 1. if build_dir is not writable, it is set to current dir\n 2. if current dir is not writable either, '/tmp' is used then\n\nSo you don't like 1., right?"
					},
					{
						"isprivate": "0",
						"commentid": "5561064",
						"comment_count": "3",
						"who": {
							"text": "fweimer",
							"name": "Florian Weimer"
						},
						"bug_when": "2013-03-01 12:49:21 +0000",
						"thetext": "(In reply to comment #2)\n> I'm sorry, but I'm a bit puzzled by this one. You are talking about\n> build_dir, right? Current routine sets it to current dir:\n> \n>     build_dir = configure_build_dir(module_dir)\n> \n> which is a bug IMO, because argument 'build_dir' is completely ignored --\n> I'm gonna report it to upstream. But back to the routine that is trying to\n> set build_dir if it's not specified:\n> \n>  1. if build_dir is not writable, it is set to current dir\n>  2. if current dir is not writable either, '/tmp' is used then\n> \n> So you don't like 1., right?\n\nI don't like 1.  2 doesn't look great, either, unless a private subdirectory of /tmp is created exactly for this purposes.  I haven't tested the second scenario."
					},
					{
						"isprivate": "0",
						"commentid": "5561193",
						"comment_count": "4",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-03-01 13:45:44 +0000",
						"thetext": "Okay, I'll fix them both. It is really easy. Brew builds will be done by Monday (March 4th) for sure (if you want to test it)."
					},
					{
						"isprivate": "0",
						"commentid": "5566739",
						"comment_count": "5",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-03-04 14:57:29 +0000",
						"thetext": "Here [1] is a build of scipy with these changes:\n- Use argument build_dir if it is specified, fallback to module path\n- Do not fall for current dir if build_dir is not specified\n- Create temp dir (mkdtemp) when building extension if build_dir is not specified (last fallback)\n\nTests that test this fall now (I haven't updated them yet).\n\nIs this behaviour okay or should I change it somehow?\n\n[1] https://brewweb.devel.redhat.com/taskinfo?taskID=5461629"
					},
					{
						"isprivate": "0",
						"commentid": "5570444",
						"comment_count": "6",
						"who": {
							"text": "fweimer",
							"name": "Florian Weimer"
						},
						"bug_when": "2013-03-05 16:40:27 +0000",
						"thetext": "(In reply to comment #5)\n> Here [1] is a build of scipy with these changes:\n> - Use argument build_dir if it is specified, fallback to module path\n> - Do not fall for current dir if build_dir is not specified\n> - Create temp dir (mkdtemp) when building extension if build_dir is not\n> specified (last fallback)\n\nThis is good, but I think you have to clean up the directory created with mkdtemp, otherwise it will stick around."
					},
					{
						"isprivate": "0",
						"commentid": "5570537",
						"comment_count": "7",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-03-05 17:14:05 +0000",
						"thetext": "But what will be the purpose of the execution if the actual result will be deleted? (I think in that case there should be a way to inform the user where is his extension stored)"
					},
					{
						"isprivate": "0",
						"commentid": "5570546",
						"comment_count": "8",
						"who": {
							"text": "fweimer",
							"name": "Florian Weimer"
						},
						"bug_when": "2013-03-05 17:18:05 +0000",
						"thetext": "(In reply to comment #7)\n> But what will be the purpose of the execution if the actual result will be\n> deleted? (I think in that case there should be a way to inform the user\n> where is his extension stored)\n\nIf you use os.mkdtemp(), you won't be able to find the directory again, so the data cached there will not be reused.  Perhaps it's best to just error out in this case, simply requiring a writable home directory?  That part is hard to tell for me."
					},
					{
						"isprivate": "0",
						"commentid": "5608215",
						"comment_count": "9",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-03-18 15:26:14 +0000",
						"thetext": "I found out that it could be traceable, because if 'build_dir' is not on sys.path, build_extension adds it there. But it's not very nice, since /tmp is tmpfs, thus not permanent storage.\n\nAlso, answer to comment ( https://bugzilla.redhat.com/show_bug.cgi?id=916695#c8 ) from #916695 would help me in here."
					},
					{
						"isprivate": "0",
						"commentid": "6211554",
						"comment_count": "10",
						"who": {
							"text": "fweimer",
							"name": "Florian Weimer"
						},
						"bug_when": "2013-08-14 14:07:59 +0000",
						"thetext": "Tomas, I answered your question on bug 916695.\n\nDuring testing, I noticed this:\n\n[fweimer@localhost ~]$ ls -lhd /tmp/fweimer\ndrwxr-xr-x. 2 nobody nobody 4.0K Aug 14 09:45 /tmp/fweimer\n[fweimer@localhost ~]$ python\nPython 2.7.5 (default, Aug  5 2013, 02:37:08) \n[GCC 4.8.1 20130717 (Red Hat 4.8.1-5)] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import random, scipy.weave; a=1; scipy.weave.inline('printf(\"%%d\\\\n\",a,%f);' % random.random(),['a'])\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/inline_tools.py\", line 357, in inline\n    **kw)\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/inline_tools.py\", line 484, in compile_function\n    verbose=verbose, **kw)\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/ext_tools.py\", line 365, in compile\n    temp = catalog.intermediate_dir()\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/catalog.py\", line 220, in intermediate_dir\n    os.makedirs(path, mode=0o700)\n  File \"/usr/lib64/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/tmp/fweimer/python27_intermediate'\n>>> \n\nSo this is at least a denial of service.  With laxer permissions, weave uses that directory:\n\n[fweimer@localhost ~]$ ls -lhd /tmp/fweimer\ndrwxrwxrwx. 2 nobody nobody 4.0K Aug 14 09:45 /tmp/fweimer\n[fweimer@localhost ~]$ python\nPython 2.7.5 (default, Aug  5 2013, 02:37:08) \n[GCC 4.8.1 20130717 (Red Hat 4.8.1-5)] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import random, scipy.weave; a=1; scipy.weave.inline('printf(\"%%d\\\\n\",a,%f);' % random.random(),['a'])\ncreating /tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc\nIn file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,\n                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,\n                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:15,\n                 from /home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp:22:\n/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning \"Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]\n #warning \"Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\"\n  ^\n/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp: In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:\n/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp:673:29: warning: too many arguments for format [-Wformat-extra-args]\n     printf(\"%d\\n\",a,0.946759);        /*I would like to fill in changed locals and globals here...*/   \n                             ^\n1\n>>> \n[fweimer@localhost ~]$ find /tmp/fweimer -type f \n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/home/fweimer/.python27_compiled/sc_777337fffcbda13be8e1c5a8c5ce3aef0.o\n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.o\n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/usr/lib64/python2.7/site-packages/scipy/weave/scxx/weave_imp.o\n\nThe files are actually used as linker input files, so this allows local users to trick each other into executing code.\n\nThis is much more severe, not merely hardening, and probably warrants CVE assignment.  This should be fixed in cooperation with upstream, perhaps with a (short) embargo period.  Please do not commit a fix to a public repository or file a public bug report."
					},
					{
						"isprivate": "0",
						"commentid": "6215952",
						"comment_count": "11",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-08-15 16:16:43 +0000",
						"thetext": "To summarize, scipy.weave will use /tmp/[username] as persistent storage (cache), but it does not check whether or not this directory already exists, does not check whether it is a directory or a symlink, and also does not verify permissions or ownership, which could allow someone to place code in this directory that would be executed as the user running scipy.weave.\n\nIdeally, it should be creating the directory if it doesn't exist with appropriate ownership/permissions, and if the directory already exists (and permissions/ownership is inappropriate), create a new directory and use it instead (in a similar way that Pulseaudio does, perhaps /var/tmp/scipy-[variable])."
					},
					{
						"isprivate": "0",
						"commentid": "6215962",
						"comment_count": "12",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-08-15 16:19:36 +0000",
						"thetext": "Acknowledgements:\n\nThis issue was found by Florian Weimer of the Red Hat Product Security Team."
					},
					{
						"isprivate": "0",
						"commentid": "6228703",
						"comment_count": "14",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-20 13:33:35 +0000",
						"thetext": "(In reply to Vincent Danen from comment #11)\n> To summarize, scipy.weave will use /tmp/[username] as persistent storage\n> (cache), but it does not check whether or not this directory already exists\n\nI would like to correct this a little bit. scipy does check whether the dir exists. This is the function that is responsible for creating the directory:\n\n\ndef intermediate_dir():\n    \"\"\" Location in temp dir for storing .cpp and .o  files during\n        builds.\n    \"\"\"\n    python_name = \"python%d%d_intermediate\" % tuple(sys.version_info[:2])\n    path = os.path.join(tempfile.gettempdir(),\"%s\" % whoami(),python_name)\n    if not os.path.exists(path):\n        os.makedirs(path, mode=0o700)\n    return path\n\n\nAs you can see, it checks if the directory already exists.\n\nCurrently I'm writing tests for this CVE. When I finish I'll attach them here so it will be pretty easy to fix this. Is this okay?"
					},
					{
						"isprivate": "0",
						"commentid": "6233204",
						"comment_count": "15",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-21 13:45:54 +0000",
						"thetext": "Created attachment 788882\nUnit tests for this CVE\n\nI've mocked unit tests for this CVE. These are definitely not final. Especially a part, where the tests play with actual temporary directory (/tmp/<name>/python27...) and not with one created only for purpose of the tests, is really bad. They were created to fit current code only. Also I wanted to know if the tests check correct values.\n\nOnce there will be code which fixes this bug, the tests will be easy to adapt."
					},
					{
						"isprivate": "0",
						"commentid": "6239863",
						"comment_count": "16",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-23 10:17:04 +0000",
						"thetext": "Created attachment 789545\nPatch"
					},
					{
						"isprivate": "0",
						"commentid": "6240190",
						"comment_count": "17",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-23 12:35:39 +0000",
						"thetext": "Created attachment 789580\ncatalog reproducer\n\nWhile writing the patch I noticed that same thing occurs for persistent cache/store of compiled functions -- catalog. We agreed with Florian that it should be fixed too, so I'm going to \"respin\" the patch."
					},
					{
						"isprivate": "0",
						"commentid": "6247481",
						"comment_count": "18",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-08-27 01:08:25 +0000",
						"thetext": "Thanks, Tomas.  Have we reported this upstream or gotten any feedback on it from them yet?"
					},
					{
						"isprivate": "0",
						"commentid": "6248717",
						"comment_count": "19",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-27 09:45:05 +0000",
						"thetext": "As I wrote in the e-mail to your mailing list, I haven't got response yet. This may be because there was an event taking place recently -- EuroSciPy. So I'm assuming they were pretty busy and that's why they didn't respond."
					},
					{
						"isprivate": "0",
						"commentid": "6250094",
						"comment_count": "20",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-08-27 14:50:53 +0000",
						"thetext": "Created attachment 791020\nPatch 2\n\nThis patch fixes original issue and similar problem with function 'default_dir'. I will post a build of scipy here tomorrow."
					},
					{
						"isprivate": "0",
						"commentid": "6298020",
						"comment_count": "22",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-09-11 18:11:44 +0000",
						"thetext": "Any response from upstream yet?"
					},
					{
						"isprivate": "0",
						"commentid": "6299440",
						"comment_count": "23",
						"who": {
							"text": "ttomecek",
							"name": "Tomas Tomecek"
						},
						"bug_when": "2013-09-12 05:56:44 +0000",
						"thetext": "(In reply to Vincent Danen from comment #22)\n> Any response from upstream yet?\n\nUnfortunately no. I'm assuming they have problems with verification if the patch works. Especially on Windows environment. I may write them this week if no response come til Friday."
					},
					{
						"isprivate": "0",
						"commentid": "6353577",
						"comment_count": "24",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-09-27 17:47:26 +0000",
						"thetext": "Created attachment 804078\npatch from upstream"
					},
					{
						"isprivate": "0",
						"commentid": "6376332",
						"comment_count": "25",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-03 21:39:40 +0000",
						"thetext": "The CRD date for this is October 10th."
					},
					{
						"isprivate": "0",
						"commentid": "6409691",
						"comment_count": "26",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-11 18:17:28 +0000",
						"thetext": "SciPy 0.12.1 has been released to fix this issue:\n\nhttp://sourceforge.net/projects/scipy/files/scipy/0.12.1/\nhttps://github.com/scipy/scipy/commit/bd296e0336420b840fcd2faabb97084fd252a973"
					},
					{
						"isprivate": "0",
						"commentid": "6409718",
						"comment_count": "27",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-11 18:25:35 +0000",
						"thetext": "\nCreated scipy tracking bugs for this issue:\n\nAffects: fedora-all [bug 1018351]\nAffects: epel-5 [bug 1018353]"
					},
					{
						"isprivate": "0",
						"commentid": "6423554",
						"comment_count": "28",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-15 22:37:28 +0000",
						"thetext": "This is also correct in SciPy 0.13.0rc1:\n\nsourceforge.net/projects/scipy/files/scipy/0.13.0rc1/"
					},
					{
						"isprivate": "0",
						"commentid": "6460080",
						"comment_count": "29",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-10-27 05:37:17 +0000",
						"thetext": "scipy-0.12.1-1.fc18 has been pushed to the Fedora 18 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "6460092",
						"comment_count": "30",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-10-27 05:39:16 +0000",
						"thetext": "scipy-0.12.1-1.fc19 has been pushed to the Fedora 19 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "6480458",
						"comment_count": "31",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-11-01 21:05:47 +0000",
						"thetext": "scipy-0.6.0-7.el5 has been pushed to the Fedora EPEL 5 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "6504807",
						"comment_count": "32",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-11-10 06:55:56 +0000",
						"thetext": "scipy-0.12.1-1.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1018353,
			"security": true,
			"title": "CVE-2013-4251 scipy: weave /tmp and current directory issues [epel-5]",
			"bugzilla": {
				"bug_id": "1018353",
				"creation_ts": "2013-10-11 18:25:21 +0000",
				"short_desc": "CVE-2013-4251 scipy: weave /tmp and current directory issues [epel-5]",
				"delta_ts": "2013-11-01 21:05:29 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "916690",
						"alias": "CVE-2013-4251",
						"creation_ts": "2013-02-28 16:45:42 +0000",
						"short_desc": "CVE-2013-4251 scipy: weave /tmp and current directory issues",
						"delta_ts": "2023-05-13 00:32:18 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"997579",
							"1018351",
							"1018353"
						],
						"blocked": [
							{
								"bug_id": "916691",
								"error": "NotPermitted"
							},
							{
								"bug_id": "1007017",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "5558280",
								"comment_count": "0",
								"who": {
									"text": "fweimer",
									"name": "Florian Weimer"
								},
								"bug_when": "2013-02-28 16:45:42 +0000",
								"thetext": "I think it would be a good idea to remove the fallback to the current directory in the weave code (which happens if ~/.python26_compiled is not a writable directory).  This looks unsafe when the current directory is not trusted."
							},
							{
								"isprivate": "0",
								"commentid": "5561019",
								"comment_count": "2",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-03-01 12:19:45 +0000",
								"thetext": "I'm sorry, but I'm a bit puzzled by this one. You are talking about build_dir, right? Current routine sets it to current dir:\n\n    build_dir = configure_build_dir(module_dir)\n\nwhich is a bug IMO, because argument 'build_dir' is completely ignored -- I'm gonna report it to upstream. But back to the routine that is trying to set build_dir if it's not specified:\n\n 1. if build_dir is not writable, it is set to current dir\n 2. if current dir is not writable either, '/tmp' is used then\n\nSo you don't like 1., right?"
							},
							{
								"isprivate": "0",
								"commentid": "5561064",
								"comment_count": "3",
								"who": {
									"text": "fweimer",
									"name": "Florian Weimer"
								},
								"bug_when": "2013-03-01 12:49:21 +0000",
								"thetext": "(In reply to comment #2)\n> I'm sorry, but I'm a bit puzzled by this one. You are talking about\n> build_dir, right? Current routine sets it to current dir:\n> \n>     build_dir = configure_build_dir(module_dir)\n> \n> which is a bug IMO, because argument 'build_dir' is completely ignored --\n> I'm gonna report it to upstream. But back to the routine that is trying to\n> set build_dir if it's not specified:\n> \n>  1. if build_dir is not writable, it is set to current dir\n>  2. if current dir is not writable either, '/tmp' is used then\n> \n> So you don't like 1., right?\n\nI don't like 1.  2 doesn't look great, either, unless a private subdirectory of /tmp is created exactly for this purposes.  I haven't tested the second scenario."
							},
							{
								"isprivate": "0",
								"commentid": "5561193",
								"comment_count": "4",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-03-01 13:45:44 +0000",
								"thetext": "Okay, I'll fix them both. It is really easy. Brew builds will be done by Monday (March 4th) for sure (if you want to test it)."
							},
							{
								"isprivate": "0",
								"commentid": "5566739",
								"comment_count": "5",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-03-04 14:57:29 +0000",
								"thetext": "Here [1] is a build of scipy with these changes:\n- Use argument build_dir if it is specified, fallback to module path\n- Do not fall for current dir if build_dir is not specified\n- Create temp dir (mkdtemp) when building extension if build_dir is not specified (last fallback)\n\nTests that test this fall now (I haven't updated them yet).\n\nIs this behaviour okay or should I change it somehow?\n\n[1] https://brewweb.devel.redhat.com/taskinfo?taskID=5461629"
							},
							{
								"isprivate": "0",
								"commentid": "5570444",
								"comment_count": "6",
								"who": {
									"text": "fweimer",
									"name": "Florian Weimer"
								},
								"bug_when": "2013-03-05 16:40:27 +0000",
								"thetext": "(In reply to comment #5)\n> Here [1] is a build of scipy with these changes:\n> - Use argument build_dir if it is specified, fallback to module path\n> - Do not fall for current dir if build_dir is not specified\n> - Create temp dir (mkdtemp) when building extension if build_dir is not\n> specified (last fallback)\n\nThis is good, but I think you have to clean up the directory created with mkdtemp, otherwise it will stick around."
							},
							{
								"isprivate": "0",
								"commentid": "5570537",
								"comment_count": "7",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-03-05 17:14:05 +0000",
								"thetext": "But what will be the purpose of the execution if the actual result will be deleted? (I think in that case there should be a way to inform the user where is his extension stored)"
							},
							{
								"isprivate": "0",
								"commentid": "5570546",
								"comment_count": "8",
								"who": {
									"text": "fweimer",
									"name": "Florian Weimer"
								},
								"bug_when": "2013-03-05 17:18:05 +0000",
								"thetext": "(In reply to comment #7)\n> But what will be the purpose of the execution if the actual result will be\n> deleted? (I think in that case there should be a way to inform the user\n> where is his extension stored)\n\nIf you use os.mkdtemp(), you won't be able to find the directory again, so the data cached there will not be reused.  Perhaps it's best to just error out in this case, simply requiring a writable home directory?  That part is hard to tell for me."
							},
							{
								"isprivate": "0",
								"commentid": "5608215",
								"comment_count": "9",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-03-18 15:26:14 +0000",
								"thetext": "I found out that it could be traceable, because if 'build_dir' is not on sys.path, build_extension adds it there. But it's not very nice, since /tmp is tmpfs, thus not permanent storage.\n\nAlso, answer to comment ( https://bugzilla.redhat.com/show_bug.cgi?id=916695#c8 ) from #916695 would help me in here."
							},
							{
								"isprivate": "0",
								"commentid": "6211554",
								"comment_count": "10",
								"who": {
									"text": "fweimer",
									"name": "Florian Weimer"
								},
								"bug_when": "2013-08-14 14:07:59 +0000",
								"thetext": "Tomas, I answered your question on bug 916695.\n\nDuring testing, I noticed this:\n\n[fweimer@localhost ~]$ ls -lhd /tmp/fweimer\ndrwxr-xr-x. 2 nobody nobody 4.0K Aug 14 09:45 /tmp/fweimer\n[fweimer@localhost ~]$ python\nPython 2.7.5 (default, Aug  5 2013, 02:37:08) \n[GCC 4.8.1 20130717 (Red Hat 4.8.1-5)] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import random, scipy.weave; a=1; scipy.weave.inline('printf(\"%%d\\\\n\",a,%f);' % random.random(),['a'])\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/inline_tools.py\", line 357, in inline\n    **kw)\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/inline_tools.py\", line 484, in compile_function\n    verbose=verbose, **kw)\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/ext_tools.py\", line 365, in compile\n    temp = catalog.intermediate_dir()\n  File \"/usr/lib64/python2.7/site-packages/scipy/weave/catalog.py\", line 220, in intermediate_dir\n    os.makedirs(path, mode=0o700)\n  File \"/usr/lib64/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/tmp/fweimer/python27_intermediate'\n>>> \n\nSo this is at least a denial of service.  With laxer permissions, weave uses that directory:\n\n[fweimer@localhost ~]$ ls -lhd /tmp/fweimer\ndrwxrwxrwx. 2 nobody nobody 4.0K Aug 14 09:45 /tmp/fweimer\n[fweimer@localhost ~]$ python\nPython 2.7.5 (default, Aug  5 2013, 02:37:08) \n[GCC 4.8.1 20130717 (Red Hat 4.8.1-5)] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import random, scipy.weave; a=1; scipy.weave.inline('printf(\"%%d\\\\n\",a,%f);' % random.random(),['a'])\ncreating /tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc\nIn file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,\n                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,\n                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:15,\n                 from /home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp:22:\n/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning \"Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]\n #warning \"Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\"\n  ^\n/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp: In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:\n/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.cpp:673:29: warning: too many arguments for format [-Wformat-extra-args]\n     printf(\"%d\\n\",a,0.946759);        /*I would like to fill in changed locals and globals here...*/   \n                             ^\n1\n>>> \n[fweimer@localhost ~]$ find /tmp/fweimer -type f \n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/home/fweimer/.python27_compiled/sc_777337fffcbda13be8e1c5a8c5ce3aef0.o\n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/home/fweimer/.python27_compiled/sc_a35dbf436a57cecf7066976e9761bd000.o\n/tmp/fweimer/python27_intermediate/compiler_ddba75e443dd3a9a304e5ced64620fbc/usr/lib64/python2.7/site-packages/scipy/weave/scxx/weave_imp.o\n\nThe files are actually used as linker input files, so this allows local users to trick each other into executing code.\n\nThis is much more severe, not merely hardening, and probably warrants CVE assignment.  This should be fixed in cooperation with upstream, perhaps with a (short) embargo period.  Please do not commit a fix to a public repository or file a public bug report."
							},
							{
								"isprivate": "0",
								"commentid": "6215952",
								"comment_count": "11",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-08-15 16:16:43 +0000",
								"thetext": "To summarize, scipy.weave will use /tmp/[username] as persistent storage (cache), but it does not check whether or not this directory already exists, does not check whether it is a directory or a symlink, and also does not verify permissions or ownership, which could allow someone to place code in this directory that would be executed as the user running scipy.weave.\n\nIdeally, it should be creating the directory if it doesn't exist with appropriate ownership/permissions, and if the directory already exists (and permissions/ownership is inappropriate), create a new directory and use it instead (in a similar way that Pulseaudio does, perhaps /var/tmp/scipy-[variable])."
							},
							{
								"isprivate": "0",
								"commentid": "6215962",
								"comment_count": "12",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-08-15 16:19:36 +0000",
								"thetext": "Acknowledgements:\n\nThis issue was found by Florian Weimer of the Red Hat Product Security Team."
							},
							{
								"isprivate": "0",
								"commentid": "6228703",
								"comment_count": "14",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-20 13:33:35 +0000",
								"thetext": "(In reply to Vincent Danen from comment #11)\n> To summarize, scipy.weave will use /tmp/[username] as persistent storage\n> (cache), but it does not check whether or not this directory already exists\n\nI would like to correct this a little bit. scipy does check whether the dir exists. This is the function that is responsible for creating the directory:\n\n\ndef intermediate_dir():\n    \"\"\" Location in temp dir for storing .cpp and .o  files during\n        builds.\n    \"\"\"\n    python_name = \"python%d%d_intermediate\" % tuple(sys.version_info[:2])\n    path = os.path.join(tempfile.gettempdir(),\"%s\" % whoami(),python_name)\n    if not os.path.exists(path):\n        os.makedirs(path, mode=0o700)\n    return path\n\n\nAs you can see, it checks if the directory already exists.\n\nCurrently I'm writing tests for this CVE. When I finish I'll attach them here so it will be pretty easy to fix this. Is this okay?"
							},
							{
								"isprivate": "0",
								"commentid": "6233204",
								"comment_count": "15",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-21 13:45:54 +0000",
								"thetext": "Created attachment 788882\nUnit tests for this CVE\n\nI've mocked unit tests for this CVE. These are definitely not final. Especially a part, where the tests play with actual temporary directory (/tmp/<name>/python27...) and not with one created only for purpose of the tests, is really bad. They were created to fit current code only. Also I wanted to know if the tests check correct values.\n\nOnce there will be code which fixes this bug, the tests will be easy to adapt."
							},
							{
								"isprivate": "0",
								"commentid": "6239863",
								"comment_count": "16",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-23 10:17:04 +0000",
								"thetext": "Created attachment 789545\nPatch"
							},
							{
								"isprivate": "0",
								"commentid": "6240190",
								"comment_count": "17",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-23 12:35:39 +0000",
								"thetext": "Created attachment 789580\ncatalog reproducer\n\nWhile writing the patch I noticed that same thing occurs for persistent cache/store of compiled functions -- catalog. We agreed with Florian that it should be fixed too, so I'm going to \"respin\" the patch."
							},
							{
								"isprivate": "0",
								"commentid": "6247481",
								"comment_count": "18",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-08-27 01:08:25 +0000",
								"thetext": "Thanks, Tomas.  Have we reported this upstream or gotten any feedback on it from them yet?"
							},
							{
								"isprivate": "0",
								"commentid": "6248717",
								"comment_count": "19",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-27 09:45:05 +0000",
								"thetext": "As I wrote in the e-mail to your mailing list, I haven't got response yet. This may be because there was an event taking place recently -- EuroSciPy. So I'm assuming they were pretty busy and that's why they didn't respond."
							},
							{
								"isprivate": "0",
								"commentid": "6250094",
								"comment_count": "20",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-08-27 14:50:53 +0000",
								"thetext": "Created attachment 791020\nPatch 2\n\nThis patch fixes original issue and similar problem with function 'default_dir'. I will post a build of scipy here tomorrow."
							},
							{
								"isprivate": "0",
								"commentid": "6298020",
								"comment_count": "22",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-09-11 18:11:44 +0000",
								"thetext": "Any response from upstream yet?"
							},
							{
								"isprivate": "0",
								"commentid": "6299440",
								"comment_count": "23",
								"who": {
									"text": "ttomecek",
									"name": "Tomas Tomecek"
								},
								"bug_when": "2013-09-12 05:56:44 +0000",
								"thetext": "(In reply to Vincent Danen from comment #22)\n> Any response from upstream yet?\n\nUnfortunately no. I'm assuming they have problems with verification if the patch works. Especially on Windows environment. I may write them this week if no response come til Friday."
							},
							{
								"isprivate": "0",
								"commentid": "6353577",
								"comment_count": "24",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-09-27 17:47:26 +0000",
								"thetext": "Created attachment 804078\npatch from upstream"
							},
							{
								"isprivate": "0",
								"commentid": "6376332",
								"comment_count": "25",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-10-03 21:39:40 +0000",
								"thetext": "The CRD date for this is October 10th."
							},
							{
								"isprivate": "0",
								"commentid": "6409691",
								"comment_count": "26",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-10-11 18:17:28 +0000",
								"thetext": "SciPy 0.12.1 has been released to fix this issue:\n\nhttp://sourceforge.net/projects/scipy/files/scipy/0.12.1/\nhttps://github.com/scipy/scipy/commit/bd296e0336420b840fcd2faabb97084fd252a973"
							},
							{
								"isprivate": "0",
								"commentid": "6409718",
								"comment_count": "27",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-10-11 18:25:35 +0000",
								"thetext": "\nCreated scipy tracking bugs for this issue:\n\nAffects: fedora-all [bug 1018351]\nAffects: epel-5 [bug 1018353]"
							},
							{
								"isprivate": "0",
								"commentid": "6423554",
								"comment_count": "28",
								"who": {
									"text": "vdanen",
									"name": "Vincent Danen"
								},
								"bug_when": "2013-10-15 22:37:28 +0000",
								"thetext": "This is also correct in SciPy 0.13.0rc1:\n\nsourceforge.net/projects/scipy/files/scipy/0.13.0rc1/"
							},
							{
								"isprivate": "0",
								"commentid": "6460080",
								"comment_count": "29",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2013-10-27 05:37:17 +0000",
								"thetext": "scipy-0.12.1-1.fc18 has been pushed to the Fedora 18 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "6460092",
								"comment_count": "30",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2013-10-27 05:39:16 +0000",
								"thetext": "scipy-0.12.1-1.fc19 has been pushed to the Fedora 19 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "6480458",
								"comment_count": "31",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2013-11-01 21:05:47 +0000",
								"thetext": "scipy-0.6.0-7.el5 has been pushed to the Fedora EPEL 5 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "6504807",
								"comment_count": "32",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2013-11-10 06:55:56 +0000",
								"thetext": "scipy-0.12.1-1.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "6409716",
						"comment_count": "0",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-11 18:25:21 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora EPEL.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen creating a Bodhi update request, please use the bodhi submission link\nnoted in the next comment(s).  This will include the bug IDs of this\ntracking bug as well as the relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nBodhi notes field when available.\n\nepel-5 tracking bug for scipy: see blocks bug list for full details of the security issue(s).\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "6409717",
						"comment_count": "1",
						"who": {
							"text": "vdanen",
							"name": "Vincent Danen"
						},
						"bug_when": "2013-10-11 18:25:31 +0000",
						"thetext": "\nPlease use the following update submission link to create the Bodhi\nrequest for this issue as it contains the top-level parent bug(s) as well\nas this tracking bug.  This will ensure that all associated bugs get\nupdated when new packages are pushed to stable.\n\nPlease also ensure that the \"Close bugs when update is stable\" option\nremains checked.\n\nBodhi update submission link:\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=916690,1018353"
					},
					{
						"isprivate": "0",
						"commentid": "6419341",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-10-15 04:25:46 +0000",
						"thetext": "scipy-0.6.0-7.el5 has been submitted as an update for Fedora EPEL 5.\nhttps://admin.fedoraproject.org/updates/scipy-0.6.0-7.el5"
					},
					{
						"isprivate": "0",
						"commentid": "6431691",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-10-17 18:08:32 +0000",
						"thetext": "Package scipy-0.6.0-7.el5:\n* should fix your issue,\n* was pushed to the Fedora EPEL 5 testing repository,\n* should be available at your local mirror within two days.\nUpdate it with:\n# su -c 'yum update --enablerepo=epel-testing scipy-0.6.0-7.el5'\nas soon as you are able to.\nPlease go to the following url:\nhttps://admin.fedoraproject.org/updates/FEDORA-EPEL-2013-11879/scipy-0.6.0-7.el5\nthen log in and leave karma (feedback)."
					},
					{
						"isprivate": "0",
						"commentid": "6480457",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2013-11-01 21:05:29 +0000",
						"thetext": "scipy-0.6.0-7.el5 has been pushed to the Fedora EPEL 5 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"nvr": "scipy-0.6.0-7.el5",
			"signed": true,
			"type": "rpm",
			"package": {
				"i386": [
					{
						"name": "scipy-debuginfo",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "i386"
					},
					{
						"name": "scipy",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "i386"
					}
				],
				"ppc": [
					{
						"name": "scipy",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "ppc"
					},
					{
						"name": "scipy-debuginfo",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "ppc"
					}
				],
				"src": [
					{
						"name": "scipy",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "scipy-debuginfo",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "x86_64"
					},
					{
						"name": "scipy",
						"version": "0.6.0",
						"release": "7.el5",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 127341,
			"text": "This update has been submitted for testing by orion. ",
			"timestamp": "2013-10-15 04:25:51",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127342,
			"text": "This update is currently being pushed to the Fedora EPEL 5 testing updates repository.",
			"timestamp": "2013-10-17 15:56:59",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127343,
			"text": "This update has been pushed to testing",
			"timestamp": "2013-10-17 18:08:34",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127344,
			"text": "This update has reached 14 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2013-10-31 22:08:41",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127345,
			"text": "This update has been submitted for stable by orion. ",
			"timestamp": "2013-10-31 22:40:50",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127346,
			"text": "This update is currently being pushed to the Fedora EPEL 5 stable updates repository.",
			"timestamp": "2013-11-01 18:41:23",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 127347,
			"text": "This update has been pushed to stable",
			"timestamp": "2013-11-01 21:05:54",
			"update_id": 17127,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2013-11-01 21:05:54",
	"date_stable": "2013-11-01 21:05:54",
	"date_submitted": "2013-10-15 04:25:33",
	"date_testing": "2013-10-17 18:08:34",
	"notes": "Add patch for CVE-2013-4251: insecure use of /tmp by scipy.weave",
	"pushed": true,
	"release": {
		"branch": "el5",
		"candidate_tag": "dist-5E-epel-testing-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "dist-5E-epel",
		"id_prefix": "FEDORA-EPEL",
		"long_name": "Fedora EPEL 5",
		"mail_template": "fedora_epel_legacy_errata_template",
		"name": "EL-5",
		"override_tag": "dist-5E-epel-override",
		"package_manager": "unspecified",
		"stable_tag": "dist-5E-epel",
		"state": "archived",
		"testing_tag": "dist-5E-epel-testing",
		"version": "5"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"title": "scipy-0.6.0-7.el5",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2013-11879",
	"unstable_karma": -3,
	"updateid": "FEDORA-EPEL-2013-11879",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/4dbef71827789c946f87277314d67676f0629ea0b689a0d0a55f326ae3a4cd72?s=24&d=retro",
		"email": "orion@nwra.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "astro-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "epel-packagers-sig"
			},
			{
				"name": "scitech_sig"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "scitech"
			},
			{
				"name": "clamav"
			}
		],
		"id": 97,
		"name": "orion",
		"openid": "orion.id.fedoraproject.org"
	},
	"version_hash": "d2dca7645f11a3421b6a23b835d72261b61c0929"
}
