{
	"alias": "FEDORA-2020-db0eb54982",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1906451,
			"parent": true,
			"security": true,
			"title": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality",
			"bugzilla": {
				"bug_id": "1906451",
				"alias": "CVE-2020-29651",
				"creation_ts": "2020-12-10 14:48:23 +0000",
				"short_desc": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality",
				"delta_ts": "2021-10-28 11:00:29 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "low",
				"bug_severity": "low",
				"depends_on": [
					"1906453",
					"1906892",
					"1910397",
					"1910398",
					"1910655",
					"1914836",
					"1914838",
					"1914839"
				],
				"blocked": [
					{
						"bug_id": "1906454",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14588826",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-12-10 14:48:23 +0000",
						"thetext": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.\n\nReference:\nhttps://github.com/pytest-dev/py/issues/256\n\nUpstream patch:\nhttps://github.com/pytest-dev/py/pull/257"
					},
					{
						"isprivate": "0",
						"commentid": "14588835",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-12-10 14:50:11 +0000",
						"thetext": "Created python-py tracking bugs for this issue:\n\nAffects: fedora-all [bug 1906453]"
					},
					{
						"isprivate": "0",
						"commentid": "14592311",
						"comment_count": "3",
						"who": {
							"text": "proguski",
							"name": "Przemyslaw Roguski"
						},
						"bug_when": "2020-12-11 17:06:37 +0000",
						"thetext": "External References:\n\nhttps://github.com/pytest-dev/py/issues/256"
					},
					{
						"isprivate": "0",
						"commentid": "14592329",
						"comment_count": "4",
						"who": {
							"text": "proguski",
							"name": "Przemyslaw Roguski"
						},
						"bug_when": "2020-12-11 17:15:52 +0000",
						"thetext": "Upstream fixed version is not released yet, but the patch is already merged with master branch:\nhttps://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					},
					{
						"isprivate": "0",
						"commentid": "14615369",
						"comment_count": "6",
						"who": {
							"text": "proguski",
							"name": "Przemyslaw Roguski"
						},
						"bug_when": "2020-12-18 10:30:28 +0000",
						"thetext": "Upstream PR:\nhttps://github.com/earthgecko/skyline/pull/381"
					},
					{
						"isprivate": "0",
						"commentid": "14750543",
						"comment_count": "11",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2021-02-04 22:21:59 +0000",
						"thetext": "Statement:\n\nIn Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-py package."
					}
				]
			}
		},
		{
			"bug_id": 1906453,
			"security": true,
			"title": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality [fedora-all]",
			"bugzilla": {
				"bug_id": "1906453",
				"creation_ts": "2020-12-10 14:49:55 +0000",
				"short_desc": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality [fedora-all]",
				"delta_ts": "2021-01-05 01:25:57 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "low",
				"blocked": [
					{
						"bug_id": "1906451",
						"alias": "CVE-2020-29651",
						"creation_ts": "2020-12-10 14:48:23 +0000",
						"short_desc": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality",
						"delta_ts": "2021-10-28 11:00:29 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"1906453",
							"1906892",
							"1910397",
							"1910398",
							"1910655",
							"1914836",
							"1914838",
							"1914839"
						],
						"blocked": [
							{
								"bug_id": "1906454",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14588826",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-12-10 14:48:23 +0000",
								"thetext": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.\n\nReference:\nhttps://github.com/pytest-dev/py/issues/256\n\nUpstream patch:\nhttps://github.com/pytest-dev/py/pull/257"
							},
							{
								"isprivate": "0",
								"commentid": "14588835",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-12-10 14:50:11 +0000",
								"thetext": "Created python-py tracking bugs for this issue:\n\nAffects: fedora-all [bug 1906453]"
							},
							{
								"isprivate": "0",
								"commentid": "14592311",
								"comment_count": "3",
								"who": {
									"text": "proguski",
									"name": "Przemyslaw Roguski"
								},
								"bug_when": "2020-12-11 17:06:37 +0000",
								"thetext": "External References:\n\nhttps://github.com/pytest-dev/py/issues/256"
							},
							{
								"isprivate": "0",
								"commentid": "14592329",
								"comment_count": "4",
								"who": {
									"text": "proguski",
									"name": "Przemyslaw Roguski"
								},
								"bug_when": "2020-12-11 17:15:52 +0000",
								"thetext": "Upstream fixed version is not released yet, but the patch is already merged with master branch:\nhttps://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
							},
							{
								"isprivate": "0",
								"commentid": "14615369",
								"comment_count": "6",
								"who": {
									"text": "proguski",
									"name": "Przemyslaw Roguski"
								},
								"bug_when": "2020-12-18 10:30:28 +0000",
								"thetext": "Upstream PR:\nhttps://github.com/earthgecko/skyline/pull/381"
							},
							{
								"isprivate": "0",
								"commentid": "14750543",
								"comment_count": "11",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2021-02-04 22:21:59 +0000",
								"thetext": "Statement:\n\nIn Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-py package."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14588832",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-12-10 14:49:55 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "14588834",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-12-10 14:49:58 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1906451,1906453\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14630137",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-12-27 11:48:08 +0000",
						"thetext": "FEDORA-2020-8371993b6b has been submitted as an update to Fedora 33. https://bodhi.fedoraproject.org/updates/FEDORA-2020-8371993b6b"
					},
					{
						"isprivate": "0",
						"commentid": "14630139",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-12-27 11:53:02 +0000",
						"thetext": "FEDORA-2020-db0eb54982 has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-db0eb54982"
					},
					{
						"isprivate": "0",
						"commentid": "14630581",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-12-28 00:33:58 +0000",
						"thetext": "FEDORA-2020-db0eb54982 has been pushed to the Fedora 32 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-db0eb54982`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-db0eb54982\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14630622",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-12-28 01:05:08 +0000",
						"thetext": "FEDORA-2020-8371993b6b has been pushed to the Fedora 33 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-8371993b6b`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-8371993b6b\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14642504",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-05 01:19:01 +0000",
						"thetext": "FEDORA-2020-db0eb54982 has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14642532",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-01-05 01:25:57 +0000",
						"thetext": "FEDORA-2020-8371993b6b has been pushed to the Fedora 33 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-py-1.10.0-1.fc32",
			"release_id": 35,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-py",
						"version": "1.10.0",
						"release": "1.fc32",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-py",
						"version": "1.10.0",
						"release": "1.fc32",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1791107,
			"text": "This update has been submitted for testing by thm. ",
			"timestamp": "2020-12-27 11:53:01",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1791108,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-12-27 11:53:01",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1791109,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2020-12-27 11:53:01",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1791112,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-12-27 12:01:33",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1791545,
			"text": "This update has been pushed to testing.",
			"timestamp": "2020-12-28 00:34:01",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1799165,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2021-01-04 00:34:54",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1799166,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2021-01-04 00:34:55",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1801104,
			"text": "This update has been pushed to stable.",
			"timestamp": "2021-01-05 01:19:10",
			"update_id": 267613,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2021-01-05 01:18:53",
	"date_stable": "2021-01-05 01:18:53",
	"date_submitted": "2020-12-27 11:53:00",
	"date_testing": "2020-12-28 00:33:53",
	"meets_testing_requirements": true,
	"notes": "#### 1.10.0 (2020-12-12) ####\n\n- Fix a regular expression DoS vulnerability in the py.path.svnwc SVN blame functionality (CVE-2020-29651)\n- Update vendored apipkg: 1.4 => 1.5\n- Update vendored iniconfig: 1.0.0 => 1.1.1\n\n#### 1.9.0 (2020-06-24) ####\n\n- Add type annotation stubs for the following modules:\n    - ``py.error``\n    - ``py.iniconfig``\n    - ``py.path`` (not including SVN paths)\n    - ``py.io``\n    - ``py.xml``\n\n    There are no plans to type other modules at this time.\n\n    The type annotations are provided in external .pyi files, not inline in the code, and may therefore contain small errors or omissions. If you use ``py`` in conjunction with a type checker, and encounter any type errors you believe should be accepted, please report it in an issue.",
	"pushed": true,
	"release": {
		"branch": "f32",
		"candidate_tag": "f32-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f32",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 32",
		"mail_template": "fedora_errata_template",
		"name": "F32",
		"override_tag": "f32-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f32-signing-pending",
		"pending_stable_tag": "f32-updates-pending",
		"pending_testing_tag": "f32-updates-testing-pending",
		"stable_tag": "f32-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f32-updates-testing",
		"version": "32"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-py-1.10.0-1.fc32",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2020-db0eb54982",
	"unstable_karma": -3,
	"updateid": "FEDORA-2020-db0eb54982",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/9059004173d8a8bfddf2eb8c342af2c655aabe40786c6fffa5b0527680120734?s=24&d=retro",
		"email": "thomas.moschny@gmx.de",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			}
		],
		"id": 101,
		"name": "thm",
		"openid": "thm.id.fedoraproject.org"
	},
	"version_hash": "031ac548274d1afec6d1f1e68b49a3e079486084"
}
