{
	"alias": "FEDORA-2020-c2639662af",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1798515,
			"parent": true,
			"security": true,
			"title": "CVE-2020-7471 django: potential SQL injection via StringAgg(delimiter)",
			"bugzilla": {
				"bug_id": "1798515",
				"alias": "CVE-2020-7471",
				"creation_ts": "2020-02-05 14:31:02 +0000",
				"short_desc": "CVE-2020-7471 django: potential SQL injection via StringAgg(delimiter)",
				"delta_ts": "2021-12-14 18:47:58 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"1798518",
					"1798521",
					"1798516",
					"1798519",
					"1798520",
					"1802139",
					"1809129",
					"1812715",
					"1812716",
					"1812717",
					"1813793"
				],
				"blocked": [
					{
						"bug_id": "1798517",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13578779",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-02-05 14:31:02 +0000",
						"thetext": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.\n\nReference:\nhttps://www.openwall.com/lists/oss-security/2020/02/03/1"
					},
					{
						"isprivate": "0",
						"commentid": "13578800",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-02-05 14:33:35 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1798521]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 1798518]\nAffects: epel-8 [bug 1798519]\nAffects: fedora-all [bug 1798516]\nAffects: openstack-rdo [bug 1798520]"
					},
					{
						"isprivate": "0",
						"commentid": "13604769",
						"comment_count": "2",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-02-12 12:31:41 +0000",
						"thetext": "Upstream fixes:\n* https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136 [master branch]\n* https://github.com/django/django/commit/505826b469b16ab36693360da9e11fd13213421b [3.0 branch]\n* https://github.com/django/django/commit/c67a368c16e4680b324b4f385398d638db4d8147 [2.2 branch]\n* https://github.com/django/django/commit/001b0634cd309e372edb6d7d95d083d02b8e37bd [1.11 branch]"
					},
					{
						"isprivate": "0",
						"commentid": "13604871",
						"comment_count": "5",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-02-12 12:58:53 +0000",
						"thetext": "PostgreSQL specific aggregation functions were added in python-django v1.9 (see https://docs.djangoproject.com/en/3.0/releases/1.9/)."
					},
					{
						"isprivate": "0",
						"commentid": "13704744",
						"comment_count": "12",
						"who": {
							"text": "ytale",
							"name": "Yadnyawalk Tale"
						},
						"bug_when": "2020-03-16 06:20:43 +0000",
						"thetext": "Statement:\n\nEven though the version of python-django as shipped in Red Hat Update Infrastructure contains the vulnerable code, the Product is not vulnerable because the vulnerable function is not used. Red Hat Update Infrastructure is based on pulp 2, which still uses MongoDB as database and not postgresql, where the flaw lies.\n\nAlthough Red Hat OpenStack Platform 13, 15, & 16 contain the vulnerable code, postgresql is not a supported database hence the lowered impact.\n\nSatellite 6 versions include vulnerable version of python-django however vulnerability is not directly exposed through code since the product does not use 'StringAgg' delimiter implementation. This issue may be get fixed in future updates."
					}
				]
			}
		},
		{
			"bug_id": 1798516,
			"security": true,
			"title": "CVE-2020-7471 python-django: django: potential SQL injection via StringAgg(delimiter) [fedora-all]",
			"bugzilla": {
				"bug_id": "1798516",
				"creation_ts": "2020-02-05 14:33:00 +0000",
				"short_desc": "CVE-2020-7471 python-django: django: potential SQL injection via StringAgg(delimiter) [fedora-all]",
				"delta_ts": "2020-06-19 01:06:45 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"blocked": [
					{
						"bug_id": "1798515",
						"alias": "CVE-2020-7471",
						"creation_ts": "2020-02-05 14:31:02 +0000",
						"short_desc": "CVE-2020-7471 django: potential SQL injection via StringAgg(delimiter)",
						"delta_ts": "2021-12-14 18:47:58 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"1798518",
							"1798521",
							"1798516",
							"1798519",
							"1798520",
							"1802139",
							"1809129",
							"1812715",
							"1812716",
							"1812717",
							"1813793"
						],
						"blocked": [
							{
								"bug_id": "1798517",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "13578779",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-02-05 14:31:02 +0000",
								"thetext": "Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.\n\nReference:\nhttps://www.openwall.com/lists/oss-security/2020/02/03/1"
							},
							{
								"isprivate": "0",
								"commentid": "13578800",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-02-05 14:33:35 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1798521]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 1798518]\nAffects: epel-8 [bug 1798519]\nAffects: fedora-all [bug 1798516]\nAffects: openstack-rdo [bug 1798520]"
							},
							{
								"isprivate": "0",
								"commentid": "13604769",
								"comment_count": "2",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-02-12 12:31:41 +0000",
								"thetext": "Upstream fixes:\n* https://github.com/django/django/commit/eb31d845323618d688ad429479c6dda973056136 [master branch]\n* https://github.com/django/django/commit/505826b469b16ab36693360da9e11fd13213421b [3.0 branch]\n* https://github.com/django/django/commit/c67a368c16e4680b324b4f385398d638db4d8147 [2.2 branch]\n* https://github.com/django/django/commit/001b0634cd309e372edb6d7d95d083d02b8e37bd [1.11 branch]"
							},
							{
								"isprivate": "0",
								"commentid": "13604871",
								"comment_count": "5",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-02-12 12:58:53 +0000",
								"thetext": "PostgreSQL specific aggregation functions were added in python-django v1.9 (see https://docs.djangoproject.com/en/3.0/releases/1.9/)."
							},
							{
								"isprivate": "0",
								"commentid": "13704744",
								"comment_count": "12",
								"who": {
									"text": "ytale",
									"name": "Yadnyawalk Tale"
								},
								"bug_when": "2020-03-16 06:20:43 +0000",
								"thetext": "Statement:\n\nEven though the version of python-django as shipped in Red Hat Update Infrastructure contains the vulnerable code, the Product is not vulnerable because the vulnerable function is not used. Red Hat Update Infrastructure is based on pulp 2, which still uses MongoDB as database and not postgresql, where the flaw lies.\n\nAlthough Red Hat OpenStack Platform 13, 15, & 16 contain the vulnerable code, postgresql is not a supported database hence the lowered impact.\n\nSatellite 6 versions include vulnerable version of python-django however vulnerability is not directly exposed through code since the product does not use 'StringAgg' delimiter implementation. This issue may be get fixed in future updates."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13578788",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-02-05 14:33:00 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "13578789",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-02-05 14:33:02 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1798515,1798516\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "13997878",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2020-06-07 20:38:09 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-django/pull-request/12\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/13\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/14\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/15"
					},
					{
						"isprivate": "0",
						"commentid": "13999613",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 10:24:50 +0000",
						"thetext": "FEDORA-2020-c2639662af has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14000680",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 13:57:13 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14013756",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:21:26 +0000",
						"thetext": "python-django-3.0.7-1.fc32 has been pushed to the Fedora 32 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14013803",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:23:47 +0000",
						"thetext": "python-django-2.2.13-1.fc31 has been pushed to the Fedora 31 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14034225",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:03:30 +0000",
						"thetext": "FEDORA-2020-c2639662af has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14034269",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:06:45 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been pushed to the Fedora 31 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1810088,
			"parent": true,
			"security": true,
			"title": "CVE-2020-9402 django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle",
			"bugzilla": {
				"bug_id": "1810088",
				"alias": "CVE-2020-9402",
				"creation_ts": "2020-03-04 14:25:37 +0000",
				"short_desc": "CVE-2020-9402 django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle",
				"delta_ts": "2021-04-21 16:46:36 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1810095",
					"1810097",
					"1810093",
					"1810094",
					"1810096",
					"1811634",
					"1819819",
					"1825178"
				],
				"blocked": [
					{
						"bug_id": "1810092",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13670634",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-03-04 14:25:37 +0000",
						"thetext": "A flaw was found in Django in a way that GIS functions and aggregates on Oracle were subject to SQL injection, using a suitably crafted tolerance.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "13670680",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-03-04 14:33:31 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1810097]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1810094]\nAffects: fedora-all [bug 1810093]\nAffects: openstack-rdo [bug 1810096]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1810095]"
					},
					{
						"isprivate": "0",
						"commentid": "13673200",
						"comment_count": "2",
						"who": {
							"text": "slong",
							"name": "Summer Long"
						},
						"bug_when": "2020-03-05 06:21:10 +0000",
						"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "13673216",
						"comment_count": "3",
						"who": {
							"text": "slong",
							"name": "Summer Long"
						},
						"bug_when": "2020-03-05 06:37:17 +0000",
						"thetext": "Upstream commits:\n3.0.: https://github.com/django/django/commit/26a5cf834526e291db00385dd33d319b8271fc4c\n2.2 : https://github.com/django/django/commit/fe886a3b58a93cfbe8864b485f93cb6d426cd1f2\n1.1 : https://github.com/django/django/commit/02d97f3c9a88adc890047996e5606180bd1c6166"
					},
					{
						"isprivate": "0",
						"commentid": "13683125",
						"comment_count": "6",
						"who": {
							"text": "slong",
							"name": "Summer Long"
						},
						"bug_when": "2020-03-09 01:01:18 +0000",
						"thetext": "Mitigation:\n\nThere is no known mitigation for this issue, the flaw can only be resolved by applying updates."
					},
					{
						"isprivate": "0",
						"commentid": "14099590",
						"comment_count": "15",
						"who": {
							"text": "slong",
							"name": "Summer Long"
						},
						"bug_when": "2020-07-13 02:21:33 +0000",
						"thetext": "Statement:\n\nAlthough the following products ship the flawed code, they do not use or support its functionality and therefore will not be updated:\n* Red Hat OpenStack Platform\n* Red Hat Update Infrastructure 3\n* Red Hat Ceph Storage\n\nThe following products will be updated. However, because both products do not use the functionality, their Impact has been reduced to 'Low':\n* Red Hat Gluster Storage\n* Red Hat Satellite 6"
					},
					{
						"isprivate": "0",
						"commentid": "14984538",
						"comment_count": "16",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-04-21 13:10:18 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.8 for RHEL 7\n\nVia RHSA-2021:1313 https://access.redhat.com/errata/RHSA-2021:1313"
					},
					{
						"isprivate": "0",
						"commentid": "14985916",
						"comment_count": "17",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2021-04-21 16:46:36 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-9402"
					}
				]
			}
		},
		{
			"bug_id": 1810093,
			"security": true,
			"title": "CVE-2020-9402 python-django: django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle [fedora-all]",
			"bugzilla": {
				"bug_id": "1810093",
				"creation_ts": "2020-03-04 14:32:59 +0000",
				"short_desc": "CVE-2020-9402 python-django: django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle [fedora-all]",
				"delta_ts": "2020-06-19 01:06:47 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1810088",
						"alias": "CVE-2020-9402",
						"creation_ts": "2020-03-04 14:25:37 +0000",
						"short_desc": "CVE-2020-9402 django: potential SQL injection via \"tolerance\" parameter in GIS functions and aggregates on Oracle",
						"delta_ts": "2021-04-21 16:46:36 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1810095",
							"1810097",
							"1810093",
							"1810094",
							"1810096",
							"1811634",
							"1819819",
							"1825178"
						],
						"blocked": [
							{
								"bug_id": "1810092",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "13670634",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-03-04 14:25:37 +0000",
								"thetext": "A flaw was found in Django in a way that GIS functions and aggregates on Oracle were subject to SQL injection, using a suitably crafted tolerance.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "13670680",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-03-04 14:33:31 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1810097]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1810094]\nAffects: fedora-all [bug 1810093]\nAffects: openstack-rdo [bug 1810096]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1810095]"
							},
							{
								"isprivate": "0",
								"commentid": "13673200",
								"comment_count": "2",
								"who": {
									"text": "slong",
									"name": "Summer Long"
								},
								"bug_when": "2020-03-05 06:21:10 +0000",
								"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/mar/04/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "13673216",
								"comment_count": "3",
								"who": {
									"text": "slong",
									"name": "Summer Long"
								},
								"bug_when": "2020-03-05 06:37:17 +0000",
								"thetext": "Upstream commits:\n3.0.: https://github.com/django/django/commit/26a5cf834526e291db00385dd33d319b8271fc4c\n2.2 : https://github.com/django/django/commit/fe886a3b58a93cfbe8864b485f93cb6d426cd1f2\n1.1 : https://github.com/django/django/commit/02d97f3c9a88adc890047996e5606180bd1c6166"
							},
							{
								"isprivate": "0",
								"commentid": "13683125",
								"comment_count": "6",
								"who": {
									"text": "slong",
									"name": "Summer Long"
								},
								"bug_when": "2020-03-09 01:01:18 +0000",
								"thetext": "Mitigation:\n\nThere is no known mitigation for this issue, the flaw can only be resolved by applying updates."
							},
							{
								"isprivate": "0",
								"commentid": "14099590",
								"comment_count": "15",
								"who": {
									"text": "slong",
									"name": "Summer Long"
								},
								"bug_when": "2020-07-13 02:21:33 +0000",
								"thetext": "Statement:\n\nAlthough the following products ship the flawed code, they do not use or support its functionality and therefore will not be updated:\n* Red Hat OpenStack Platform\n* Red Hat Update Infrastructure 3\n* Red Hat Ceph Storage\n\nThe following products will be updated. However, because both products do not use the functionality, their Impact has been reduced to 'Low':\n* Red Hat Gluster Storage\n* Red Hat Satellite 6"
							},
							{
								"isprivate": "0",
								"commentid": "14984538",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-04-21 13:10:18 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.8 for RHEL 7\n\nVia RHSA-2021:1313 https://access.redhat.com/errata/RHSA-2021:1313"
							},
							{
								"isprivate": "0",
								"commentid": "14985916",
								"comment_count": "17",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2021-04-21 16:46:36 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-9402"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13670667",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-03-04 14:32:59 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "13670668",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-03-04 14:33:01 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1810088,1810093\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "13997880",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2020-06-07 20:38:20 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-django/pull-request/12\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/13\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/14\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/15"
					},
					{
						"isprivate": "0",
						"commentid": "13999616",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 10:24:53 +0000",
						"thetext": "FEDORA-2020-c2639662af has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14000681",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 13:57:15 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14013757",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:21:29 +0000",
						"thetext": "python-django-3.0.7-1.fc32 has been pushed to the Fedora 32 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14013804",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:23:49 +0000",
						"thetext": "python-django-2.2.13-1.fc31 has been pushed to the Fedora 31 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14034226",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:03:36 +0000",
						"thetext": "FEDORA-2020-c2639662af has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14034270",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:06:47 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been pushed to the Fedora 31 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1843614,
			"parent": true,
			"security": true,
			"title": "CVE-2020-13254 django: potential data leakage via malformed memcached keys",
			"bugzilla": {
				"bug_id": "1843614",
				"alias": "CVE-2020-13254",
				"creation_ts": "2020-06-03 16:41:32 +0000",
				"short_desc": "CVE-2020-13254 django: potential data leakage via malformed memcached keys",
				"delta_ts": "2021-12-14 18:47:58 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1843618",
					"1843620",
					"1843616",
					"1843617",
					"1843619",
					"1844992",
					"1845340",
					"1845341",
					"1845342",
					"1845442",
					"1845455",
					"1845729",
					"1852453"
				],
				"blocked": [
					{
						"bug_id": "1843622",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2021:0933",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13986950",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:41:32 +0000",
						"thetext": "In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage. In order to avoid this vulnerability, key validation is added to the memcached cache backends.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "13986962",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:42:11 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1843620]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1843616]\nAffects: fedora-all [bug 1843617]\nAffects: openstack-rdo [bug 1843619]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1843618]"
					},
					{
						"isprivate": "0",
						"commentid": "13999453",
						"comment_count": "3",
						"who": {
							"text": "ytale",
							"name": "Yadnyawalk Tale"
						},
						"bug_when": "2020-06-08 09:47:25 +0000",
						"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases"
					},
					{
						"isprivate": "0",
						"commentid": "14003479",
						"comment_count": "7",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-06-09 09:01:55 +0000",
						"thetext": "Upstream patches:\nhttps://github.com/django/django/commit/2c82414914ae6476be5a166be9ff49c24d0d9069\nhttps://github.com/django/django/commit/229c9c6653356a0bc23846d83b2d4b5d0438a145"
					},
					{
						"isprivate": "0",
						"commentid": "14003495",
						"comment_count": "8",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-06-09 09:08:59 +0000",
						"thetext": "Created python2-django1.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1845442]"
					},
					{
						"isprivate": "0",
						"commentid": "14066945",
						"comment_count": "14",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2020-06-30 13:09:20 +0000",
						"thetext": "Statement:\n\nRed Hat Satellite 6 ships affected python-django, however, it does not use memcached implementation in product code hence not vulnerable to this flaw.\n\nRed Hat Update Infrastructure 3 ships an affected version of python-django, however it does not use memcached as a cache backend and it is not vulnerable to this flaw.\n\nRed Hat Ceph Storage(RHCS) ships an affected version of python-django used with calamari and graphite which are no longer supported, hence the django package will not be fixed for RHCS."
					},
					{
						"isprivate": "0",
						"commentid": "14881637",
						"comment_count": "16",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-03-17 15:29:18 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 16.1\n\nVia RHSA-2021:0915 https://access.redhat.com/errata/RHSA-2021:0915"
					},
					{
						"isprivate": "0",
						"commentid": "14882610",
						"comment_count": "17",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2021-03-17 19:51:43 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-13254"
					},
					{
						"isprivate": "0",
						"commentid": "14884799",
						"comment_count": "18",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-03-18 13:07:02 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 13.0 (Queens)\n  Red Hat OpenStack Platform 13.0 (Queens) for RHEL 7.6 EUS\n\nVia RHSA-2021:0933 https://access.redhat.com/errata/RHSA-2021:0933"
					}
				]
			}
		},
		{
			"bug_id": 1843617,
			"security": true,
			"title": "CVE-2020-13254 python-django: django: potential data leakage via malformed memcached keys [fedora-all]",
			"bugzilla": {
				"bug_id": "1843617",
				"creation_ts": "2020-06-03 16:41:44 +0000",
				"short_desc": "CVE-2020-13254 python-django: django: potential data leakage via malformed memcached keys [fedora-all]",
				"delta_ts": "2020-06-19 01:06:49 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1843614",
						"alias": "CVE-2020-13254",
						"creation_ts": "2020-06-03 16:41:32 +0000",
						"short_desc": "CVE-2020-13254 django: potential data leakage via malformed memcached keys",
						"delta_ts": "2021-12-14 18:47:58 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1843618",
							"1843620",
							"1843616",
							"1843617",
							"1843619",
							"1844992",
							"1845340",
							"1845341",
							"1845342",
							"1845442",
							"1845455",
							"1845729",
							"1852453"
						],
						"blocked": [
							{
								"bug_id": "1843622",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2021:0933",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "13986950",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-06-03 16:41:32 +0000",
								"thetext": "In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage. In order to avoid this vulnerability, key validation is added to the memcached cache backends.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "13986962",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-06-03 16:42:11 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1843620]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1843616]\nAffects: fedora-all [bug 1843617]\nAffects: openstack-rdo [bug 1843619]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1843618]"
							},
							{
								"isprivate": "0",
								"commentid": "13999453",
								"comment_count": "3",
								"who": {
									"text": "ytale",
									"name": "Yadnyawalk Tale"
								},
								"bug_when": "2020-06-08 09:47:25 +0000",
								"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases"
							},
							{
								"isprivate": "0",
								"commentid": "14003479",
								"comment_count": "7",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-06-09 09:01:55 +0000",
								"thetext": "Upstream patches:\nhttps://github.com/django/django/commit/2c82414914ae6476be5a166be9ff49c24d0d9069\nhttps://github.com/django/django/commit/229c9c6653356a0bc23846d83b2d4b5d0438a145"
							},
							{
								"isprivate": "0",
								"commentid": "14003495",
								"comment_count": "8",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-06-09 09:08:59 +0000",
								"thetext": "Created python2-django1.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1845442]"
							},
							{
								"isprivate": "0",
								"commentid": "14066945",
								"comment_count": "14",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2020-06-30 13:09:20 +0000",
								"thetext": "Statement:\n\nRed Hat Satellite 6 ships affected python-django, however, it does not use memcached implementation in product code hence not vulnerable to this flaw.\n\nRed Hat Update Infrastructure 3 ships an affected version of python-django, however it does not use memcached as a cache backend and it is not vulnerable to this flaw.\n\nRed Hat Ceph Storage(RHCS) ships an affected version of python-django used with calamari and graphite which are no longer supported, hence the django package will not be fixed for RHCS."
							},
							{
								"isprivate": "0",
								"commentid": "14881637",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-03-17 15:29:18 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 16.1\n\nVia RHSA-2021:0915 https://access.redhat.com/errata/RHSA-2021:0915"
							},
							{
								"isprivate": "0",
								"commentid": "14882610",
								"comment_count": "17",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2021-03-17 19:51:43 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-13254"
							},
							{
								"isprivate": "0",
								"commentid": "14884799",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-03-18 13:07:02 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 13.0 (Queens)\n  Red Hat OpenStack Platform 13.0 (Queens) for RHEL 7.6 EUS\n\nVia RHSA-2021:0933 https://access.redhat.com/errata/RHSA-2021:0933"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13986955",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:41:44 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "13986956",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:41:47 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1843614,1843617\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "13997879",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2020-06-07 20:38:15 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-django/pull-request/12\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/13\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/14\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/15"
					},
					{
						"isprivate": "0",
						"commentid": "13999617",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 10:24:56 +0000",
						"thetext": "FEDORA-2020-c2639662af has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14000682",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 13:57:17 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14013758",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:21:31 +0000",
						"thetext": "python-django-3.0.7-1.fc32 has been pushed to the Fedora 32 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14013805",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:23:51 +0000",
						"thetext": "python-django-2.2.13-1.fc31 has been pushed to the Fedora 31 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14034227",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:03:42 +0000",
						"thetext": "FEDORA-2020-c2639662af has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14034271",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:06:49 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been pushed to the Fedora 31 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1843625,
			"parent": true,
			"security": true,
			"title": "CVE-2020-13596 django: possible XSS via admin ForeignKeyRawIdWidget",
			"bugzilla": {
				"bug_id": "1843625",
				"alias": "CVE-2020-13596",
				"creation_ts": "2020-06-03 16:48:19 +0000",
				"short_desc": "CVE-2020-13596 django: possible XSS via admin ForeignKeyRawIdWidget",
				"delta_ts": "2021-12-14 18:47:58 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1843629",
					"1843630",
					"1843626",
					"1843627",
					"1843631",
					"1844992",
					"1845335",
					"1845336",
					"1845337",
					"1845525",
					"1845582",
					"1846525",
					"1851982"
				],
				"blocked": [
					{
						"bug_id": "1843628",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13986979",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:48:19 +0000",
						"thetext": "Query parameters for the admin ``ForeignKeyRawIdWidget`` were not properly URL encoded, posing an XSS attack vector. ``ForeignKeyRawIdWidget`` now ensures query parameters are correctly URL encoded.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "13986991",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:48:59 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1843630]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1843626]\nAffects: fedora-all [bug 1843627]\nAffects: openstack-rdo [bug 1843631]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1843629]"
					},
					{
						"isprivate": "0",
						"commentid": "13998649",
						"comment_count": "3",
						"who": {
							"text": "ytale",
							"name": "Yadnyawalk Tale"
						},
						"bug_when": "2020-06-08 06:20:35 +0000",
						"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases"
					},
					{
						"isprivate": "0",
						"commentid": "13998655",
						"comment_count": "4",
						"who": {
							"text": "ytale",
							"name": "Yadnyawalk Tale"
						},
						"bug_when": "2020-06-08 06:23:54 +0000",
						"thetext": "Patches have been applied to Django's master branch and the 3.1, 3.0, and 2.2 release branches. \n\nMaster branch: https://github.com/django/django/commit/2dd4d110c159d0c81dff42eaead2c378a0998735\n3.1 release branch: https://github.com/django/django/commit/49d7cc19e33a104bb23f7ae1dbb1240b4f6c40f9\n3.0 release branch: https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38\n2.2 release branch: https://github.com/django/django/commit/6d61860b22875f358fac83d903dc629897934815"
					},
					{
						"isprivate": "0",
						"commentid": "14004455",
						"comment_count": "10",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-06-09 13:00:57 +0000",
						"thetext": "Created python2-django1.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1845525]"
					},
					{
						"isprivate": "0",
						"commentid": "14062586",
						"comment_count": "19",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2020-06-29 14:44:05 +0000",
						"thetext": "Statement:\n\nThe following products ship the flawed code, however they do not make use of ForeignKeyRawIdWidget and are therefore not vulnerable to this flaw:\n* Red Hat Satellite 6\n* Red Hat Update Infrastructure 3\n* Red Hat OpenStack Platform 13, 15, & 16\n* Red Hat Gluster Storage 3\n\nThe version of python-django shipped with Red Hat Ceph Storage(RHCS) was used with calamari and graphite which are no more supported, hence the django package will not be fixed for RHCS."
					}
				]
			}
		},
		{
			"bug_id": 1843627,
			"security": true,
			"title": "CVE-2020-13596 python-django: django: possible XSS via admin ForeignKeyRawIdWidget [fedora-all]",
			"bugzilla": {
				"bug_id": "1843627",
				"creation_ts": "2020-06-03 16:48:33 +0000",
				"short_desc": "CVE-2020-13596 python-django: django: possible XSS via admin ForeignKeyRawIdWidget [fedora-all]",
				"delta_ts": "2020-06-19 01:06:51 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1843625",
						"alias": "CVE-2020-13596",
						"creation_ts": "2020-06-03 16:48:19 +0000",
						"short_desc": "CVE-2020-13596 django: possible XSS via admin ForeignKeyRawIdWidget",
						"delta_ts": "2021-12-14 18:47:58 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1843629",
							"1843630",
							"1843626",
							"1843627",
							"1843631",
							"1844992",
							"1845335",
							"1845336",
							"1845337",
							"1845525",
							"1845582",
							"1846525",
							"1851982"
						],
						"blocked": [
							{
								"bug_id": "1843628",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "13986979",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-06-03 16:48:19 +0000",
								"thetext": "Query parameters for the admin ``ForeignKeyRawIdWidget`` were not properly URL encoded, posing an XSS attack vector. ``ForeignKeyRawIdWidget`` now ensures query parameters are correctly URL encoded.\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "13986991",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-06-03 16:48:59 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1843630]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1843626]\nAffects: fedora-all [bug 1843627]\nAffects: openstack-rdo [bug 1843631]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1843629]"
							},
							{
								"isprivate": "0",
								"commentid": "13998649",
								"comment_count": "3",
								"who": {
									"text": "ytale",
									"name": "Yadnyawalk Tale"
								},
								"bug_when": "2020-06-08 06:20:35 +0000",
								"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/jun/03/security-releases"
							},
							{
								"isprivate": "0",
								"commentid": "13998655",
								"comment_count": "4",
								"who": {
									"text": "ytale",
									"name": "Yadnyawalk Tale"
								},
								"bug_when": "2020-06-08 06:23:54 +0000",
								"thetext": "Patches have been applied to Django's master branch and the 3.1, 3.0, and 2.2 release branches. \n\nMaster branch: https://github.com/django/django/commit/2dd4d110c159d0c81dff42eaead2c378a0998735\n3.1 release branch: https://github.com/django/django/commit/49d7cc19e33a104bb23f7ae1dbb1240b4f6c40f9\n3.0 release branch: https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38\n2.2 release branch: https://github.com/django/django/commit/6d61860b22875f358fac83d903dc629897934815"
							},
							{
								"isprivate": "0",
								"commentid": "14004455",
								"comment_count": "10",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-06-09 13:00:57 +0000",
								"thetext": "Created python2-django1.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1845525]"
							},
							{
								"isprivate": "0",
								"commentid": "14062586",
								"comment_count": "19",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2020-06-29 14:44:05 +0000",
								"thetext": "Statement:\n\nThe following products ship the flawed code, however they do not make use of ForeignKeyRawIdWidget and are therefore not vulnerable to this flaw:\n* Red Hat Satellite 6\n* Red Hat Update Infrastructure 3\n* Red Hat OpenStack Platform 13, 15, & 16\n* Red Hat Gluster Storage 3\n\nThe version of python-django shipped with Red Hat Ceph Storage(RHCS) was used with calamari and graphite which are no more supported, hence the django package will not be fixed for RHCS."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13986983",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:48:33 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "13986984",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-06-03 16:48:36 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1843625,1843627\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "13997877",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2020-06-07 20:38:05 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-django/pull-request/12\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/13\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/14\nhttps://src.fedoraproject.org/rpms/python-django/pull-request/15"
					},
					{
						"isprivate": "0",
						"commentid": "13999619",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 10:24:59 +0000",
						"thetext": "FEDORA-2020-c2639662af has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14000683",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-08 13:57:20 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14013759",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:21:33 +0000",
						"thetext": "python-django-3.0.7-1.fc32 has been pushed to the Fedora 32 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af"
					},
					{
						"isprivate": "0",
						"commentid": "14013806",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-11 19:23:52 +0000",
						"thetext": "python-django-2.2.13-1.fc31 has been pushed to the Fedora 31 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-2e7d30f7aa"
					},
					{
						"isprivate": "0",
						"commentid": "14034228",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:03:49 +0000",
						"thetext": "FEDORA-2020-c2639662af has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14034272",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-06-19 01:06:51 +0000",
						"thetext": "FEDORA-2020-2e7d30f7aa has been pushed to the Fedora 31 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-django-3.0.7-1.fc32",
			"release_id": 35,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python-django-bash-completion",
						"version": "3.0.7",
						"release": "1.fc32",
						"arch": "noarch"
					},
					{
						"name": "python3-django-doc",
						"version": "3.0.7",
						"release": "1.fc32",
						"arch": "noarch"
					},
					{
						"name": "python3-django",
						"version": "3.0.7",
						"release": "1.fc32",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-django",
						"version": "3.0.7",
						"release": "1.fc32",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1404141,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2020-06-08 10:24:45",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1404142,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2020-06-08 10:24:45",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1404144,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-06-08 10:25:00",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1405483,
			"text": "This update's test gating status has been changed to 'greenwave_failed'.",
			"timestamp": "2020-06-09 17:46:05",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1406007,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-06-10 04:32:58",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1407609,
			"text": "This update has been pushed to testing.",
			"timestamp": "2020-06-11 19:22:23",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1419964,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2020-06-18 19:21:29",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1419965,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2020-06-18 19:21:29",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1420349,
			"text": "This update has been pushed to stable.",
			"timestamp": "2020-06-19 01:05:01",
			"update_id": 212008,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2020-06-19 01:01:42",
	"date_stable": "2020-06-19 01:01:42",
	"date_submitted": "2020-06-08 10:24:44",
	"date_testing": "2020-06-11 19:20:07",
	"meets_testing_requirements": true,
	"notes": "- Security fix for CVE-2020-7471.\n- Security fix for CVE-2020-9402.\n- Security fix for CVE-2020-13254.\n- Security fix for CVE-2020-13596.",
	"pushed": true,
	"release": {
		"branch": "f32",
		"candidate_tag": "f32-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f32",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 32",
		"mail_template": "fedora_errata_template",
		"name": "F32",
		"override_tag": "f32-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f32-signing-pending",
		"pending_stable_tag": "f32-updates-pending",
		"pending_testing_tag": "f32-updates-testing-pending",
		"stable_tag": "f32-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f32-updates-testing",
		"version": "32"
	},
	"requirements": "",
	"severity": "high",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-django-3.0.7-1.fc32",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2020-c2639662af",
	"unstable_karma": -2,
	"updateid": "FEDORA-2020-c2639662af",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "fesco"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "b97682628ca814d63123c5b146d58c4587d5a31b"
}
