{
	"alias": "FEDORA-2021-a311bf10d4",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1935913,
			"feedback": [
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1979553,
						"karma": 1,
						"timestamp": "2021-04-09 14:58:05",
						"update_id": 297884,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1979553
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1981156,
						"karma": 1,
						"timestamp": "2021-04-11 11:54:35",
						"update_id": 297811,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1981156
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1978135,
						"karma": 1,
						"timestamp": "2021-04-08 16:08:17",
						"update_id": 297647,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/4d5bf123c258c90abbf2b56c3da4752c620faae0f5ecb9906599f47b4ea52d84?s=24&d=retro",
							"email": "oguz@ersen.moe",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "l10n"
								},
								{
									"name": "fedora-join"
								},
								{
									"name": "ask-fedora"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 5615,
							"name": "ersen",
							"openid": "ersen.id.fedoraproject.org"
						},
						"user_id": 5615
					},
					"comment_id": 1978135
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1978281,
						"karma": 1,
						"timestamp": "2021-04-08 18:29:28",
						"update_id": 297648,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1978281
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1979063,
						"karma": 1,
						"timestamp": "2021-04-09 06:49:50",
						"update_id": 297811,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/4d5bf123c258c90abbf2b56c3da4752c620faae0f5ecb9906599f47b4ea52d84?s=24&d=retro",
							"email": "oguz@ersen.moe",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "l10n"
								},
								{
									"name": "fedora-join"
								},
								{
									"name": "ask-fedora"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 5615,
							"name": "ersen",
							"openid": "ersen.id.fedoraproject.org"
						},
						"user_id": 5615
					},
					"comment_id": 1979063
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2021-3426 python: information disclosure via pydoc",
			"bugzilla": {
				"bug_id": "1935913",
				"alias": "CVE-2021-3426",
				"creation_ts": "2021-03-05 19:20:02 +0000",
				"short_desc": "CVE-2021-3426 python: Information disclosure via pydoc",
				"delta_ts": "2024-06-14 00:40:01 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1936931",
					"1936937",
					"1936698",
					"1936699",
					"1936700",
					"1936701",
					"1936702",
					"1936703",
					"1936933",
					"1936936",
					"1937474",
					"1937475",
					"1937476",
					"1937477",
					"1937479",
					"1937480",
					"1937481",
					"1937482",
					"1937483",
					"1969518"
				],
				"blocked": [
					{
						"bug_id": "1919196",
						"error": "NotPermitted"
					},
					{
						"bug_id": "1937052",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2021:4399",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14846426",
						"comment_count": "0",
						"who": {
							"text": "msiddiqu"
						},
						"bug_when": "2021-03-05 19:20:02 +0000",
						"thetext": "Running `pydoc -p` allows other local users to extract arbitrary files"
					},
					{
						"isprivate": "0",
						"commentid": "14846906",
						"comment_count": "1",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-05 21:50:00 +0000",
						"thetext": "Related upstream PRs:\n\nhttps://github.com/python/cpython/pull/24337\nhttps://github.com/python/cpython/pull/24285"
					},
					{
						"isprivate": "0",
						"commentid": "14857175",
						"comment_count": "11",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 00:11:13 +0000",
						"thetext": "Not sure why it's not mentioned upstream, but in Python 3.7.0 alpha 1+, pydoc has the -n command[1][2]. So using -n can additionally expose this to adjacent attackers rather than just local attackers.\n\n1. https://bugs.python.org/issue31128\n2. https://github.com/python/cpython/commit/6a396c9807b1674a24e240731f18e20de97117a5"
					},
					{
						"isprivate": "0",
						"commentid": "14857211",
						"comment_count": "13",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 00:32:09 +0000",
						"thetext": "Statement:\n\nRed Hat Quay from version 3.4 uses Python from Red Hat Enterprise Linux RPM repositories and therefore may receive an update for this issue in a future release. Earlier versions of Red Hat Quay will not receive an patch for this issue.\n\nPython 2.x.x as shipped in any Red Hat product is not affected. This flaw is out of support scope for python3 as shipped with Red Hat Enterprise Linux 7. For more information about Red Hat Enterprise Linux support scope, please see https://access.redhat.com/support/policy/updates/errata/ ."
					},
					{
						"isprivate": "0",
						"commentid": "14860081",
						"comment_count": "16",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 17:53:06 +0000",
						"thetext": "There is not yet a fix in an upstream Python release at this time."
					},
					{
						"isprivate": "0",
						"commentid": "14860124",
						"comment_count": "17",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 18:00:58 +0000",
						"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937475]\nAffects: fedora-33 [bug 1937483]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937476]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1937474]\nAffects: fedora-32 [bug 1937477]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937479]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937480]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937481]\n\n\nCreated python39 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937482]"
					},
					{
						"isprivate": "0",
						"commentid": "14947762",
						"comment_count": "19",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-04-08 22:03:52 +0000",
						"thetext": "Mitigation:\n\nUse the console (no argument needed) or HTML file (-w argument) output to generate docs rather than the HTTP server options. Put differently, do not use the -p or -n options of pydoc."
					},
					{
						"isprivate": "0",
						"commentid": "15415647",
						"comment_count": "23",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-08-24 08:09:10 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n\nVia RHSA-2021:3254 https://access.redhat.com/errata/RHSA-2021:3254"
					},
					{
						"isprivate": "0",
						"commentid": "15417479",
						"comment_count": "24",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2021-08-24 15:34:58 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2021-3426"
					},
					{
						"isprivate": "0",
						"commentid": "15667044",
						"comment_count": "25",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 17:27:06 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4160 https://access.redhat.com/errata/RHSA-2021:4160"
					},
					{
						"isprivate": "0",
						"commentid": "15667064",
						"comment_count": "26",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 17:28:15 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4162 https://access.redhat.com/errata/RHSA-2021:4162"
					},
					{
						"isprivate": "0",
						"commentid": "15668236",
						"comment_count": "27",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 18:37:04 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4399 https://access.redhat.com/errata/RHSA-2021:4399"
					}
				]
			}
		},
		{
			"bug_id": 1937482,
			"feedback": [
				{
					"bug_id": 1937482,
					"comment": {
						"id": 1979553,
						"karma": 1,
						"timestamp": "2021-04-09 14:58:05",
						"update_id": 297884,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1979553
				}
			],
			"security": true,
			"title": "CVE-2021-3426 python39: python: information disclosure via pydoc [fedora-32]",
			"bugzilla": {
				"bug_id": "1937482",
				"creation_ts": "2021-03-10 18:00:38 +0000",
				"short_desc": "CVE-2021-3426 python39: python: information disclosure via pydoc [fedora-32]",
				"delta_ts": "2021-04-10 23:19:12 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1935913",
						"alias": "CVE-2021-3426",
						"creation_ts": "2021-03-05 19:20:02 +0000",
						"short_desc": "CVE-2021-3426 python: Information disclosure via pydoc",
						"delta_ts": "2024-06-14 00:40:01 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1936931",
							"1936937",
							"1936698",
							"1936699",
							"1936700",
							"1936701",
							"1936702",
							"1936703",
							"1936933",
							"1936936",
							"1937474",
							"1937475",
							"1937476",
							"1937477",
							"1937479",
							"1937480",
							"1937481",
							"1937482",
							"1937483",
							"1969518"
						],
						"blocked": [
							{
								"bug_id": "1919196",
								"error": "NotPermitted"
							},
							{
								"bug_id": "1937052",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2021:4399",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14846426",
								"comment_count": "0",
								"who": {
									"text": "msiddiqu"
								},
								"bug_when": "2021-03-05 19:20:02 +0000",
								"thetext": "Running `pydoc -p` allows other local users to extract arbitrary files"
							},
							{
								"isprivate": "0",
								"commentid": "14846906",
								"comment_count": "1",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-03-05 21:50:00 +0000",
								"thetext": "Related upstream PRs:\n\nhttps://github.com/python/cpython/pull/24337\nhttps://github.com/python/cpython/pull/24285"
							},
							{
								"isprivate": "0",
								"commentid": "14857175",
								"comment_count": "11",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-03-10 00:11:13 +0000",
								"thetext": "Not sure why it's not mentioned upstream, but in Python 3.7.0 alpha 1+, pydoc has the -n command[1][2]. So using -n can additionally expose this to adjacent attackers rather than just local attackers.\n\n1. https://bugs.python.org/issue31128\n2. https://github.com/python/cpython/commit/6a396c9807b1674a24e240731f18e20de97117a5"
							},
							{
								"isprivate": "0",
								"commentid": "14857211",
								"comment_count": "13",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-03-10 00:32:09 +0000",
								"thetext": "Statement:\n\nRed Hat Quay from version 3.4 uses Python from Red Hat Enterprise Linux RPM repositories and therefore may receive an update for this issue in a future release. Earlier versions of Red Hat Quay will not receive an patch for this issue.\n\nPython 2.x.x as shipped in any Red Hat product is not affected. This flaw is out of support scope for python3 as shipped with Red Hat Enterprise Linux 7. For more information about Red Hat Enterprise Linux support scope, please see https://access.redhat.com/support/policy/updates/errata/ ."
							},
							{
								"isprivate": "0",
								"commentid": "14860081",
								"comment_count": "16",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-03-10 17:53:06 +0000",
								"thetext": "There is not yet a fix in an upstream Python release at this time."
							},
							{
								"isprivate": "0",
								"commentid": "14860124",
								"comment_count": "17",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-03-10 18:00:58 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937475]\nAffects: fedora-33 [bug 1937483]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937476]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1937474]\nAffects: fedora-32 [bug 1937477]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937479]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937480]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937481]\n\n\nCreated python39 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937482]"
							},
							{
								"isprivate": "0",
								"commentid": "14947762",
								"comment_count": "19",
								"who": {
									"text": "tcullum",
									"name": "Todd Cullum"
								},
								"bug_when": "2021-04-08 22:03:52 +0000",
								"thetext": "Mitigation:\n\nUse the console (no argument needed) or HTML file (-w argument) output to generate docs rather than the HTTP server options. Put differently, do not use the -p or -n options of pydoc."
							},
							{
								"isprivate": "0",
								"commentid": "15415647",
								"comment_count": "23",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-08-24 08:09:10 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n\nVia RHSA-2021:3254 https://access.redhat.com/errata/RHSA-2021:3254"
							},
							{
								"isprivate": "0",
								"commentid": "15417479",
								"comment_count": "24",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2021-08-24 15:34:58 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2021-3426"
							},
							{
								"isprivate": "0",
								"commentid": "15667044",
								"comment_count": "25",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-11-09 17:27:06 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4160 https://access.redhat.com/errata/RHSA-2021:4160"
							},
							{
								"isprivate": "0",
								"commentid": "15667064",
								"comment_count": "26",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-11-09 17:28:15 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4162 https://access.redhat.com/errata/RHSA-2021:4162"
							},
							{
								"isprivate": "0",
								"commentid": "15668236",
								"comment_count": "27",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2021-11-09 18:37:04 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4399 https://access.redhat.com/errata/RHSA-2021:4399"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14860120",
						"comment_count": "0",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 18:00:38 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-32.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message."
					},
					{
						"isprivate": "0",
						"commentid": "14860121",
						"comment_count": "1",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 18:00:40 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1935913,1937482\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14943010",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2021-04-07 16:43:47 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python39/pull-request/71"
					},
					{
						"isprivate": "0",
						"commentid": "14944051",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-04-07 22:06:04 +0000",
						"thetext": "FEDORA-2021-a311bf10d4 has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2021-a311bf10d4"
					},
					{
						"isprivate": "0",
						"commentid": "14947690",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-04-08 21:26:51 +0000",
						"thetext": "FEDORA-2021-a311bf10d4 has been pushed to the Fedora 32 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-a311bf10d4`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-a311bf10d4\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14952312",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2021-04-10 23:19:12 +0000",
						"thetext": "FEDORA-2021-a311bf10d4 has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python39-3.9.4-1.fc32",
			"release_id": 35,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "aarch64"
					},
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "aarch64"
					},
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "armv7hl"
					},
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "armv7hl"
					},
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "i686"
					},
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "i686"
					},
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "ppc64le"
					},
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "ppc64le"
					},
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "s390x"
					},
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "s390x"
					},
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python39-debuginfo",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "x86_64"
					},
					{
						"name": "python39-debugsource",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "x86_64"
					},
					{
						"name": "python39",
						"version": "3.9.4",
						"release": "1.fc32",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1976824,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2021-04-07 22:06:02",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1976825,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-04-07 22:06:03",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1976826,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2021-04-07 22:06:03",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1976859,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-04-07 22:57:14",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1978705,
			"text": "This update has been pushed to testing.",
			"timestamp": "2021-04-08 21:27:16",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1935913,
						"parent": true,
						"security": true,
						"title": "CVE-2021-3426 python: information disclosure via pydoc"
					},
					"bug_id": 1935913,
					"comment_id": 1979553
				},
				{
					"bug": {
						"bug_id": 1937482,
						"security": true,
						"title": "CVE-2021-3426 python39: python: information disclosure via pydoc [fedora-32]"
					},
					"bug_id": 1937482,
					"comment_id": 1979553
				}
			],
			"id": 1979553,
			"karma": 1,
			"timestamp": "2021-04-09 14:58:05",
			"update_id": 297884,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
				"email": "geraldo.simiao.kutz@gmail.com",
				"groups": [
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "fedora-br"
					},
					{
						"name": "advocates"
					},
					{
						"name": "respins-sig"
					}
				],
				"id": 5881,
				"name": "geraldosimiao",
				"openid": "geraldosimiao.id.fedoraproject.org"
			},
			"user_id": 5881
		},
		{
			"id": 1979554,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2021-04-09 14:58:05",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1980883,
			"text": "This update has been pushed to stable.",
			"timestamp": "2021-04-10 23:19:20",
			"update_id": 297884,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2021-04-10 23:18:57",
	"date_stable": "2021-04-10 23:18:57",
	"date_submitted": "2021-04-07 22:06:02",
	"date_testing": "2021-04-08 21:26:09",
	"karma": 1,
	"meets_testing_requirements": true,
	"notes": "Update Python to 3.9.4. [Changelog](https://docs.python.org/release/3.9.4/whatsnew/changelog.html#changelog). Contains security fix for CVE-2021-3426.\n",
	"pushed": true,
	"release": {
		"branch": "f32",
		"candidate_tag": "f32-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f32",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 32",
		"mail_template": "fedora_errata_template",
		"name": "F32",
		"override_tag": "f32-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f32-signing-pending",
		"pending_stable_tag": "f32-updates-pending",
		"pending_testing_tag": "f32-updates-testing-pending",
		"stable_tag": "f32-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f32-updates-testing",
		"version": "32"
	},
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python39-3.9.4-1.fc32",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2021-a311bf10d4",
	"unstable_karma": -1,
	"updateid": "FEDORA-2021-a311bf10d4",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "9c2018a977dbfb5b9e3b11161930e1941e60ccb9"
}
