{
	"alias": "FEDORA-2020-6941c0a65b",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1874492,
			"parent": true,
			"security": true,
			"title": "CVE-2020-24584 django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+",
			"bugzilla": {
				"bug_id": "1874492",
				"alias": "CVE-2020-24584",
				"creation_ts": "2020-09-01 13:39:43 +0000",
				"short_desc": "CVE-2020-24584 django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+",
				"delta_ts": "2021-12-14 18:47:58 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1874493",
					"1874495",
					"1874494",
					"1874496"
				],
				"blocked": [
					{
						"bug_id": "1874498",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14249476",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-09-01 13:39:43 +0000",
						"thetext": "On Python 3.7+, the intermediate-level directories of the file system cache had the system's standard umask rather than ``0o077`` (no group or others permissions).\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/sep/01/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "14249485",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-09-01 13:40:23 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1874495]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1874493]\nAffects: fedora-all [bug 1874494]\nAffects: openstack-rdo [bug 1874496]"
					},
					{
						"isprivate": "0",
						"commentid": "14255401",
						"comment_count": "2",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2020-09-03 07:23:14 +0000",
						"thetext": "Upstream fix:\nhttps://github.com/django/django/commit/1853724acaf17ed7414d54c7d2b5563a25025a71"
					},
					{
						"isprivate": "0",
						"commentid": "14324017",
						"comment_count": "7",
						"who": {
							"text": "amctagga",
							"name": "Sage McTaggart"
						},
						"bug_when": "2020-09-25 21:30:01 +0000",
						"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/sep/01/security-releases"
					},
					{
						"isprivate": "0",
						"commentid": "14326953",
						"comment_count": "9",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2020-09-28 13:10:29 +0000",
						"thetext": "Statement:\n\nThis flaw can only be triggered in Django by using Python version 3.7 and newer. While the flawed package is shipped with the below Red Hat products, the flaw cannot be activated without manually updating Python to a newer release. This change would break many features and is an unsupported configuration.\n\n* Red Hat OpenStack Platform versions 15 and 16 ship Python 3.6.8; 10 and 13 ship Python 2.X.\n* Red Hat Ceph Storage 2 and 3 uses Python 2.X\n* Red Hat Gluster Storage 3 uses Python 2.X"
					},
					{
						"isprivate": "0",
						"commentid": "14327218",
						"comment_count": "10",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2020-09-28 14:40:57 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-24584"
					}
				]
			}
		},
		{
			"bug_id": 1874494,
			"security": true,
			"title": "CVE-2020-24584 python-django: django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+ [fedora-all]",
			"bugzilla": {
				"bug_id": "1874494",
				"creation_ts": "2020-09-01 13:40:00 +0000",
				"short_desc": "CVE-2020-24584 python-django: django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+ [fedora-all]",
				"delta_ts": "2020-09-25 16:44:49 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1874492",
						"alias": "CVE-2020-24584",
						"creation_ts": "2020-09-01 13:39:43 +0000",
						"short_desc": "CVE-2020-24584 django: permission escalation in intermediate-level directories of the file system cache on Python 3.7+",
						"delta_ts": "2021-12-14 18:47:58 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1874493",
							"1874495",
							"1874494",
							"1874496"
						],
						"blocked": [
							{
								"bug_id": "1874498",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14249476",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-09-01 13:39:43 +0000",
								"thetext": "On Python 3.7+, the intermediate-level directories of the file system cache had the system's standard umask rather than ``0o077`` (no group or others permissions).\n\nReference:\nhttps://www.djangoproject.com/weblog/2020/sep/01/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "14249485",
								"comment_count": "1",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2020-09-01 13:40:23 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1874495]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-all [bug 1874493]\nAffects: fedora-all [bug 1874494]\nAffects: openstack-rdo [bug 1874496]"
							},
							{
								"isprivate": "0",
								"commentid": "14255401",
								"comment_count": "2",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-09-03 07:23:14 +0000",
								"thetext": "Upstream fix:\nhttps://github.com/django/django/commit/1853724acaf17ed7414d54c7d2b5563a25025a71"
							},
							{
								"isprivate": "0",
								"commentid": "14324017",
								"comment_count": "7",
								"who": {
									"text": "amctagga",
									"name": "Sage McTaggart"
								},
								"bug_when": "2020-09-25 21:30:01 +0000",
								"thetext": "External References:\n\nhttps://www.djangoproject.com/weblog/2020/sep/01/security-releases"
							},
							{
								"isprivate": "0",
								"commentid": "14326953",
								"comment_count": "9",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2020-09-28 13:10:29 +0000",
								"thetext": "Statement:\n\nThis flaw can only be triggered in Django by using Python version 3.7 and newer. While the flawed package is shipped with the below Red Hat products, the flaw cannot be activated without manually updating Python to a newer release. This change would break many features and is an unsupported configuration.\n\n* Red Hat OpenStack Platform versions 15 and 16 ship Python 3.6.8; 10 and 13 ship Python 2.X.\n* Red Hat Ceph Storage 2 and 3 uses Python 2.X\n* Red Hat Gluster Storage 3 uses Python 2.X"
							},
							{
								"isprivate": "0",
								"commentid": "14327218",
								"comment_count": "10",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2020-09-28 14:40:57 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-24584"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14249480",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-09-01 13:40:00 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "14249481",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2020-09-01 13:40:03 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1874492,1874494\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14257018",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-03 15:22:54 +0000",
						"thetext": "FEDORA-2020-9c6b391162 has been submitted as an update to Fedora 33. https://bodhi.fedoraproject.org/updates/FEDORA-2020-9c6b391162"
					},
					{
						"isprivate": "0",
						"commentid": "14257108",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-03 15:46:01 +0000",
						"thetext": "FEDORA-2020-94407454d7 has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-94407454d7"
					},
					{
						"isprivate": "0",
						"commentid": "14257693",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-03 18:10:30 +0000",
						"thetext": "FEDORA-2020-9c6b391162 has been pushed to the Fedora 33 testing repository.\nIn short time you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-9c6b391162`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-9c6b391162\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14257754",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-03 18:28:50 +0000",
						"thetext": "FEDORA-2020-6941c0a65b has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2020-6941c0a65b"
					},
					{
						"isprivate": "0",
						"commentid": "14260299",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-04 15:12:38 +0000",
						"thetext": "FEDORA-2020-6941c0a65b has been pushed to the Fedora 31 testing repository.\nIn short time you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-6941c0a65b`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-6941c0a65b\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14260390",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-04 15:27:44 +0000",
						"thetext": "FEDORA-2020-94407454d7 has been pushed to the Fedora 32 testing repository.\nIn short time you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-94407454d7`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-94407454d7\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14282155",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-12 16:33:27 +0000",
						"thetext": "FEDORA-2020-94407454d7 has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14282190",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-12 16:37:03 +0000",
						"thetext": "FEDORA-2020-6941c0a65b has been pushed to the Fedora 31 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "14322872",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-09-25 16:44:49 +0000",
						"thetext": "FEDORA-2020-9c6b391162 has been pushed to the Fedora 33 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-django-2.2.16-1.fc31",
			"release_id": 33,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-django",
						"version": "2.2.16",
						"release": "1.fc31",
						"arch": "noarch"
					},
					{
						"name": "python-django-bash-completion",
						"version": "2.2.16",
						"release": "1.fc31",
						"arch": "noarch"
					},
					{
						"name": "python3-django-doc",
						"version": "2.2.16",
						"release": "1.fc31",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-django",
						"version": "2.2.16",
						"release": "1.fc31",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1604652,
			"text": "This update has been submitted for testing by mrunge. ",
			"timestamp": "2020-09-03 18:28:46",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1604653,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-09-03 18:28:46",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1604654,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2020-09-03 18:28:46",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1604663,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-09-03 18:34:11",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1606423,
			"text": "This update has been pushed to testing.",
			"timestamp": "2020-09-04 15:13:14",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1618544,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2020-09-11 15:12:32",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1618545,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2020-09-11 15:12:33",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1621807,
			"text": "This update has been pushed to stable.",
			"timestamp": "2020-09-12 16:37:26",
			"update_id": 238526,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2020-09-12 16:36:51",
	"date_stable": "2020-09-12 16:36:51",
	"date_submitted": "2020-09-03 18:28:46",
	"date_testing": "2020-09-04 15:12:21",
	"meets_testing_requirements": true,
	"notes": "update to 2.2.16, CVE-2020-24583, CVE-2020-24584",
	"pushed": true,
	"release": {
		"branch": "f31",
		"candidate_tag": "f31-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f31",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 31",
		"mail_template": "fedora_errata_template",
		"name": "F31",
		"override_tag": "f31-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f31-signing-pending",
		"pending_stable_tag": "f31-updates-pending",
		"pending_testing_tag": "f31-updates-testing-pending",
		"stable_tag": "f31-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f31-updates-testing",
		"version": "31"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-django-2.2.16-1.fc31",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2020-6941c0a65b",
	"unstable_karma": -3,
	"updateid": "FEDORA-2020-6941c0a65b",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/c626775cb5584b1a49ea4a5cabb248e54e49c09185ebbf4fbce72265255956f0?s=24&d=retro",
		"email": "mrunge@redhat.com",
		"groups": [
			{
				"name": "proventesters"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "centosproject-email-aliases"
			},
			{
				"name": "gitovirt"
			},
			{
				"name": "sig-cloud"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "gitnodejs-packaging"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "sig-extras"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "sig-opstools"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sig-messaging"
			},
			{
				"name": "openstack-sig"
			}
		],
		"id": 189,
		"name": "mrunge",
		"openid": "mrunge.id.fedoraproject.org"
	},
	"version_hash": "37dbd5e1770bb670abf668f6b3d76fdbc527c765"
}
