{
	"alias": "FEDORA-2023-a53ab7c969",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2072447,
			"parent": true,
			"security": true,
			"title": "CVE-2022-28346 Django: SQL injection in QuerySet.annotate(),aggregate() and extra()",
			"bugzilla": {
				"bug_id": "2072447",
				"alias": "CVE-2022-28346",
				"creation_ts": "2022-04-06 10:47:30 +0000",
				"short_desc": "CVE-2022-28346 Django: SQL injection in QuerySet.annotate(),aggregate() and extra()",
				"delta_ts": "2022-12-07 20:27:29 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"2074856",
					"2074857",
					"2074859",
					"2074860",
					"2074858",
					"2074861",
					"2074862",
					"2074863",
					"2074864",
					"2074865",
					"2074866",
					"2074867",
					"2074869",
					"2074871",
					"2074872",
					"2074874",
					"2074876",
					"2074878",
					"2074879",
					"2074881",
					"2074954",
					"2074955",
					"2074956",
					"2074957",
					"2074958",
					"2074959",
					"2074960",
					"2074961",
					"2074962",
					"2074963",
					"2074964",
					"2074965",
					"2075662",
					"2075663",
					"2075919",
					"2075920",
					"2075921",
					"2076571",
					"2076572",
					"2076573",
					"2085188",
					"2102716",
					"2102717",
					"2102718"
				],
				"blocked": [
					{
						"bug_id": "2072463",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2022:8872",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16121662",
						"comment_count": "0",
						"who": {
							"text": "vinair",
							"name": "Vipul Nair"
						},
						"bug_when": "2022-04-06 10:47:30 +0000",
						"thetext": "``QuerySet.annotate()`, ``aggregate()``, and ``extra()`` methods were\nsubject\nto SQL injection in column aliases, using a suitably crafted dictionary,\nwith\ndictionary expansion, as the ``**kwargs`` passed to these methods.\n\nThis issue has High severity, according to the Django security policy [1]."
					},
					{
						"isprivate": "0",
						"commentid": "16140994",
						"comment_count": "2",
						"who": {
							"text": "vinair",
							"name": "Vipul Nair"
						},
						"bug_when": "2022-04-13 09:27:11 +0000",
						"thetext": "Created autotest-framework tracking bugs for this issue:\n\nAffects: epel-all [bug 2074857]\n\n\nCreated graphite-web tracking bugs for this issue:\n\nAffects: epel-all [bug 2074858]\n\n\nCreated netbox tracking bugs for this issue:\n\nAffects: epel-all [bug 2074856]\nAffects: fedora-all [bug 2074862]\n\n\nCreated python-django-ajax-selects tracking bugs for this issue:\n\nAffects: epel-all [bug 2074859]\n\n\nCreated python-django-helpdesk tracking bugs for this issue:\n\nAffects: epel-all [bug 2074860]\n\n\nCreated python-django-nose tracking bugs for this issue:\n\nAffects: fedora-all [bug 2074863]\n\n\nCreated python-django-uuslug tracking bugs for this issue:\n\nAffects: fedora-all [bug 2074864]\n\n\nCreated zezere tracking bugs for this issue:\n\nAffects: epel-all [bug 2074861]\nAffects: fedora-all [bug 2074865]"
					},
					{
						"isprivate": "0",
						"commentid": "16377174",
						"comment_count": "12",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-06-22 16:06:11 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 16.2\n\nVia RHSA-2022:5115 https://access.redhat.com/errata/RHSA-2022:5115"
					},
					{
						"isprivate": "0",
						"commentid": "16378103",
						"comment_count": "13",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2022-06-22 21:06:28 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-28346"
					},
					{
						"isprivate": "0",
						"commentid": "16415041",
						"comment_count": "17",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-05 14:27:43 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.11 for RHEL 7\n  Red Hat Satellite 6.11 for RHEL 8\n\nVia RHSA-2022:5498 https://access.redhat.com/errata/RHSA-2022:5498"
					},
					{
						"isprivate": "0",
						"commentid": "16472081",
						"comment_count": "18",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-19 13:03:33 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2022:5602 https://access.redhat.com/errata/RHSA-2022:5602"
					},
					{
						"isprivate": "0",
						"commentid": "16488756",
						"comment_count": "19",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-25 18:13:40 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Ansible Automation Platform 2.1 for RHEL 8\n\nVia RHSA-2022:5702 https://access.redhat.com/errata/RHSA-2022:5702"
					},
					{
						"isprivate": "0",
						"commentid": "16488952",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-25 19:51:40 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Automation Hub 4.2 for RHEL 8\n  Red Hat Automation Hub 4.2 for RHEL 7\n\nVia RHSA-2022:5703 https://access.redhat.com/errata/RHSA-2022:5703"
					},
					{
						"isprivate": "0",
						"commentid": "16859422",
						"comment_count": "21",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-12-07 20:27:25 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenStack Platform 16.1\n\nVia RHSA-2022:8872 https://access.redhat.com/errata/RHSA-2022:8872"
					}
				]
			}
		},
		{
			"bug_id": 2072459,
			"parent": true,
			"security": true,
			"title": "CVE-2022-28347 Django: SQL injection via QuerySet.explain(options) on PostgreSQL",
			"bugzilla": {
				"bug_id": "2072459",
				"alias": "CVE-2022-28347",
				"creation_ts": "2022-04-06 11:12:57 +0000",
				"short_desc": "CVE-2022-28347 Django: SQL injection via QuerySet.explain(options) on PostgreSQL",
				"delta_ts": "2023-03-15 08:03:06 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"2074868",
					"2074870",
					"2074875",
					"2074877",
					"2074873",
					"2074880",
					"2074882",
					"2074883",
					"2074884",
					"2074885",
					"2074904",
					"2074905",
					"2074906",
					"2074908",
					"2074909",
					"2074910",
					"2074911",
					"2074912",
					"2074913",
					"2074914",
					"2074969",
					"2074970",
					"2074971",
					"2074972",
					"2074973",
					"2074974",
					"2074975",
					"2074976",
					"2074977",
					"2074978",
					"2074979",
					"2074980",
					"2075664",
					"2075665",
					"2075922",
					"2075923",
					"2075924",
					"2076568",
					"2076569",
					"2076570",
					"2085188",
					"2102713",
					"2102714",
					"2102715"
				],
				"blocked": [
					{
						"bug_id": "2072463",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2022:5703",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16121750",
						"comment_count": "0",
						"who": {
							"text": "vinair",
							"name": "Vipul Nair"
						},
						"bug_when": "2022-04-06 11:12:57 +0000",
						"thetext": "``QuerySet.explain()`` method was subject to SQL injection in option names,\nusing a suitably crafted dictionary, with dictionary expansion, as the\n``**options`` argument.\n\nThis issue has High severity, according to the Django security policy [1]."
					},
					{
						"isprivate": "0",
						"commentid": "16141023",
						"comment_count": "2",
						"who": {
							"text": "vinair",
							"name": "Vipul Nair"
						},
						"bug_when": "2022-04-13 09:28:11 +0000",
						"thetext": "Created autotest-framework tracking bugs for this issue:\n\nAffects: epel-all [bug 2074870]\n\n\nCreated graphite-web tracking bugs for this issue:\n\nAffects: epel-all [bug 2074873]\n\n\nCreated netbox tracking bugs for this issue:\n\nAffects: epel-all [bug 2074868]\nAffects: fedora-all [bug 2074882]\n\n\nCreated python-django-ajax-selects tracking bugs for this issue:\n\nAffects: epel-all [bug 2074875]\n\n\nCreated python-django-helpdesk tracking bugs for this issue:\n\nAffects: epel-all [bug 2074877]\n\n\nCreated python-django-nose tracking bugs for this issue:\n\nAffects: fedora-all [bug 2074883]\n\n\nCreated python-django-uuslug tracking bugs for this issue:\n\nAffects: fedora-all [bug 2074884]\n\n\nCreated zezere tracking bugs for this issue:\n\nAffects: epel-all [bug 2074880]\nAffects: fedora-all [bug 2074885]"
					},
					{
						"isprivate": "0",
						"commentid": "16415042",
						"comment_count": "17",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-05 14:27:47 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.11 for RHEL 7\n  Red Hat Satellite 6.11 for RHEL 8\n\nVia RHSA-2022:5498 https://access.redhat.com/errata/RHSA-2022:5498"
					},
					{
						"isprivate": "0",
						"commentid": "16472082",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-19 13:03:34 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2022:5602 https://access.redhat.com/errata/RHSA-2022:5602"
					},
					{
						"isprivate": "0",
						"commentid": "16488757",
						"comment_count": "21",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-25 18:13:41 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Ansible Automation Platform 2.1 for RHEL 8\n\nVia RHSA-2022:5702 https://access.redhat.com/errata/RHSA-2022:5702"
					},
					{
						"isprivate": "0",
						"commentid": "16488953",
						"comment_count": "22",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-25 19:51:46 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Automation Hub 4.2 for RHEL 8\n  Red Hat Automation Hub 4.2 for RHEL 7\n\nVia RHSA-2022:5703 https://access.redhat.com/errata/RHSA-2022:5703"
					},
					{
						"isprivate": "0",
						"commentid": "16595107",
						"comment_count": "23",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2022-08-30 12:25:51 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-28347"
					}
				]
			}
		},
		{
			"bug_id": 2102896,
			"parent": true,
			"security": true,
			"title": "CVE-2022-34265 python-django: Potential SQL injection via Trunc(kind) and Extract(lookup_name) arguments",
			"bugzilla": {
				"bug_id": "2102896",
				"alias": "CVE-2022-34265",
				"creation_ts": "2022-06-30 23:30:14 +0000",
				"short_desc": "CVE-2022-34265 python-django: Potential SQL injection via Trunc(kind) and Extract(lookup_name) arguments",
				"delta_ts": "2022-11-16 13:32:23 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"2104869",
					"2104870",
					"2104871",
					"2104872",
					"2105184",
					"2105185",
					"2105186",
					"2105187",
					"2105188",
					"2105189",
					"2105190",
					"2105191",
					"2105192",
					"2105193",
					"2105194",
					"2105195",
					"2105196",
					"2105197",
					"2105198",
					"2105199",
					"2105207",
					"2105209",
					"2105210",
					"2105212",
					"2105214",
					"2105215",
					"2105216",
					"2109822"
				],
				"blocked": [
					{
						"bug_id": "2102892",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2022:8506",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16405065",
						"comment_count": "0",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2022-06-30 23:30:14 +0000",
						"thetext": "In Django versions 4.0, 4.1 (beta), and 3.2, `Trunc()` and `Extract()` database functions were subject to SQL\ninjection if untrusted data was used as a `lookup_name`/`kind` value. Applications that constrain the lookup name and kind choice to a known safe\nlist are unaffected."
					},
					{
						"isprivate": "0",
						"commentid": "16424687",
						"comment_count": "9",
						"who": {
							"text": "ahanwate",
							"name": "Avinash Hanwate"
						},
						"bug_when": "2022-07-08 09:12:40 +0000",
						"thetext": "Created python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 2105207]\nAffects: epel-8 [bug 2105210]\nAffects: fedora-35 [bug 2105214]\nAffects: fedora-36 [bug 2105215]\nAffects: openstack-rdo [bug 2105216]\n\n\nCreated python-django16 tracking bugs for this issue:\n\nAffects: epel-7 [bug 2105209]\n\n\nCreated python-django3 tracking bugs for this issue:\n\nAffects: epel-8 [bug 2105212]"
					},
					{
						"isprivate": "0",
						"commentid": "16495909",
						"comment_count": "14",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-07-27 14:47:28 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2022:5738 https://access.redhat.com/errata/RHSA-2022:5738"
					},
					{
						"isprivate": "0",
						"commentid": "16595972",
						"comment_count": "15",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2022-08-30 15:55:50 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-34265"
					},
					{
						"isprivate": "0",
						"commentid": "16795812",
						"comment_count": "16",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2022-11-16 13:32:20 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.12 for RHEL 8\n\nVia RHSA-2022:8506 https://access.redhat.com/errata/RHSA-2022:8506"
					}
				]
			}
		},
		{
			"bug_id": 2136130,
			"parent": true,
			"security": true,
			"title": "CVE-2022-41323 python-django: Potential denial-of-service vulnerability in internationalized URLs",
			"bugzilla": {
				"bug_id": "2136130",
				"alias": "CVE-2022-41323",
				"creation_ts": "2022-10-19 12:08:20 +0000",
				"short_desc": "CVE-2022-41323 python-django: Potential denial-of-service vulnerability in internationalized URLs",
				"delta_ts": "2023-05-03 13:20:01 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2136879",
					"2136134",
					"2136135",
					"2136136",
					"2136137",
					"2136138",
					"2136139",
					"2138114"
				],
				"blocked": [
					{
						"bug_id": "2132135",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2023:2097",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16718233",
						"comment_count": "0",
						"who": {
							"text": "ybuenos"
						},
						"bug_when": "2022-10-19 12:08:20 +0000",
						"thetext": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.\n\nhttps://docs.djangoproject.com/en/4.0/releases/security/\nhttps://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924\nhttps://www.djangoproject.com/weblog/2022/oct/04/security-releases/\nhttps://groups.google.com/forum/#!forum/django-announce"
					},
					{
						"isprivate": "0",
						"commentid": "16718287",
						"comment_count": "1",
						"who": {
							"text": "ybuenos"
						},
						"bug_when": "2022-10-19 12:15:52 +0000",
						"thetext": "Created python-django tracking bugs for this issue:\n\nAffects: fedora-35 [bug 2136135]\nAffects: fedora-36 [bug 2136136]\n\n\nCreated python-django3 tracking bugs for this issue:\n\nAffects: epel-8 [bug 2136134]\nAffects: fedora-36 [bug 2136137]"
					},
					{
						"isprivate": "0",
						"commentid": "17042326",
						"comment_count": "18",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-02-13 12:00:33 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2023:0742 https://access.redhat.com/errata/RHSA-2023:0742"
					},
					{
						"isprivate": "0",
						"commentid": "17047282",
						"comment_count": "19",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2023-02-14 22:42:08 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-41323"
					},
					{
						"isprivate": "0",
						"commentid": "17238771",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-03 13:19:57 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.13 for RHEL 8\n\nVia RHSA-2023:2097 https://access.redhat.com/errata/RHSA-2023:2097"
					}
				]
			}
		},
		{
			"bug_id": 2166457,
			"parent": true,
			"security": true,
			"title": "CVE-2023-23969 python-django: Potential denial-of-service via Accept-Language headers",
			"bugzilla": {
				"bug_id": "2166457",
				"alias": "CVE-2023-23969",
				"creation_ts": "2023-02-01 21:07:54 +0000",
				"short_desc": "CVE-2023-23969 python-django: Potential denial-of-service via Accept-Language headers",
				"delta_ts": "2023-05-03 23:15:28 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2167738",
					"2167739",
					"2167740",
					"2167741",
					"2168510",
					"2168511",
					"2168512",
					"2168513"
				],
				"blocked": [
					{
						"bug_id": "2166455",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2023:2101",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "17016768",
						"comment_count": "0",
						"who": {
							"text": "askrabec",
							"name": "Anten Skrabec"
						},
						"bug_when": "2023-02-01 21:07:54 +0000",
						"thetext": "The parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if large header values are sent."
					},
					{
						"isprivate": "0",
						"commentid": "17238782",
						"comment_count": "7",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-03 13:20:24 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.13 for RHEL 8\n\nVia RHSA-2023:2097 https://access.redhat.com/errata/RHSA-2023:2097"
					},
					{
						"isprivate": "0",
						"commentid": "17239400",
						"comment_count": "8",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-03 14:55:58 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2023:2101 https://access.redhat.com/errata/RHSA-2023:2101"
					},
					{
						"isprivate": "0",
						"commentid": "17240273",
						"comment_count": "9",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2023-05-03 23:15:25 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2023-23969"
					}
				]
			}
		},
		{
			"bug_id": 2169402,
			"parent": true,
			"security": true,
			"title": "CVE-2023-24580 python-django: Potential denial-of-service vulnerability in file uploads",
			"bugzilla": {
				"bug_id": "2169402",
				"alias": "CVE-2023-24580",
				"creation_ts": "2023-02-13 14:21:15 +0000",
				"short_desc": "CVE-2023-24580 python-django: Potential denial-of-service vulnerability in file uploads",
				"delta_ts": "2023-08-21 17:04:53 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2169424",
					"2169431",
					"2169644",
					"2169645",
					"2169646",
					"2169647",
					"2169742",
					"2169743",
					"2169744",
					"2169745",
					"2169746",
					"2172889"
				],
				"blocked": [
					{
						"bug_id": "2167773",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2023:4692",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "17042705",
						"comment_count": "0",
						"who": {
							"text": "ybuenos"
						},
						"bug_when": "2023-02-13 14:21:15 +0000",
						"thetext": "Passing certain inputs to multipart forms could result in too many open files or memory exhaustion, and provide a potential vector for a denial-of-service attack."
					},
					{
						"isprivate": "0",
						"commentid": "17046135",
						"comment_count": "7",
						"who": {
							"text": "ybuenos"
						},
						"bug_when": "2023-02-14 14:44:20 +0000",
						"thetext": "Created python-django tracking bugs for this issue:\n\nAffects: fedora-36 [bug 2169743]\nAffects: fedora-37 [bug 2169745]\n\n\nCreated python-django3 tracking bugs for this issue:\n\nAffects: epel-8 [bug 2169742]\nAffects: fedora-36 [bug 2169744]\nAffects: fedora-37 [bug 2169746]"
					},
					{
						"isprivate": "0",
						"commentid": "17238784",
						"comment_count": "11",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-03 13:20:25 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Satellite 6.13 for RHEL 8\n\nVia RHSA-2023:2097 https://access.redhat.com/errata/RHSA-2023:2097"
					},
					{
						"isprivate": "0",
						"commentid": "17239401",
						"comment_count": "12",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-03 14:55:59 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  RHUI 4 for RHEL 8\n\nVia RHSA-2023:2101 https://access.redhat.com/errata/RHSA-2023:2101"
					},
					{
						"isprivate": "0",
						"commentid": "17240276",
						"comment_count": "13",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2023-05-03 23:16:31 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2023-24580"
					},
					{
						"isprivate": "0",
						"commentid": "17553203",
						"comment_count": "14",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-08-21 17:04:50 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Ansible Automation Platform 2.4 for RHEL 8\n  Red Hat Ansible Automation Platform 2.4 for RHEL 9\n\nVia RHSA-2023:4692 https://access.redhat.com/errata/RHSA-2023:4692"
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-django-4.0.10-1.fc38",
			"release_id": 66,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-django-doc",
						"version": "4.0.10",
						"release": "1.fc38",
						"arch": "noarch"
					},
					{
						"name": "python-django-bash-completion",
						"version": "4.0.10",
						"release": "1.fc38",
						"arch": "noarch"
					},
					{
						"name": "python3-django",
						"version": "4.0.10",
						"release": "1.fc38",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-django",
						"version": "4.0.10",
						"release": "1.fc38",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 2993133,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2023-04-19 12:26:37",
			"update_id": 504178,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2993134,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2023-04-19 12:26:37",
			"update_id": 504178,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2993923,
			"text": "This update has been pushed to testing.",
			"timestamp": "2023-04-20 04:30:20",
			"update_id": 504178,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3003211,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2023-04-27 04:31:19",
			"update_id": 504178,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3004687,
			"text": "This update has been pushed to stable.",
			"timestamp": "2023-04-28 02:36:51",
			"update_id": 504178,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2023-04-27 04:31:18",
	"date_pushed": "2023-04-28 02:35:08",
	"date_stable": "2023-04-28 02:35:08",
	"date_submitted": "2023-04-19 12:26:36",
	"date_testing": "2023-04-20 04:29:00",
	"meets_testing_requirements": true,
	"notes": "Security fix for:\n\n - CVE-2023-24580\n - CVE-2023-23969\n - CVE-2022-41323\n - CVE-2022-36359\n - CVE-2022-34265\n - CVE-2022-28346\n - CVE-2022-28347\n\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.3/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.4/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.5/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.6/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.7/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.8/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.9/\nhttps://docs.djangoproject.com/en/4.2/releases/4.0.10/",
	"pushed": true,
	"release": {
		"branch": "f38",
		"candidate_tag": "f38-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f38",
		"eol": "2024-05-14",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 38",
		"mail_template": "fedora_errata_template",
		"name": "F38",
		"override_tag": "f38-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f38-signing-pending",
		"pending_stable_tag": "f38-updates-pending",
		"pending_testing_tag": "f38-updates-testing-pending",
		"stable_tag": "f38-updates",
		"state": "current",
		"testing_repository": "updates-testing",
		"testing_tag": "f38-updates-testing",
		"version": "38"
	},
	"require_testcases": true,
	"severity": "high",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-django-4.0.10-1.fc38",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2023-a53ab7c969",
	"unstable_karma": -3,
	"updateid": "FEDORA-2023-a53ab7c969",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "fesco"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "9e47a65deb58e7091f3e7a16b3c92441fed541f3"
}
