{
	"alias": "FEDORA-2019-243442e600",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1688543,
			"feedback": [
				{
					"bug_id": 1688543,
					"comment": {
						"id": 912220,
						"karma": 1,
						"karma_critpath": 1,
						"timestamp": "2019-03-21 15:33:45",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
							"email": "eugenemah@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedora-hams"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 2935,
							"name": "imabug",
							"openid": "imabug.id.fedoraproject.org"
						},
						"user_id": 2935
					},
					"comment_id": 912220
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 912732,
						"karma": 1,
						"karma_critpath": 1,
						"text": "Works here.",
						"timestamp": "2019-03-22 06:00:25",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1a8afd83231ef5ba905344806ba95b39f2abd77b399b0ee217ec3e6fa30a4825?s=24&d=retro",
							"email": "bojan@rexursive.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 198,
							"name": "bojan",
							"openid": "bojan.id.fedoraproject.org"
						},
						"user_id": 198
					},
					"comment_id": 912732
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 913633,
						"karma": 1,
						"text": "no regressions noted",
						"timestamp": "2019-03-24 10:50:01",
						"update_id": 134462,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/636ff3eea65823b2c7349e36b691fd8c6d48f2a2158242b946762c0a14055425?s=24&d=retro",
							"email": "samoht0-bugzilla@yahoo.com",
							"groups": [
								{
									"name": "ipausers"
								}
							],
							"id": 2998,
							"name": "samoht0",
							"openid": "samoht0.id.fedoraproject.org"
						},
						"user_id": 2998
					},
					"comment_id": 913633
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 913863,
						"karma": 1,
						"karma_critpath": 1,
						"text": "No regressions noted.",
						"timestamp": "2019-03-24 18:16:31",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/e62cb974458dc33fcf2225462b8765e0aadcbbd698560c8f8dad6c3e23d5e47e?s=24&d=retro",
							"email": "dhgutteridge@hotmail.com",
							"groups": [
								{
									"name": "ipausers"
								}
							],
							"id": 194,
							"name": "dhgutteridge",
							"openid": "dhgutteridge.id.fedoraproject.org"
						},
						"user_id": 194
					},
					"comment_id": 913863
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 915440,
						"karma": 1,
						"text": "Works for me!\nCVE-2018-1060, -1061, -2019-5010 aren't easy to reproduce. I checked that the patches are in, not necessarily that the issues are solved.",
						"timestamp": "2019-03-26 10:21:13",
						"update_id": 134265,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/6b6af6e29e5a2f51ca6d5fa2ea27adcefa3a299adf5c59e7f1ddddaf037f7e49?s=24&d=retro",
							"email": "pviktori@redhat.com",
							"groups": [
								{
									"name": "python-sig"
								},
								{
									"name": "packager"
								},
								{
									"name": "python-packagers-sig"
								},
								{
									"name": "pypi-builds"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "gitpython-pytest-beakerlib"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa-docs"
								},
								{
									"name": "modularity-wg"
								},
								{
									"name": "gitpython-pytest-sourceorder"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "gitpython-pytest-multihost"
								}
							],
							"id": 1667,
							"name": "pviktori",
							"openid": "pviktori.id.fedoraproject.org"
						},
						"user_id": 1667
					},
					"comment_id": 915440,
					"karma": 1
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 915442,
						"karma": 1,
						"text": "Works for me!\nCVE-2018-1060, -1061, -2019-5010 aren't easy to reproduce. I checked that the patches are in, not necessarily that the issues are solved.",
						"timestamp": "2019-03-26 10:21:51",
						"update_id": 134265,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/6b6af6e29e5a2f51ca6d5fa2ea27adcefa3a299adf5c59e7f1ddddaf037f7e49?s=24&d=retro",
							"email": "pviktori@redhat.com",
							"groups": [
								{
									"name": "python-sig"
								},
								{
									"name": "packager"
								},
								{
									"name": "python-packagers-sig"
								},
								{
									"name": "pypi-builds"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "gitpython-pytest-beakerlib"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa-docs"
								},
								{
									"name": "modularity-wg"
								},
								{
									"name": "gitpython-pytest-sourceorder"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "gitpython-pytest-multihost"
								}
							],
							"id": 1667,
							"name": "pviktori",
							"openid": "pviktori.id.fedoraproject.org"
						},
						"user_id": 1667
					},
					"comment_id": 915442,
					"karma": 1
				},
				{
					"bug_id": 1688543,
					"comment": {
						"id": 968879,
						"karma": 1,
						"timestamp": "2019-07-04 23:39:54",
						"update_id": 142273,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/d826994e83ce867281f73d85986dd475938841874b75a83a82cdb184f6af8749?s=24&d=retro",
							"email": "rosset.filipe@gmail.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "l10n"
								},
								{
									"name": "cvsl10n"
								},
								{
									"name": "fedora-br"
								}
							],
							"id": 124,
							"name": "filiperosset",
							"openid": "filiperosset.id.fedoraproject.org"
						},
						"user_id": 124
					},
					"comment_id": 968879
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization",
			"bugzilla": {
				"bug_id": "1688543",
				"alias": "CVE-2019-9636",
				"creation_ts": "2019-03-13 23:14:41 +0000",
				"short_desc": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization",
				"delta_ts": "2023-03-24 14:38:03 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"1688544",
					"1688545",
					"1688546",
					"1688547",
					"1688549",
					"1688550",
					"1688552",
					"1689316",
					"1689317",
					"1689318",
					"1689319",
					"1689320",
					"1689321",
					"1689322",
					"1689323",
					"1689324",
					"1689325",
					"1689326",
					"1689327",
					"1689328",
					"1693973",
					"1693974",
					"1693975",
					"1694514",
					"1694515",
					"1694516",
					"1694517",
					"1696755",
					"1716744",
					"1744471",
					"1744472"
				],
				"blocked": [
					{
						"bug_id": "1688554",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2019:3170",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12543157",
						"comment_count": "0",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-03-13 23:14:41 +0000",
						"thetext": "A vulnerability was found in Python 2.7.x through 2.7.16 and 3.x through 3.7.2. An improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization could lead to an Information Disclosure (credentials, cookies, etc. that are cached against a given hostname) in the urllib.parse.urlsplit, urllib.parse.urlparse components. A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly.  \n\n\n\nReferences:\nhttps://bugs.python.org/issue36216\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html\n\nUptream Patch:\nhttps://github.com/python/cpython/pull/12201"
					},
					{
						"isprivate": "0",
						"commentid": "12543175",
						"comment_count": "1",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-03-13 23:15:22 +0000",
						"thetext": "Created python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1688546]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 1688552]\nAffects: fedora-all [bug 1688549]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1688550]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1688547]\nAffects: fedora-29 [bug 1688544]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-28 [bug 1688545]"
					},
					{
						"isprivate": "0",
						"commentid": "12618930",
						"comment_count": "8",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-04-08 12:59:30 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2019:0710 https://access.redhat.com/errata/RHSA-2019:0710"
					},
					{
						"isprivate": "0",
						"commentid": "12643922",
						"comment_count": "26",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-04-16 14:06:00 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n\nVia RHSA-2019:0765 https://access.redhat.com/errata/RHSA-2019:0765"
					},
					{
						"isprivate": "0",
						"commentid": "12659445",
						"comment_count": "30",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-04-23 11:38:55 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:0806 https://access.redhat.com/errata/RHSA-2019:0806"
					},
					{
						"isprivate": "0",
						"commentid": "12677177",
						"comment_count": "34",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-04-29 14:30:29 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:0902 https://access.redhat.com/errata/RHSA-2019:0902"
					},
					{
						"isprivate": "0",
						"commentid": "12704354",
						"comment_count": "36",
						"who": {
							"text": "cstratak",
							"name": "Charalampos Stratakis"
						},
						"bug_when": "2019-05-06 09:31:45 +0000",
						"thetext": "The CVE fix we pushed unfortunately introduced a regression, fixed by https://bugs.python.org/issue36742"
					},
					{
						"isprivate": "0",
						"commentid": "12708013",
						"comment_count": "38",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-05-07 04:19:59 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:0981 https://access.redhat.com/errata/RHSA-2019:0981"
					},
					{
						"isprivate": "0",
						"commentid": "12708042",
						"comment_count": "39",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-05-07 04:21:57 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:0997 https://access.redhat.com/errata/RHSA-2019:0997"
					},
					{
						"isprivate": "0",
						"commentid": "12752203",
						"comment_count": "40",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-05-20 07:53:20 +0000",
						"thetext": "This flaw also affects the versions of python as shipped with Red Hat Enterprise Linux 5 and 6, which are, respectively, python 2.4 and 2.6."
					},
					{
						"isprivate": "0",
						"commentid": "12802636",
						"comment_count": "42",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-03 14:51:50 +0000",
						"thetext": "The flaw was reproduced both on python 2.4 shipped with Red Hat Enterprise Linux 5 and on python 2.6 shipped with Red Hat Enterprise Linux 6."
					},
					{
						"isprivate": "0",
						"commentid": "12802660",
						"comment_count": "43",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-03 15:01:36 +0000",
						"thetext": "This flaw affects applications that process untrusted URLs and store credentials, cookies or other kind of information based on the domain name of the URL, when encoded with Punycode/Internationalizing Domain Names in Applications (IDNA), more precisely the netloc component returned by urlparse()/urlsplit(). Assuming an application has cookies stored for the netloc \"redhat.com\", an attacker may construct a URL that, when encoded with IDNA and parsed through urlparse()/urlsplit() would indicate \"redhat.com\" as netloc, even though the connection would be made to the attacker-controlled host, possibly leaking the information that were associated with \"redhat.com\"."
					},
					{
						"isprivate": "0",
						"commentid": "12802665",
						"comment_count": "45",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-03 15:02:21 +0000",
						"thetext": "External References:\n\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html"
					},
					{
						"isprivate": "0",
						"commentid": "12806577",
						"comment_count": "48",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-04 07:44:02 +0000",
						"thetext": "netloc is the part of a URL that includes <user>:<password>@<host>:<port>.\n\nSee https://tools.ietf.org/html/rfc1808.html#section-2.1 for more information about netloc."
					},
					{
						"isprivate": "0",
						"commentid": "12812019",
						"comment_count": "50",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-05 10:23:25 +0000",
						"thetext": "In reply to comment #36:\n> The CVE fix we pushed unfortunately introduced a regression, fixed by\n> https://bugs.python.org/issue36742\n\nThe initial fix for this regression can be found at https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3.\nHowever, alone it would re-introduce this vulnerability, CVE-2019-9636, thus it requires https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete."
					},
					{
						"isprivate": "0",
						"commentid": "12815632",
						"comment_count": "53",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-06 09:19:11 +0000",
						"thetext": "In reply to comment #50:\n> In reply to comment #36:\n> > The CVE fix we pushed unfortunately introduced a regression, fixed by\n> > https://bugs.python.org/issue36742\n> \n> The initial fix for this regression can be found at\n> https://github.com/python/cpython/commit/\n> d537ab0ff9767ef024f26246899728f0116b1ec3.\n> However, alone it would re-introduce this vulnerability, CVE-2019-9636, thus\n> it requires\n> https://github.com/python/cpython/commit/\n> 8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete.\n\nReference:\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization2.html"
					},
					{
						"isprivate": "0",
						"commentid": "12825076",
						"comment_count": "54",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-10 07:56:45 +0000",
						"thetext": "CVE-2019-10160 has been assigned to this security regression.In reply to comment #50:\n> In reply to comment #36:\n> > The CVE fix we pushed unfortunately introduced a regression, fixed by\n> > https://bugs.python.org/issue36742\n> \n> The initial fix for this regression can be found at\n> https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3.\n> However, alone it would re-introduce this vulnerability, CVE-2019-9636, thus\n> it requires https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete.\n\nCVE-2019-10160 has been assigned to the security regression introduced with https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3"
					},
					{
						"isprivate": "0",
						"commentid": "12840456",
						"comment_count": "55",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-06-13 12:32:08 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 6\n\nVia RHSA-2019:1467 https://access.redhat.com/errata/RHSA-2019:1467"
					},
					{
						"isprivate": "0",
						"commentid": "12888543",
						"comment_count": "56",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-06-21 13:38:09 +0000",
						"thetext": "In reply to comment #55:\n> This issue has been addressed in the following products:\n> \n>   Red Hat Enterprise Linux 6\n> \n> Via RHSA-2019:1467 https://access.redhat.com/errata/RHSA-2019:1467\n\nCVE-2019-10160 was discovered by Red Hat during the development of the Red Hat Enterprise Linux 6 patch, thus RHSA-2019:1467 was directly shipped with the proper fix for CVE-2019-9636. The security regression CVE-2019-10160 was not introduced in RHEL 6."
					},
					{
						"isprivate": "0",
						"commentid": "13235871",
						"comment_count": "63",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-10-08 10:01:01 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.5 Extended Update Support\n\nVia RHSA-2019:2980 https://access.redhat.com/errata/RHSA-2019:2980"
					},
					{
						"isprivate": "0",
						"commentid": "13275627",
						"comment_count": "64",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-10-22 11:09:53 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.4 Advanced Update Support\n  Red Hat Enterprise Linux 7.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 7.4 Telco Extended Update Support\n\nVia RHSA-2019:3170 https://access.redhat.com/errata/RHSA-2019:3170"
					}
				]
			}
		},
		{
			"bug_id": 1688546,
			"feedback": [
				{
					"bug_id": 1688546,
					"comment": {
						"id": 912220,
						"karma": 1,
						"karma_critpath": 1,
						"timestamp": "2019-03-21 15:33:45",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
							"email": "eugenemah@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedora-hams"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 2935,
							"name": "imabug",
							"openid": "imabug.id.fedoraproject.org"
						},
						"user_id": 2935
					},
					"comment_id": 912220
				},
				{
					"bug_id": 1688546,
					"comment": {
						"id": 912732,
						"karma": 1,
						"karma_critpath": 1,
						"text": "Works here.",
						"timestamp": "2019-03-22 06:00:25",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1a8afd83231ef5ba905344806ba95b39f2abd77b399b0ee217ec3e6fa30a4825?s=24&d=retro",
							"email": "bojan@rexursive.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 198,
							"name": "bojan",
							"openid": "bojan.id.fedoraproject.org"
						},
						"user_id": 198
					},
					"comment_id": 912732
				},
				{
					"bug_id": 1688546,
					"comment": {
						"id": 913633,
						"karma": 1,
						"text": "no regressions noted",
						"timestamp": "2019-03-24 10:50:01",
						"update_id": 134462,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/636ff3eea65823b2c7349e36b691fd8c6d48f2a2158242b946762c0a14055425?s=24&d=retro",
							"email": "samoht0-bugzilla@yahoo.com",
							"groups": [
								{
									"name": "ipausers"
								}
							],
							"id": 2998,
							"name": "samoht0",
							"openid": "samoht0.id.fedoraproject.org"
						},
						"user_id": 2998
					},
					"comment_id": 913633
				},
				{
					"bug_id": 1688546,
					"comment": {
						"id": 913863,
						"karma": 1,
						"karma_critpath": 1,
						"text": "No regressions noted.",
						"timestamp": "2019-03-24 18:16:31",
						"update_id": 134461,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/e62cb974458dc33fcf2225462b8765e0aadcbbd698560c8f8dad6c3e23d5e47e?s=24&d=retro",
							"email": "dhgutteridge@hotmail.com",
							"groups": [
								{
									"name": "ipausers"
								}
							],
							"id": 194,
							"name": "dhgutteridge",
							"openid": "dhgutteridge.id.fedoraproject.org"
						},
						"user_id": 194
					},
					"comment_id": 913863
				}
			],
			"security": true,
			"title": "CVE-2019-9636 python3: python: Information Disclosure due to urlsplit improper NFKC normalization [fedora-all]",
			"bugzilla": {
				"bug_id": "1688546",
				"creation_ts": "2019-03-13 23:14:58 +0000",
				"short_desc": "CVE-2019-9636 python3: python: Information Disclosure due to urlsplit improper NFKC normalization [fedora-all]",
				"delta_ts": "2019-04-05 01:54:56 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"1688284"
				],
				"blocked": [
					{
						"bug_id": "1688543",
						"alias": "CVE-2019-9636",
						"creation_ts": "2019-03-13 23:14:41 +0000",
						"short_desc": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization",
						"delta_ts": "2023-03-24 14:38:03 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"1688544",
							"1688545",
							"1688546",
							"1688547",
							"1688549",
							"1688550",
							"1688552",
							"1689316",
							"1689317",
							"1689318",
							"1689319",
							"1689320",
							"1689321",
							"1689322",
							"1689323",
							"1689324",
							"1689325",
							"1689326",
							"1689327",
							"1689328",
							"1693973",
							"1693974",
							"1693975",
							"1694514",
							"1694515",
							"1694516",
							"1694517",
							"1696755",
							"1716744",
							"1744471",
							"1744472"
						],
						"blocked": [
							{
								"bug_id": "1688554",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2019:3170",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12543157",
								"comment_count": "0",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-03-13 23:14:41 +0000",
								"thetext": "A vulnerability was found in Python 2.7.x through 2.7.16 and 3.x through 3.7.2. An improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization could lead to an Information Disclosure (credentials, cookies, etc. that are cached against a given hostname) in the urllib.parse.urlsplit, urllib.parse.urlparse components. A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly.  \n\n\n\nReferences:\nhttps://bugs.python.org/issue36216\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html\n\nUptream Patch:\nhttps://github.com/python/cpython/pull/12201"
							},
							{
								"isprivate": "0",
								"commentid": "12543175",
								"comment_count": "1",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-03-13 23:15:22 +0000",
								"thetext": "Created python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1688546]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 1688552]\nAffects: fedora-all [bug 1688549]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1688550]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1688547]\nAffects: fedora-29 [bug 1688544]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-28 [bug 1688545]"
							},
							{
								"isprivate": "0",
								"commentid": "12618930",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-04-08 12:59:30 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2019:0710 https://access.redhat.com/errata/RHSA-2019:0710"
							},
							{
								"isprivate": "0",
								"commentid": "12643922",
								"comment_count": "26",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-04-16 14:06:00 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n\nVia RHSA-2019:0765 https://access.redhat.com/errata/RHSA-2019:0765"
							},
							{
								"isprivate": "0",
								"commentid": "12659445",
								"comment_count": "30",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-04-23 11:38:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:0806 https://access.redhat.com/errata/RHSA-2019:0806"
							},
							{
								"isprivate": "0",
								"commentid": "12677177",
								"comment_count": "34",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-04-29 14:30:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:0902 https://access.redhat.com/errata/RHSA-2019:0902"
							},
							{
								"isprivate": "0",
								"commentid": "12704354",
								"comment_count": "36",
								"who": {
									"text": "cstratak",
									"name": "Charalampos Stratakis"
								},
								"bug_when": "2019-05-06 09:31:45 +0000",
								"thetext": "The CVE fix we pushed unfortunately introduced a regression, fixed by https://bugs.python.org/issue36742"
							},
							{
								"isprivate": "0",
								"commentid": "12708013",
								"comment_count": "38",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-05-07 04:19:59 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:0981 https://access.redhat.com/errata/RHSA-2019:0981"
							},
							{
								"isprivate": "0",
								"commentid": "12708042",
								"comment_count": "39",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-05-07 04:21:57 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:0997 https://access.redhat.com/errata/RHSA-2019:0997"
							},
							{
								"isprivate": "0",
								"commentid": "12752203",
								"comment_count": "40",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-05-20 07:53:20 +0000",
								"thetext": "This flaw also affects the versions of python as shipped with Red Hat Enterprise Linux 5 and 6, which are, respectively, python 2.4 and 2.6."
							},
							{
								"isprivate": "0",
								"commentid": "12802636",
								"comment_count": "42",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-03 14:51:50 +0000",
								"thetext": "The flaw was reproduced both on python 2.4 shipped with Red Hat Enterprise Linux 5 and on python 2.6 shipped with Red Hat Enterprise Linux 6."
							},
							{
								"isprivate": "0",
								"commentid": "12802660",
								"comment_count": "43",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-03 15:01:36 +0000",
								"thetext": "This flaw affects applications that process untrusted URLs and store credentials, cookies or other kind of information based on the domain name of the URL, when encoded with Punycode/Internationalizing Domain Names in Applications (IDNA), more precisely the netloc component returned by urlparse()/urlsplit(). Assuming an application has cookies stored for the netloc \"redhat.com\", an attacker may construct a URL that, when encoded with IDNA and parsed through urlparse()/urlsplit() would indicate \"redhat.com\" as netloc, even though the connection would be made to the attacker-controlled host, possibly leaking the information that were associated with \"redhat.com\"."
							},
							{
								"isprivate": "0",
								"commentid": "12802665",
								"comment_count": "45",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-03 15:02:21 +0000",
								"thetext": "External References:\n\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html"
							},
							{
								"isprivate": "0",
								"commentid": "12806577",
								"comment_count": "48",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-04 07:44:02 +0000",
								"thetext": "netloc is the part of a URL that includes <user>:<password>@<host>:<port>.\n\nSee https://tools.ietf.org/html/rfc1808.html#section-2.1 for more information about netloc."
							},
							{
								"isprivate": "0",
								"commentid": "12812019",
								"comment_count": "50",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-05 10:23:25 +0000",
								"thetext": "In reply to comment #36:\n> The CVE fix we pushed unfortunately introduced a regression, fixed by\n> https://bugs.python.org/issue36742\n\nThe initial fix for this regression can be found at https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3.\nHowever, alone it would re-introduce this vulnerability, CVE-2019-9636, thus it requires https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete."
							},
							{
								"isprivate": "0",
								"commentid": "12815632",
								"comment_count": "53",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-06 09:19:11 +0000",
								"thetext": "In reply to comment #50:\n> In reply to comment #36:\n> > The CVE fix we pushed unfortunately introduced a regression, fixed by\n> > https://bugs.python.org/issue36742\n> \n> The initial fix for this regression can be found at\n> https://github.com/python/cpython/commit/\n> d537ab0ff9767ef024f26246899728f0116b1ec3.\n> However, alone it would re-introduce this vulnerability, CVE-2019-9636, thus\n> it requires\n> https://github.com/python/cpython/commit/\n> 8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete.\n\nReference:\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization2.html"
							},
							{
								"isprivate": "0",
								"commentid": "12825076",
								"comment_count": "54",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-10 07:56:45 +0000",
								"thetext": "CVE-2019-10160 has been assigned to this security regression.In reply to comment #50:\n> In reply to comment #36:\n> > The CVE fix we pushed unfortunately introduced a regression, fixed by\n> > https://bugs.python.org/issue36742\n> \n> The initial fix for this regression can be found at\n> https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3.\n> However, alone it would re-introduce this vulnerability, CVE-2019-9636, thus\n> it requires https://github.com/python/cpython/commit/8d0ef0b5edeae52960c7ed05ae8a12388324f87e to be complete.\n\nCVE-2019-10160 has been assigned to the security regression introduced with https://github.com/python/cpython/commit/d537ab0ff9767ef024f26246899728f0116b1ec3"
							},
							{
								"isprivate": "0",
								"commentid": "12840456",
								"comment_count": "55",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-06-13 12:32:08 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 6\n\nVia RHSA-2019:1467 https://access.redhat.com/errata/RHSA-2019:1467"
							},
							{
								"isprivate": "0",
								"commentid": "12888543",
								"comment_count": "56",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-06-21 13:38:09 +0000",
								"thetext": "In reply to comment #55:\n> This issue has been addressed in the following products:\n> \n>   Red Hat Enterprise Linux 6\n> \n> Via RHSA-2019:1467 https://access.redhat.com/errata/RHSA-2019:1467\n\nCVE-2019-10160 was discovered by Red Hat during the development of the Red Hat Enterprise Linux 6 patch, thus RHSA-2019:1467 was directly shipped with the proper fix for CVE-2019-9636. The security regression CVE-2019-10160 was not introduced in RHEL 6."
							},
							{
								"isprivate": "0",
								"commentid": "13235871",
								"comment_count": "63",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-10-08 10:01:01 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.5 Extended Update Support\n\nVia RHSA-2019:2980 https://access.redhat.com/errata/RHSA-2019:2980"
							},
							{
								"isprivate": "0",
								"commentid": "13275627",
								"comment_count": "64",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-10-22 11:09:53 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.4 Advanced Update Support\n  Red Hat Enterprise Linux 7.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 7.4 Telco Extended Update Support\n\nVia RHSA-2019:3170 https://access.redhat.com/errata/RHSA-2019:3170"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12543162",
						"comment_count": "0",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-03-13 23:14:58 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "12543163",
						"comment_count": "1",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-03-13 23:15:00 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=high\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1688543,1688546\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "12566304",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 13:19:08 +0000",
						"thetext": "python3-3.7.2-8.fc30 has been submitted as an update to Fedora 30. https://bodhi.fedoraproject.org/updates/FEDORA-2019-a122fe704d"
					},
					{
						"isprivate": "0",
						"commentid": "12566309",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 13:19:49 +0000",
						"thetext": "python3-3.7.2-5.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-243442e600"
					},
					{
						"isprivate": "0",
						"commentid": "12566314",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 13:20:24 +0000",
						"thetext": "python3-3.6.8-3.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2019-86f32cbab1"
					},
					{
						"isprivate": "0",
						"commentid": "12567836",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 19:12:51 +0000",
						"thetext": "python3-3.7.2-8.fc30 has been pushed to the Fedora 30 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-a122fe704d"
					},
					{
						"isprivate": "0",
						"commentid": "12568198",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 21:19:15 +0000",
						"thetext": "python3-3.7.2-5.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-243442e600"
					},
					{
						"isprivate": "0",
						"commentid": "12568290",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-21 21:49:08 +0000",
						"thetext": "python3-3.6.8-3.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-86f32cbab1"
					},
					{
						"isprivate": "0",
						"commentid": "12573713",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-25 06:05:34 +0000",
						"thetext": "python3-3.7.2-5.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12592752",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-29 19:19:14 +0000",
						"thetext": "python3-3.7.2-8.fc30 has been pushed to the Fedora 30 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12611830",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-04-05 01:54:56 +0000",
						"thetext": "python3-3.6.8-3.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3-3.7.2-5.fc29",
			"release_id": 23,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3-debug",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-devel",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-debugsource",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-idle",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-libs",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-test",
						"version": "3.7.2",
						"release": "5.fc29",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 912142,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2019-03-21 13:19:44",
			"update_id": 134461,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1688543,
						"parent": true,
						"security": true,
						"title": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization"
					},
					"bug_id": 1688543,
					"comment_id": 912220
				},
				{
					"bug": {
						"bug_id": 1688546,
						"security": true,
						"title": "CVE-2019-9636 python3: python: Information Disclosure due to urlsplit improper NFKC normalization [fedora-all]"
					},
					"bug_id": 1688546,
					"comment_id": 912220
				}
			],
			"id": 912220,
			"karma": 1,
			"karma_critpath": 1,
			"timestamp": "2019-03-21 15:33:45",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
				"email": "eugenemah@gmail.com",
				"groups": [
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedora-hams"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 2935,
				"name": "imabug",
				"openid": "imabug.id.fedoraproject.org"
			},
			"user_id": 2935
		},
		{
			"id": 912568,
			"text": "This update has been pushed to testing.",
			"timestamp": "2019-03-21 21:19:50",
			"update_id": 134461,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1688543,
						"parent": true,
						"security": true,
						"title": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization"
					},
					"bug_id": 1688543,
					"comment_id": 912732
				},
				{
					"bug": {
						"bug_id": 1688546,
						"security": true,
						"title": "CVE-2019-9636 python3: python: Information Disclosure due to urlsplit improper NFKC normalization [fedora-all]"
					},
					"bug_id": 1688546,
					"comment_id": 912732
				}
			],
			"id": 912732,
			"karma": 1,
			"karma_critpath": 1,
			"text": "Works here.",
			"timestamp": "2019-03-22 06:00:25",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1a8afd83231ef5ba905344806ba95b39f2abd77b399b0ee217ec3e6fa30a4825?s=24&d=retro",
				"email": "bojan@rexursive.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 198,
				"name": "bojan",
				"openid": "bojan.id.fedoraproject.org"
			},
			"user_id": 198
		},
		{
			"id": 913164,
			"karma": 1,
			"text": "Works great!  LGTM!  =)",
			"timestamp": "2019-03-22 22:03:09",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/307632fc7188138f052f244345e779451863879298f2e6d73023011a05b1f1f6?s=24&d=retro",
				"email": "besser82.fpo@gmail.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "designteam"
					},
					{
						"name": "shogun-ca"
					},
					{
						"name": "alt-gtk-de-sig"
					}
				],
				"id": 206,
				"name": "besser82",
				"openid": "besser82.id.fedoraproject.org"
			},
			"user_id": 206
		},
		{
			"id": 913464,
			"karma": 1,
			"text": "No regressions found",
			"timestamp": "2019-03-23 12:37:10",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/18a0ed8e439e9913c577f9c4d260a917530f0021fefb8d47a6788f2a10545202?s=24&d=retro",
				"email": "cacouret.renault@gmail.com",
				"groups": [
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "l10n"
					},
					{
						"name": "cvsl10n"
					},
					{
						"name": "l10n-commits"
					},
					{
						"name": "gitmuffin"
					}
				],
				"id": 208,
				"name": "renault",
				"openid": "renault.id.fedoraproject.org"
			},
			"user_id": 208
		},
		{
			"id": 913517,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2019-03-23 14:57:51",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/054959f4db5d1ad8f22cae1ba73e26ebfd3edd6690c21cc7ee00608f294ff22a?s=24&d=retro",
				"email": "cserpentis@gmail.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 739,
				"name": "cserpentis",
				"openid": "cserpentis.id.fedoraproject.org"
			},
			"user_id": 739
		},
		{
			"id": 913529,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2019-03-23 15:17:30",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/3cd1b1919767c5d86c84f4026cf733611effd8daaa629553453789b84f0ba1a8?s=24&d=retro",
				"email": "flexo3001@pm.me",
				"id": 3451,
				"name": "flexo3001",
				"openid": "flexo3001.id.fedoraproject.org"
			},
			"user_id": 3451
		},
		{
			"id": 913530,
			"text": "This update has been submitted for batched by bodhi. ",
			"timestamp": "2019-03-23 15:17:31",
			"update_id": 134461,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 913566,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2019-03-23 23:45:40",
			"update_id": 134461,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1688543,
						"parent": true,
						"security": true,
						"title": "CVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization"
					},
					"bug_id": 1688543,
					"comment_id": 913863
				},
				{
					"bug": {
						"bug_id": 1688546,
						"security": true,
						"title": "CVE-2019-9636 python3: python: Information Disclosure due to urlsplit improper NFKC normalization [fedora-all]"
					},
					"bug_id": 1688546,
					"comment_id": 913863
				}
			],
			"id": 913863,
			"karma": 1,
			"karma_critpath": 1,
			"text": "No regressions noted.",
			"timestamp": "2019-03-24 18:16:31",
			"update_id": 134461,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/e62cb974458dc33fcf2225462b8765e0aadcbbd698560c8f8dad6c3e23d5e47e?s=24&d=retro",
				"email": "dhgutteridge@hotmail.com",
				"groups": [
					{
						"name": "ipausers"
					}
				],
				"id": 194,
				"name": "dhgutteridge",
				"openid": "dhgutteridge.id.fedoraproject.org"
			},
			"user_id": 194
		},
		{
			"id": 914529,
			"text": "This update has been pushed to stable.",
			"timestamp": "2019-03-25 06:08:28",
			"update_id": 134461,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"date_pushed": "2019-03-25 06:03:54",
	"date_stable": "2019-03-25 06:03:54",
	"date_submitted": "2019-03-21 13:19:44",
	"date_testing": "2019-03-21 21:18:41",
	"karma": 7,
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2019-9636",
	"pushed": true,
	"release": {
		"branch": "f29",
		"candidate_tag": "f29-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f29",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 29",
		"mail_template": "fedora_errata_template",
		"name": "F29",
		"override_tag": "f29-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f29-signing-pending",
		"pending_stable_tag": "f29-updates-pending",
		"pending_testing_tag": "f29-updates-testing-pending",
		"stable_tag": "f29-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f29-updates-testing",
		"version": "29"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "high",
	"stable_karma": 6,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3-3.7.2-5.fc29",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2019-243442e600",
	"unstable_karma": -2,
	"updateid": "FEDORA-2019-243442e600",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "f9d8d5df8a195eb25c923a8498ba2da834a593b5"
}
