{
	"alias": "FEDORA-2019-ec55814c1c",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1673642,
			"parent": true,
			"security": true,
			"title": "CVE-2019-6975 python-django: memory exhaustion in django.utils.numberformat.format()",
			"bugzilla": {
				"bug_id": "1673642",
				"alias": "CVE-2019-6975",
				"creation_ts": "2019-02-07 16:43:23 +0000",
				"short_desc": "CVE-2019-6975 python-django: memory exhaustion in django.utils.numberformat.format()",
				"delta_ts": "2021-10-27 03:23:03 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1686074",
					"1676321",
					"1676322",
					"1676323",
					"1676324",
					"1676325",
					"1676326",
					"1676327",
					"1676328",
					"1677295",
					"1677296",
					"1677297",
					"1678264",
					"1678265",
					"1678266"
				],
				"blocked": [
					{
						"bug_id": "1673649",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12429632",
						"comment_count": "0",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-02-07 16:43:23 +0000",
						"thetext": "A vulnerability was found in Django before versions 2.2b1, 2.1.6, 2.0.11, 1.11.19. If django.utils.numberformat.format(), used by contrib.admin as well as the the floatformat, filesizeformat, and intcomma templates filters, received a Decimal with a large number of digits or a large exponent, it could lead to significant memory usage due to a call to '{:f}'.format(). To avoid this, decimals with more than 200 digits are now formatted using scientific notation.\n\n\nReferences:\nhttps://www.djangoproject.com/security/"
					},
					{
						"isprivate": "0",
						"commentid": "12429670",
						"comment_count": "1",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-02-07 16:55:43 +0000",
						"thetext": "Acknowledgments:\n\nName: the Django project"
					},
					{
						"isprivate": "0",
						"commentid": "12438365",
						"comment_count": "2",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2019-02-11 16:47:48 +0000",
						"thetext": "The associated Django releases are now public https://www.djangoproject.com/weblog/2019/feb/11/security-releases/"
					},
					{
						"isprivate": "0",
						"commentid": "12446300",
						"comment_count": "3",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2019-02-12 01:20:21 +0000",
						"thetext": "All versions of python-django supplied by Red Hat OpenStack Platform (1.6.11, 1.8.14, 1.8.18, & 1.11.10) are susceptible."
					},
					{
						"isprivate": "0",
						"commentid": "12457646",
						"comment_count": "6",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2019-02-14 13:39:52 +0000",
						"thetext": "Ceph and Gluster are affected since the shipped versions of python-django includes unpatched source code.\n\nCeph(2,3)  : python-django-1.8.18-1.el7ost\nGluster    : python-django-1.11.15-4.el7rhgs"
					},
					{
						"isprivate": "0",
						"commentid": "12465117",
						"comment_count": "8",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-02-18 11:50:41 +0000",
						"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1678266]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 1678265]\nAffects: fedora-all [bug 1678264]"
					},
					{
						"isprivate": "0",
						"commentid": "12518957",
						"comment_count": "9",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-03-06 15:01:01 +0000",
						"thetext": "Upstream patches:\n[1.11.x branch] https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227\n[2.0.x branch] https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676\n[2.1.x branch] https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3\n[2.2.x branch] https://github.com/django/django/commit/83ab3e26647f6a50cdfac01ecf735cad540b2f35"
					},
					{
						"isprivate": "0",
						"commentid": "14953101",
						"comment_count": "16",
						"who": {
							"text": "slong",
							"name": "Summer Long"
						},
						"bug_when": "2021-04-12 00:03:28 +0000",
						"thetext": "Statement:\n\nThis issue did not affect the versions of python-django as shipped with Red Hat Update Infrastructure 3 as the vulnerable code is not present.\n\nAlthough Red Hat Satellite 6 uses the vulnerable component python-django, it does not use the module django.utils.numberformat, so it's not possible to trigger this vulnerability. Hence, Red Hat Satellite 6 is not vulnerable to this issue.\n\nIn Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-django package."
					}
				]
			}
		},
		{
			"bug_id": 1678264,
			"security": true,
			"title": "CVE-2019-6975 python-django: memory exhaustion in django.utils.numberformat.format() [fedora-all]",
			"bugzilla": {
				"bug_id": "1678264",
				"creation_ts": "2019-02-18 11:50:28 +0000",
				"short_desc": "CVE-2019-6975 python-django: memory exhaustion in django.utils.numberformat.format() [fedora-all]",
				"delta_ts": "2019-03-01 23:10:38 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1673642",
						"alias": "CVE-2019-6975",
						"creation_ts": "2019-02-07 16:43:23 +0000",
						"short_desc": "CVE-2019-6975 python-django: memory exhaustion in django.utils.numberformat.format()",
						"delta_ts": "2021-10-27 03:23:03 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1686074",
							"1676321",
							"1676322",
							"1676323",
							"1676324",
							"1676325",
							"1676326",
							"1676327",
							"1676328",
							"1677295",
							"1677296",
							"1677297",
							"1678264",
							"1678265",
							"1678266"
						],
						"blocked": [
							{
								"bug_id": "1673649",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12429632",
								"comment_count": "0",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-02-07 16:43:23 +0000",
								"thetext": "A vulnerability was found in Django before versions 2.2b1, 2.1.6, 2.0.11, 1.11.19. If django.utils.numberformat.format(), used by contrib.admin as well as the the floatformat, filesizeformat, and intcomma templates filters, received a Decimal with a large number of digits or a large exponent, it could lead to significant memory usage due to a call to '{:f}'.format(). To avoid this, decimals with more than 200 digits are now formatted using scientific notation.\n\n\nReferences:\nhttps://www.djangoproject.com/security/"
							},
							{
								"isprivate": "0",
								"commentid": "12429670",
								"comment_count": "1",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-02-07 16:55:43 +0000",
								"thetext": "Acknowledgments:\n\nName: the Django project"
							},
							{
								"isprivate": "0",
								"commentid": "12438365",
								"comment_count": "2",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2019-02-11 16:47:48 +0000",
								"thetext": "The associated Django releases are now public https://www.djangoproject.com/weblog/2019/feb/11/security-releases/"
							},
							{
								"isprivate": "0",
								"commentid": "12446300",
								"comment_count": "3",
								"who": {
									"text": "ntait",
									"name": "Nick Tait"
								},
								"bug_when": "2019-02-12 01:20:21 +0000",
								"thetext": "All versions of python-django supplied by Red Hat OpenStack Platform (1.6.11, 1.8.14, 1.8.18, & 1.11.10) are susceptible."
							},
							{
								"isprivate": "0",
								"commentid": "12457646",
								"comment_count": "6",
								"who": {
									"text": "hvyas",
									"name": "Hardik Vyas"
								},
								"bug_when": "2019-02-14 13:39:52 +0000",
								"thetext": "Ceph and Gluster are affected since the shipped versions of python-django includes unpatched source code.\n\nCeph(2,3)  : python-django-1.8.18-1.el7ost\nGluster    : python-django-1.11.15-4.el7rhgs"
							},
							{
								"isprivate": "0",
								"commentid": "12465117",
								"comment_count": "8",
								"who": {
									"text": "thoger",
									"name": "Tomas Hoger"
								},
								"bug_when": "2019-02-18 11:50:41 +0000",
								"thetext": "Created django:1.6/python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1678266]\n\n\nCreated python-django tracking bugs for this issue:\n\nAffects: epel-7 [bug 1678265]\nAffects: fedora-all [bug 1678264]"
							},
							{
								"isprivate": "0",
								"commentid": "12518957",
								"comment_count": "9",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2019-03-06 15:01:01 +0000",
								"thetext": "Upstream patches:\n[1.11.x branch] https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227\n[2.0.x branch] https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676\n[2.1.x branch] https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3\n[2.2.x branch] https://github.com/django/django/commit/83ab3e26647f6a50cdfac01ecf735cad540b2f35"
							},
							{
								"isprivate": "0",
								"commentid": "14953101",
								"comment_count": "16",
								"who": {
									"text": "slong",
									"name": "Summer Long"
								},
								"bug_when": "2021-04-12 00:03:28 +0000",
								"thetext": "Statement:\n\nThis issue did not affect the versions of python-django as shipped with Red Hat Update Infrastructure 3 as the vulnerable code is not present.\n\nAlthough Red Hat Satellite 6 uses the vulnerable component python-django, it does not use the module django.utils.numberformat, so it's not possible to trigger this vulnerability. Hence, Red Hat Satellite 6 is not vulnerable to this issue.\n\nIn Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-django package."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12465110",
						"comment_count": "0",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-02-18 11:50:28 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "12465112",
						"comment_count": "1",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-02-18 11:50:30 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1673642,1678264\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "12472921",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-20 10:58:24 +0000",
						"thetext": "python-django-2.0.12-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-a9110a7812"
					},
					{
						"isprivate": "0",
						"commentid": "12473074",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-20 11:40:40 +0000",
						"thetext": "python-django-2.0.12-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2019-f2d2b5fc88"
					},
					{
						"isprivate": "0",
						"commentid": "12473254",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-20 12:33:33 +0000",
						"thetext": "python-django-2.0.13-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2019-9760933547"
					},
					{
						"isprivate": "0",
						"commentid": "12473355",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-20 12:48:37 +0000",
						"thetext": "python-django-2.0.13-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-ec55814c1c"
					},
					{
						"isprivate": "0",
						"commentid": "12475547",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-21 01:28:10 +0000",
						"thetext": "python-django-2.0.13-1.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-9760933547"
					},
					{
						"isprivate": "0",
						"commentid": "12475779",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-21 03:47:21 +0000",
						"thetext": "python-django-2.0.13-1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-ec55814c1c"
					},
					{
						"isprivate": "0",
						"commentid": "12503863",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-01 02:38:22 +0000",
						"thetext": "python-django-2.0.13-1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12507402",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-03-01 23:10:38 +0000",
						"thetext": "python-django-2.0.13-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-django-2.0.13-1.fc29",
			"release_id": 23,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-django-doc",
						"version": "2.0.13",
						"release": "1.fc29",
						"arch": "noarch"
					},
					{
						"name": "python-django-bash-completion",
						"version": "2.0.13",
						"release": "1.fc29",
						"arch": "noarch"
					},
					{
						"name": "python3-django",
						"version": "2.0.13",
						"release": "1.fc29",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-django",
						"version": "2.0.13",
						"release": "1.fc29",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 897577,
			"text": "This update has been submitted for testing by mrunge. ",
			"timestamp": "2019-02-20 12:48:32",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 897580,
			"text": "This update has obsoleted [python-django-2.0.12-1.fc29](https://bodhi.fedoraproject.org/updates/FEDORA-2019-a9110a7812), and has inherited its bugs and notes.",
			"timestamp": "2019-02-20 12:48:34",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 897924,
			"text": "This update has been pushed to testing.",
			"timestamp": "2019-02-21 03:47:45",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 898522,
			"karma": 1,
			"text": "Works great!  LGTM!  =)",
			"timestamp": "2019-02-22 09:18:35",
			"update_id": 132015,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/28bacfa3be75032390ac2c7a34599aeb825c3b62b2c55ef64821d2fc023b56cb?s=24&d=retro",
				"email": "besser82.fpo@gmail.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "designteam"
					},
					{
						"name": "shogun-ca"
					},
					{
						"name": "alt-gtk-de-sig"
					}
				],
				"id": 206,
				"name": "besser82",
				"openid": "besser82.id.fedoraproject.org"
			},
			"user_id": 206
		},
		{
			"id": 901245,
			"text": "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2019-02-28 06:01:17",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 901280,
			"text": "This update has been submitted for batched by mrunge. ",
			"timestamp": "2019-02-28 06:46:24",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 901603,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2019-02-28 23:46:14",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 901682,
			"text": "This update has been pushed to stable.",
			"timestamp": "2019-03-01 02:39:21",
			"update_id": 132015,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2019-03-01 02:37:52",
	"date_stable": "2019-03-01 02:37:52",
	"date_submitted": "2019-02-20 12:48:32",
	"date_testing": "2019-02-21 03:47:04",
	"karma": 1,
	"meets_testing_requirements": true,
	"notes": "fix CVE-2019-6975: Memory exhaustion in django.utils.numberformat.format()\n\n----\n\nfix CVE-2019-6975: Memory exhaustion in django.utils.numberformat.format()",
	"pushed": true,
	"release": {
		"branch": "f29",
		"candidate_tag": "f29-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f29",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 29",
		"mail_template": "fedora_errata_template",
		"name": "F29",
		"override_tag": "f29-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f29-signing-pending",
		"pending_stable_tag": "f29-updates-pending",
		"pending_testing_tag": "f29-updates-testing-pending",
		"stable_tag": "f29-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f29-updates-testing",
		"version": "29"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-django-2.0.13-1.fc29",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2019-ec55814c1c",
	"unstable_karma": -3,
	"updateid": "FEDORA-2019-ec55814c1c",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/a44256d99b54b87430ffaae85f0645968ec25a74a78abea5b026b1698d56ad9e?s=24&d=retro",
		"email": "mrunge@redhat.com",
		"groups": [
			{
				"name": "proventesters"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "centosproject-email-aliases"
			},
			{
				"name": "gitovirt"
			},
			{
				"name": "sig-cloud"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "gitnodejs-packaging"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "sig-extras"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "sig-opstools"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sig-messaging"
			},
			{
				"name": "openstack-sig"
			}
		],
		"id": 189,
		"name": "mrunge",
		"openid": "mrunge.id.fedoraproject.org"
	},
	"version_hash": "7a793d16d7bf602e13b4d5a1e0293c1e253ee8c1"
}
