{
	"alias": "FEDORA-2015-4642",
	"bugs": [
		{
			"bug_id": 1204829,
			"parent": true,
			"security": true,
			"title": "PyYAML: assert failure when processing wrapped strings",
			"bugzilla": {
				"bug_id": "1204829",
				"creation_ts": "2015-03-23 15:03:02 +0000",
				"short_desc": "PyYAML: assert failure when processing wrapped strings",
				"delta_ts": "2019-09-29 13:30:16 +0000",
				"bug_status": "CLOSED",
				"resolution": "WONTFIX",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1204830",
					"1204832",
					"1204833"
				],
				"blocked": [
					{
						"bug_id": "1204835",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8074155",
						"comment_count": "0",
						"who": {
							"text": "mprpic",
							"name": "Martin Prpič"
						},
						"bug_when": "2015-03-23 15:03:02 +0000",
						"thetext": "An assertion failure was found in the way the PyYAML library parsed wrapped strings. An attacker able to load specially crafted YAML input into an application using PyYAML could cause the application to crash.\n\nThis is the same flaw as CVE-2014-9130 but in the Python implementation of the YAML library. MITRE recommends it should be a separate issue:\n\nhttp://seclists.org/oss-sec/2014/q4/854\n\nUpstream patch:\n\nhttps://bitbucket.org/xi/pyyaml/commits/ddf211a41bb231c365fece5599b7e484e6dc33fc"
					},
					{
						"isprivate": "0",
						"commentid": "8074167",
						"comment_count": "1",
						"who": {
							"text": "mprpic",
							"name": "Martin Prpič"
						},
						"bug_when": "2015-03-23 15:04:20 +0000",
						"thetext": "\nCreated PyYAML tracking bugs for this issue:\n\nAffects: fedora-all [bug 1204830]\nAffects: epel-5 [bug 1204832]"
					},
					{
						"isprivate": "0",
						"commentid": "8074168",
						"comment_count": "2",
						"who": {
							"text": "mprpic",
							"name": "Martin Prpič"
						},
						"bug_when": "2015-03-23 15:04:24 +0000",
						"thetext": "\nCreated python26-PyYAML tracking bugs for this issue:\n\nAffects: epel-5 [bug 1204833]"
					},
					{
						"isprivate": "0",
						"commentid": "8114697",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-05 14:33:26 +0000",
						"thetext": "PyYAML-3.11-7.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8114713",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-05 14:35:48 +0000",
						"thetext": "PyYAML-3.10-11.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8128110",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-09 16:55:59 +0000",
						"thetext": "PyYAML-3.09-11.el5 has been pushed to the Fedora EPEL 5 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8165446",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-21 18:36:20 +0000",
						"thetext": "PyYAML-3.11-7.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1204830,
			"security": true,
			"title": "PyYAML: assert failure when processing wrapped strings [fedora-all]",
			"bugzilla": {
				"bug_id": "1204830",
				"creation_ts": "2015-03-23 15:04:04 +0000",
				"short_desc": "PyYAML: assert failure when processing wrapped strings [fedora-all]",
				"delta_ts": "2015-04-21 18:36:18 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1204829",
						"creation_ts": "2015-03-23 15:03:02 +0000",
						"short_desc": "PyYAML: assert failure when processing wrapped strings",
						"delta_ts": "2019-09-29 13:30:16 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1204830",
							"1204832",
							"1204833"
						],
						"blocked": [
							{
								"bug_id": "1204835",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "8074155",
								"comment_count": "0",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-03-23 15:03:02 +0000",
								"thetext": "An assertion failure was found in the way the PyYAML library parsed wrapped strings. An attacker able to load specially crafted YAML input into an application using PyYAML could cause the application to crash.\n\nThis is the same flaw as CVE-2014-9130 but in the Python implementation of the YAML library. MITRE recommends it should be a separate issue:\n\nhttp://seclists.org/oss-sec/2014/q4/854\n\nUpstream patch:\n\nhttps://bitbucket.org/xi/pyyaml/commits/ddf211a41bb231c365fece5599b7e484e6dc33fc"
							},
							{
								"isprivate": "0",
								"commentid": "8074167",
								"comment_count": "1",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-03-23 15:04:20 +0000",
								"thetext": "\nCreated PyYAML tracking bugs for this issue:\n\nAffects: fedora-all [bug 1204830]\nAffects: epel-5 [bug 1204832]"
							},
							{
								"isprivate": "0",
								"commentid": "8074168",
								"comment_count": "2",
								"who": {
									"text": "mprpic",
									"name": "Martin Prpič"
								},
								"bug_when": "2015-03-23 15:04:24 +0000",
								"thetext": "\nCreated python26-PyYAML tracking bugs for this issue:\n\nAffects: epel-5 [bug 1204833]"
							},
							{
								"isprivate": "0",
								"commentid": "8114697",
								"comment_count": "4",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-04-05 14:33:26 +0000",
								"thetext": "PyYAML-3.11-7.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "8114713",
								"comment_count": "5",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-04-05 14:35:48 +0000",
								"thetext": "PyYAML-3.10-11.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "8128110",
								"comment_count": "6",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-04-09 16:55:59 +0000",
								"thetext": "PyYAML-3.09-11.el5 has been pushed to the Fedora EPEL 5 stable repository.  If problems still persist, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "8165446",
								"comment_count": "7",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2015-04-21 18:36:20 +0000",
								"thetext": "PyYAML-3.11-7.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8074159",
						"comment_count": "0",
						"who": {
							"text": "mprpic",
							"name": "Martin Prpič"
						},
						"bug_when": "2015-03-23 15:04:04 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof Fedora.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate.\n\n[bug automatically created by: add-tracking-bugs]"
					},
					{
						"isprivate": "0",
						"commentid": "8074160",
						"comment_count": "1",
						"who": {
							"text": "mprpic",
							"name": "Martin Prpič"
						},
						"bug_when": "2015-03-23 15:04:08 +0000",
						"thetext": "\nUse the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1204829,1204830\n\n# Description of your update\nnotes=Security fix for \n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi update submission link instead:\n\nhttps://admin.fedoraproject.org/updates/new/?type_=security&bugs=1204829,1204830"
					},
					{
						"isprivate": "0",
						"commentid": "8074949",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-03-23 17:59:06 +0000",
						"thetext": "PyYAML-3.11-7.fc21 has been submitted as an update for Fedora 21.\nhttps://admin.fedoraproject.org/updates/PyYAML-3.11-7.fc21"
					},
					{
						"isprivate": "0",
						"commentid": "8074950",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-03-23 18:00:24 +0000",
						"thetext": "PyYAML-3.10-11.fc20 has been submitted as an update for Fedora 20.\nhttps://admin.fedoraproject.org/updates/PyYAML-3.10-11.fc20"
					},
					{
						"isprivate": "0",
						"commentid": "8089285",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-03-26 21:26:49 +0000",
						"thetext": "Package PyYAML-3.10-11.fc20:\n* should fix your issue,\n* was pushed to the Fedora 20 testing repository,\n* should be available at your local mirror within two days.\nUpdate it with:\n# su -c 'yum update --enablerepo=updates-testing PyYAML-3.10-11.fc20'\nas soon as you are able to.\nPlease go to the following url:\nhttps://admin.fedoraproject.org/updates/FEDORA-2015-4477/PyYAML-3.10-11.fc20\nthen log in and leave karma (feedback)."
					},
					{
						"isprivate": "0",
						"commentid": "8114246",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-04 22:37:53 +0000",
						"thetext": "PyYAML-3.11-7.fc22 has been submitted as an update for Fedora 22.\nhttps://admin.fedoraproject.org/updates/PyYAML-3.11-7.fc22"
					},
					{
						"isprivate": "0",
						"commentid": "8114696",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-05 14:33:22 +0000",
						"thetext": "PyYAML-3.11-7.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8114712",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-05 14:35:46 +0000",
						"thetext": "PyYAML-3.10-11.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8165445",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-21 18:36:18 +0000",
						"thetext": "PyYAML-3.11-7.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"nvr": "PyYAML-3.11-7.fc21",
			"signed": true,
			"type": "rpm",
			"package": {
				"armv7hl": [
					{
						"name": "python3-PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "armv7hl"
					},
					{
						"name": "PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "armv7hl"
					},
					{
						"name": "PyYAML-debuginfo",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python3-PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "i686"
					},
					{
						"name": "PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "i686"
					},
					{
						"name": "PyYAML-debuginfo",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "i686"
					}
				],
				"src": [
					{
						"name": "PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "x86_64"
					},
					{
						"name": "PyYAML-debuginfo",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "x86_64"
					},
					{
						"name": "python3-PyYAML",
						"version": "3.11",
						"release": "7.fc21",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 283429,
			"text": "This update has been submitted for testing by jeckersb. ",
			"timestamp": "2015-03-23 17:59:08",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283430,
			"text": "Taskotron: depcheck test PASSED on i386. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/50937/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-03-23 18:12:06",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/taskotron-24.png",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 283431,
			"text": "Taskotron: depcheck test PASSED on x86_64. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/50937/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-03-23 18:13:15",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/taskotron-24.png",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 283432,
			"text": "This update is currently being pushed to the Fedora 21 testing updates repository.",
			"timestamp": "2015-03-24 21:53:54",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283433,
			"text": "This update has been pushed to testing",
			"timestamp": "2015-03-26 21:57:08",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283434,
			"text": "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2015-04-02 22:42:12",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283435,
			"text": "This update has been submitted for stable by jeckersb. ",
			"timestamp": "2015-04-04 21:34:21",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283436,
			"text": "Taskotron: upgradepath test FAILED on noarch. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/55100/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-04-04 22:01:28",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/taskotron-24.png",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 283437,
			"text": "Automatic push to stable based on karma has been disabled for this update due to failure of an AutoQA test. Update submitter, please check the AutoQA test result and see if there is a valid problem to be fixed here, and fix it if so. If the failure is a mistake on AutoQA's part, you can re-enable the automatic push feature for this update if you like, or push it stable manually once it reaches the requirements under the Updates Policy.",
			"timestamp": "2015-04-04 22:01:29",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283438,
			"text": "This update is currently being pushed to the Fedora 21 stable updates repository.",
			"timestamp": "2015-04-05 02:21:43",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 283439,
			"text": "This update has been pushed to stable",
			"timestamp": "2015-04-05 14:33:28",
			"update_id": 34104,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2015-04-05 14:33:28",
	"date_stable": "2015-04-05 14:33:28",
	"date_submitted": "2015-03-23 17:58:58",
	"date_testing": "2015-03-26 21:57:08",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2014-9130",
	"pushed": true,
	"release": {
		"branch": "f21",
		"candidate_tag": "f21-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f21",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 21",
		"mail_template": "fedora_errata_template",
		"name": "F21",
		"override_tag": "f21-override",
		"package_manager": "dnf",
		"pending_stable_tag": "f21-updates-pending",
		"pending_testing_tag": "f21-updates-testing-pending",
		"stable_tag": "f21-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f21-updates-testing",
		"version": "21"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"title": "PyYAML-3.11-7.fc21",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2015-4642",
	"unstable_karma": -3,
	"updateid": "FEDORA-2015-4642",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/760ebf165932e564e82499dbf16754a49484f1a3fcd9e61281465b6d9ff7c6f1?s=24&d=retro",
		"email": "jeckersb@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "gitaeolus"
			},
			{
				"name": "cla_redhat"
			},
			{
				"name": "giterlang"
			},
			{
				"name": "func"
			},
			{
				"name": "gitcobbler"
			}
		],
		"id": 270,
		"name": "jeckersb",
		"openid": "jeckersb.id.fedoraproject.org"
	},
	"version_hash": "6029cf3ee684464ade25e2a7034dbebd8facb9dc"
}
